### ISSUE TITLE
kickstyle 0 is broken

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#106]
1.5 introduced new behaviour for when jumping during a wall run where the angle to the horizontal of the jump is dependant on the angle of the camera view.

The kickstyle variable was added as a way for a player to use the 1.4 behaviour where the angle was static. However it doesn't work correctly. Instead without holding W/Up it makes you jump directly jump, as if you just pressed Space while standing still on the ground. Additionally it converts all wall kicks into wall climbs.

**Comment by IceflowRE** [comment]
I can confirm that it converts all wall kicks into wall climbs.
With the other i dont really know what do you mean (Sry)

**Comment by bonifarz** [comment]
Please note that wall *kicks* and wall *jumps* are two different moves.
The *kickstyle* refers to an *experiment* to simplify kick and climb mechanics, which was reverted to the old behavior. This also included an option to automatically turn 180° to the side during wall kick. There are some additional variables to define this automatic behavior when enabling this experimental *kick* style. (Which - honestly - is not recommended!)
Wall *jumps* on the other hand have become much more useful than in Elara edition. Previously, they just pushed you upwards like a (ground) jump, now you have full control, just as during an *impulse boost*. This may be annoying at first, but once you get used to it, I bet you don't want to go back to the old *wall-jump* style.

**Comment by bonifarz** [comment]
Ah, now I see the problem. BUT: If you want the old wall-jump mechanics, a *kickoffangle* default value of 60° seems odd. I guess it should be something around 20-30°?

**Comment by qreeves** [comment]
@bonifarz Yeah, but the new default is better, unless you want to replicate 1.4 settings, in which case you can change those vars as well.
