### ISSUE TITLE
problem in the botoffset command in offline mode

### ISSUE THREAD

**Issue by ISynapsyI** [red-eclipse/base#111]
When i tried to play offline, the botoffset command didn't work (see screenshot). btw I was not sure where to post this comment (whether here or on the forum....), if i did wrong: sorry :/

![botoffset_pb](https://cloud.githubusercontent.com/assets/11562643/6792712/0a98c1aa-d1bb-11e4-885b-f67cb026b4dd.png)

**Comment by ZeroKnight** [comment]
You're playing Co-Op, so you need to use `coopbalance`.

>in coop, bot team gets this many players for each human
>default: 1.5
