### ISSUE TITLE
Player RGB color sliders in Profile don't go all the way

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#119]
I know this is a small issue, but it should still be fixed.
In the Profile section, the RGB sliders for the player model color doesn't reach the end of the bar, just stops about 20 px from it.

**Comment by gynter** [comment]
Hmm I tought that this was intended to be that way, IMO it's easier to scroll the color all the way up. In 1.4 scrolling to the end usually ended with value 0, since I unfocused the scrollbar.

**Comment by coornio** [comment]
I looked into it, since it was my code originally. I can definitely say it's not the cubescript's fault. The point-form slider is perfect, but the bar form is borked, so look for your issue in the source code. 

Looking back at my cubescript patches makes me cringe a little..
