### ISSUE TITLE
What happened to "View options" in the Profile menu?

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#121]
In Red Eclipse V1.4, there was a tab called "View options" in the Profile menu, that allowed you to control how you saw other players in-game. This tab is now gone. What happened to it?

**Comment by shirepirate** [comment]
it was removed in SVN r6943
https://svn.icculus.org/redeclipse/?view=rev&revision=6943

**Comment by ZeroKnight** [comment]
>it was removed in SVN r6943
Beat me by seconds, haha.

I'm curious as to why it was removed, though.

**Comment by freezurbern** [comment]
Perhaps to prevent people from making the enemy the wrong color? "N00B, SHOOT RED!" -> *shoots all players colored red for eternity*

**Comment by qreeves** [comment]
You are flooding the tracker with unconfirmed bugs.. freezur got it right,
too many people were fucking with these settings and then wondering why
everyone has stupid colours. KISS.
