### ISSUE TITLE
Performance issues with the new release

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#122]
I don't know if this is only on Windows, but using an AMD Radeon HD 7770, a Core 2 Duo, 4 GB RAM and Windows 7, I get a lot of performance issues. Some other players do, too. Surprisingly, enabling shaders helps a lot in improving performance, I get about 20 FPS more. But in some situations, it's still simply unplayable. 1.4 was performing correctly.

**Comment by shirepirate** [comment]
this is far too vague

**Comment by qreeves** [comment]
Make sure your game is (auto)updated to latest stable, there have been a
few performance patches since.

**Comment by acerspyro** [comment]
On this note, auto-updates do not seem to work anymore for some reason.
On my laptop in particular, the bat script often fails for some reason (and starts working again randomly), looking at it I see that it ends with "Syntax incorrect" or something similar.

 I often connect to my school's network, which blocks any port that isn't port 80. So it might break itself when I go to school, and fix itself when I come home and I am online. Just a guess.
