### ISSUE TITLE
loadout weapons in gauntlet race

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#123]
83e58a1 introduced weapons in gauntlet-race, which is a good idea.
However, loadout weapons are not in use, so this is spawn-weapons only (i.e. pistols).
Is this intended?

**Comment by qreeves** [comment]
No, not unless it is classic or basic.

**Comment by shirepirate** [comment]
wasn't the original intended behavior no weapons at all, just melee? what's the intended behavior of gauntlet race now?

**Comment by qreeves** [comment]
After a play test online, I realised that melee by itself is useless in gauntlet, so I enabled weapons.
