### ISSUE TITLE
variable menu: value box doesn't use enter key

### ISSUE THREAD

**Issue by freezurbern** [red-eclipse/base#125]
Usually, using the enter/return key will allow saving the contents of a text box, but this isn't the case for the variable menu. While trying to make a new value become active, the text box instead goes to a multi line with a miniature scroll bar.

---
*Current behavior:* Enter key doesn't make the variable change. Only clicking after editing the field does.

*Intended behavior:* Pressing enter or clicking after editing will cause the variable to change. The field will not spawn a scroll bar.

**Comment by qreeves** [comment]
Is this a recent issue, or was it in there before the release?

**Comment by shirepirate** [comment]
https://github.com/red-eclipse/base/commit/46627fc7588e85c0c624ccf35ab623715dda10b0
