### ISSUE TITLE
Game problems.

### ISSUE THREAD

**Issue by ghost** [red-eclipse/base#1302]
When I delete a lot of objects in the game, everything freezes, a black screen and Windows 10 continues to work, all programs have closed (I noticed this when Chrome is turned on with a video), but I can hear the sound of a game error. Rebooted the PC 3 times and passed, an image appeared. New PC, AMD Athlon 200GE. I use the built-in video card which is in the processor. What's wrong?

**Comment by dc-de** [comment]
@KostyaPay did my advise solve your problem?
In that case we would close this issue.
