### ISSUE TITLE
Plasma blinds self at fps over refresh rate

### ISSUE THREAD

**Issue by freezurbern** [red-eclipse/base#131]
I'd like to suggest a small tweak to the plasma1 particle. In 1.4.5, the plasma1 seems to 'start' or emanate further from the player. This was great! Now, in 1.5 the plasma particle covers a large portion of the screen for a VERY short amount of time. So short that it is difficult to capture on video.
![vlcsnap-2015-03-28-23h25m07s197](https://cloud.githubusercontent.com/assets/6363417/6884000/65df1d3a-d5a2-11e4-86c5-ce98996fe585.png)
The above image is a snapshot from a /movie .avi I made to try to capture what was going on.  I would suggest the variable and value I would like changed, except I'm not sure which one it is and thus I can't experiment.

My problem with this closer particle is that at high fps (over sixty, with vsync off) 1/3 or 2/3 of the screen are a bright plasma1 blue color. The screenshot above does not do the effect justice, as on my screen the entire 1/3 bottom portion goes aqua blue. This gives me a headache, and I'm not even epileptic or have any issues like that. However, I am unable to use the plasma for the majority of a game because of the flashing. For this reason, I would like to suggest the plasma particle start just a little bit further from the player.

---

To reproduce:
```
/maxfps {80-1000}
/vsync 0
* Fire plasma1
```

**Comment by qreeves** [comment]
This just needs a tweak to the plasmafade vars.

**Comment by freezurbern** [comment]
While we're paying attention to *fade vars, perhaps they could be explained and later added to usage.cfg?

**Comment by shirepirate** [comment]
if this has anything to do with particles from the weapon dealing damage at very close distances (1-2 meters) it should be left as it is. that was one of the most annoying things about plasma in 1.4

**Comment by bonifarz** [comment]
I think that was another variable, which was called proxdelay or pdelay in earlier versions. Fade seems to be just for particles.

**Comment by qreeves** [comment]
Yeah, as I mentioned on IRC, fade only influences the transparency of the projectile, whereas what we used to use for plasma was taper, which actually changes the size and strength of the projectile.

**Comment by shirepirate** [comment]
@freezurbern 
the fade vars are undocumented, but /plasmafade /plasmafadeat & /plasmafadecut are the vars you'd want to modify to more reasonable values. although they seem perfectly fine as they are to me, in 1st person.
