### ISSUE TITLE
RE crashs in edit mode (online)

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#133]
To reproduce:
1.  open two different RE with different config files (both were at: b4a64d827c14c5e6bef9e58687070047d4d20d1e (28, March 2015)
2. then i choose server with editing
3. both are now on one map
4. create with one person a door and a trigger
5. try to connect them with linking
6. other player get disconnectet with: illegal network message (got 80)

Maybe its not possible from one Computer or idk.
One time i try to debug and get this:

Message:
Program received signal SIGSEGV, Segmentation fault.
In USER32!SetMessageExtraInfo () (C:\Windows\syswow64\user32.dll)

and
--------------------------------------
```
#0 75A50C03	USER32!SetMessageExtraInfo() (C:\Windows\syswow64\user32.dll:??)
#1 013809C0	?? () (??:??)
#2 75A50B88	USER32!SetMessageExtraInfo() (C:\Windows\syswow64\user32.dll:??)
#3 013809C0	?? () (??:??)
#4 75A2929A	USER32!SendIMEMessageExW() (C:\Windows\syswow64\user32.dll:??)
#5 013809C0	?? () (??:??)
#6 5066346F	atioglxx!DrvGetProcAddress() (C:\Windows\SysWOW64\atioglxx.dll:??)
#7 506636C4	atioglxx!DrvGetProcAddress() (C:\Windows\SysWOW64\atioglxx.dll:??)
#8 5115EC97	atioglxx!DrvGetProcAddress() (C:\Windows\SysWOW64\atioglxx.dll:??)
#9 51163875	atioglxx!DrvGetProcAddress() (C:\Windows\SysWOW64\atioglxx.dll:??)
#10 5117304E	atioglxx!DrvGetProcAddress() (C:\Windows\SysWOW64\atioglxx.dll:??)
#11 506C5E5F	atioglxx!DrvGetProcAddress() (C:\Windows\SysWOW64\atioglxx.dll:??)
#12 50B57049	atioglxx!DrvGetProcAddress() (C:\Windows\SysWOW64\atioglxx.dll:??)
#13 50830C56	atioglxx!DrvGetProcAddress() (C:\Windows\SysWOW64\atioglxx.dll:??)
#14 004CC666	?? () (??:??)
```

NOTE: the reference to ```#1``` to ```#14``` was because, the text above wasnt a code block.

**Comment by qreeves** [comment]
The trace you provided just shows a crash caused by your video driver.

**Comment by exube** [comment]
Crash only happens when unlinking:
http://pastebin.com/y0eDzAyJ
*** Error in `/home/ecube/redeclipse/bin/amd64/redeclipse_linux': double free or corruption (out): 0x000000000b14fe00 ***
Fatal signal 6 (Aborted)
*** Error in `/home/ecube/redeclipse/bin/amd64/redeclipse_linux': free(): invalid next size (fast): 0x000000000b14fda0 ***

**Comment by IceflowRE** [comment]
Linking can rise the ping from the other clients up to 150 000. (displays the scoreboard ping)

**Comment by bonifarz** [comment]
A ping time of more than 400 hours? Sounds funny :laughing:

**Comment by shirepirate** [comment]
this is relevant:

![mwsnap0030 2015-07-27 16_12_34](https://cloud.githubusercontent.com/assets/2275004/8916567/8352290c-347a-11e5-95b2-2d42ec483a65.png)

i keep getting fatal signal 11 occasionally in edit mode
