### ISSUE TITLE
bot commands don't work if the bot host is on the other team

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#134]

**Comment by qreeves** [comment]
Please stop using the title as the full description. I expect properly formatted issues.

This is fixed upstream, but it requires the server you are on to be updated as well.

**Comment by JeffBobbo** [comment]
What format are you expecting? I don't see a way of structuring this without a vague or misleading title.

**Comment by qreeves** [comment]
I've told you about not providing a description before and I'm sick of repeating myself. Would you write a wiki article all in the header? No. It's a title, it doesn't have to describe everything.

Steps to reproduce ate also
