### ISSUE TITLE
defend-and-control decay

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#135]
decay doesn't have any defend points but this is a voteable map for defend-and-control.

tested on master server

**Comment by freezurbern** [comment]
confirmed, tested with offline client. Would DAC work well here? I think it'd be nice, but not sure about CTF. (if CTF was wanted, could do it at the same time)

**Comment by qreeves** [comment]
Decay is *huge*.

**Comment by shirepirate** [comment]
the map was not really intended for CTF, DAC or BB if i recall correctly, as it's structure isn't set up with team bases. if there's no control points it's probably an oversight. fixed.
