### ISSUE TITLE
Window not "responding" when map loads

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#136]
On Windows, when a map is loading and you click, Windows will say that the window is not answering when it isn't. It is also impossible to alt-tab while the map is loading, doing so shows the taskbar, but other windows are covered by Red Eclipse.

**Comment by shirepirate** [comment]
think that's a fairly common occurance in Windows when an application is at high CPU usage. 1.4.5 did the same thing. other games also do the same thing during loading times

**Comment by Croydon** [comment]
Yes, a lot of applications do this. However it's still bad practice to block the whole OS and force a specific behaviour on the user. Don't do this. At Inexor we will make the loading screens responsive too. https://github.com/inexor-game/code/issues/106

**Comment by freezurbern** [comment]
I do not experience this issue. My Red Eclipse (6d8e385988748df5679ab826991d590e8ca08bb4) loads smoothly and clicking does nothing. No Windows GUIs appear for me. No alt-tabbing is a valid complaint, however.

**Comment by qreeves** [comment]
The game already tries to keep the message queue alive, but this can only really be solved by multi threading. Won't fix.

**Comment by qreeves** [comment]
@Croydon Red Eclipse isn't your project, so don't tell us what to do. Shameless attempt at advertising your project.

**Comment by acerspyro** [comment]
Rekt.

**Comment by Croydon** [comment]
Sorry, if it's sounded like that. I didn't try to command you in any way. I just have a strong opinion at this point and I think it shouldn't be this way. It's of course totally up to you.

**Comment by qreeves** [comment]
The point is, nobody is going to bother to add thread support to the entire rendering and processing pipelines just for this issue.
