### ISSUE TITLE
Command that people under a specific rank can only play, but not edit

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#141]
I think and i dont found a command to lock the editing for ppl.
I mean not voting for editing! I mean in editing that e.g. "player" or "none" can play but not edit.

**Comment by freezurbern** [comment]
Another way of wording this would be

>/editmodelock 2 
>// Only players with this level or higher are allowed to enter edit mode. Players below this level may play as though the mode were deathmatch.

**Comment by bonifarz** [comment]
Wasn't *editlock* meant for exactly this? I realize it has a default of 4, though.

**Comment by freezurbern** [comment]
I can't figure out how to use */editlock* for this purpose.

**Comment by acerspyro** [comment]
A menu similar to file permissions in Windows would be nice to set rank-based permissions. If anyone's interested, I can make one.

**Comment by shirepirate** [comment]
/editlock is the value at which you can still spawn during editing when the lock mastermode is set

/spawneditlock is the value at which you can still spawn during editing when the lock mastermode is set, but not have the ability to edit anything

**Comment by bonifarz** [comment]
Thanks for the clue, @shirepirate, and thanks for the fixed descriptions in #143, @freezurbern.
