### ISSUE TITLE
New Catalyst drivers on Windows seems to be causing graphical glitches in Cube 2 games

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#149]
I need someone to confirm this theory as I could not figure out how to downgrade the drivers (I tried downloading them, but installing it installs everything but the driver), but it seems like the latest Catalyst drivers are causing stripeness from far away (You'll see what I mean) on both my laptop and my computers, with Radeon Mobility HD 5470 and Radeon HD 7770. I have friends who use older drivers and do not have the issue.

![20150410161140](https://cloud.githubusercontent.com/assets/4400999/7095914/49e29162-df83-11e4-9313-1d98f073c734.png)
![20150410161106](https://cloud.githubusercontent.com/assets/4400999/7095915/49e2d94c-df83-11e4-955f-889dfeb9187c.png)
![20150410161108](https://cloud.githubusercontent.com/assets/4400999/7095917/49e395ee-df83-11e4-9fb8-4b126b2d179c.png)
![20150410161136](https://cloud.githubusercontent.com/assets/4400999/7095916/49e335f4-df83-11e4-93ab-f3efc32a6144.png)

**Comment by shirepirate** [comment]
wouldn't one conclude that the problem is driver-based, then, and not an issue with the cube 2 engine? <.<
what's the purpose opening yet another uncomfirmed issue?

**Comment by acerspyro** [comment]
Where do you want me to post this stuff then

**Comment by freezurbern** [comment]
This used to happen to me on my old (now disassembled) Dell with Intel graphics. I can confirm this is a valid bug on my `ATI AMD Radeon HD 7400M Series` gfx card.

**Comment by IceflowRE** [comment]
Same here. AMD Radeon HD 5570 (Catalyst ver.: 14.501.1003-141120a-177998c)

**Comment by acerspyro** [comment]
Note, it still happens with the Beta drivers.

**Comment by qreeves** [comment]
Does this happen on v1.4, or is it just with v1.5? Is it only present with recent AMD Radeon drivers?

**Comment by acerspyro** [comment]
@qreeves It happens in all Cube 2 games, all the way back to Sauerbraten, so my guess would be that it also does it with v1.4.

**Comment by qreeves** [comment]
Then it is an overall Cube 2 rendering issue, we need to bring @lsalzman in to investigate.

**Comment by acerspyro** [comment]
*Takes a Prof. Farnsworth voice*
Good news, everyone!
I have found a fix: Set your Z-Buffer to 24, and all stripyness should disappear.

**Comment by freezurbern** [comment]
I can confirm, ```/depthbits 24``` fixed this issue on my AMD Radeon card.

**Comment by acerspyro** [comment]
Can anyone try this on their Intel chip? The very new (2013 AIO Dell Win 8.1 Touchscreen PCs) computers at my school had this problem. They had Intel HD somethings, never really checked.

**Comment by qreeves** [comment]
Can you take a look at this please eihrul?

**Comment by acerspyro** [comment]
@qreeves actually, @lsalzman gave me the answer via IRC, I forgot to credit him. :smile:

**Comment by qreeves** [comment]
Yeah, it's just he's the engine guy, so having this happen automatically would be up to him.

**Comment by qreeves** [comment]
See #264

**Comment by freezurbern** [comment]
Also occurs on Nvidia, for future reference.
