### ISSUE TITLE
mines dropped inside of solid geometry affect every player

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#152]
http://redeclipse.net/forum/viewtopic.php?f=7&t=654

of course, players shouldn't be able to get inside of solid geometry in the first place, but although mostly all these map glitches have been fixed, it is probably still possible at certain points.

so, the problem is a mine that explodes when left inside of geometry affects every player, killing them all instantly. apparently it's quite an old bug

**Comment by qreeves** [comment]
I've been trying to track down this one for over a year now, it's an insidious little sucker. If anyone can help it would be appreciated.

**Comment by acerspyro** [comment]
Is this still an issue in Master?

**Comment by acerspyro** [comment]
I can't reproduce on stable, can anyone else reproduce?

**Comment by shacknetisp** [comment]
I cannot reproduce this in master, even when forcing mines through ladder material (another issue).
