### ISSUE TITLE
can't see kill feed

### ISSUE THREAD

**Issue by KOOLKYLEKELLY** [red-eclipse/base#155]
i was playing offline practice and i accidentally pressed some random buttons then all my HUD disappeared. I managed to fix my HUD but then I couldn't see the kill feed (who killed who, chat between teams, alerts etc) How do i fix this. Plz answer as soon as possible.

**Comment by KOOLKYLEKELLY** [comment]
this means i can't see the event log (like 'team alpha won the round') and chat log (like 'KoolKyleKelly: Hi') and kill log (like 'KoolKyleKelly was riddled with holes by alan [39]'), alerts (like 'one minute remains')

**Comment by KOOLKYLEKELLY** [comment]
nevermind i found out how.
Delete the file "config.cfg" in your Red Eclipse save directory. The location of this directory depends on your Operating System:

Linux: ~/.redeclipse
Windows: [My] Documents\My Games\Red Eclipse
Mac: /Users/<name>/Library/Application Support/redeclipse

**Comment by bonifarz** [comment]
Okay, you resolved the issue as I was writing this.
You don't need to delete the entire config file, although that may seem the simplest solution.
With a text editor you can also try to remove or fix "suspect" lines.

Possibly you can also fix this issue via
* main menu
 * options
   * user interface
     * console tab 
      * misc tab (notice messages)

**Comment by qreeves** [comment]
In future, please use our forums, this issue tracker is for bugs and whatnot :P

**Comment by KOOLKYLEKELLY** [comment]
sorry, i couldn't find the forum Quinton.
And thanks for the alternate solution bonifarz.
