### ISSUE TITLE
Edit binds for M and 0 are missing

### ISSUE THREAD

**Issue by qreeves** [red-eclipse/base#16]
From: http://redeclipse.net/forum/viewtopic.php?f=9&t=485

The edit binds for M and 0 are missing, these toggled showmat and allfaces respectively. If the binds are permanently changed, then GUI must be updated to reflect this.

**Comment by IceflowRE** [comment]
allfaces are atm the key right of "0" (not the numpad 0) the "?" :D
Material should be rebind to M :D

**Comment by shirepirate** [comment]
i've made sure the current binds are made clear in the edit menu GUI.

outline toggle is bound to f9 i believe. all the binds seem fine unless there's a good reason they should be changed again.
