### ISSUE TITLE
Save demos to disk on server

### ISSUE THREAD

**Issue by freezurbern** [red-eclipse/base#162]
From: http://redeclipse.net/forum/viewtopic.php?f=4&t=145&p=1166

> I would really appreciate the option of saving demos to disk for the server, knowing full well that it could result in a lot of disk usage over time.
I think the only issue with not implementing this would be the effort it would take to code it. 
>-freezurbern

---

> Demo's are only stored in the server's memory, the idea to save them to disk is a valid request. 
-qreeves

---

More thought on this, perhaps a variable called `demosave` or `demodisk {0/1} // Save demos to disk on the server. NOTE: This can take up considerable disk space.` Perhaps the variable for limiting demos that can be retrieved could be modified to either how many are saved in memory and how many are saved to disk.

**Comment by qreeves** [comment]
Superceded by #163
