### ISSUE TITLE
Corrupt filename on map save (rare)

### ISSUE THREAD

**Issue by Jigoku** [red-eclipse/base#166]
Thought i lost my last save of a map i was editing, but noticed an odd filename when looking closer. The map had standard a-z:0-9 in the name, but decided to save itself as:
```
 Óf.mpz
```
The unreadable character is 15 in decimal, if that means anything.

Eg;
![screenshot6](https://cloud.githubusercontent.com/assets/1535179/7296613/09e3ffa2-e9b9-11e4-94ed-5e6f90edb201.png)

This happened once before when using svn 6550+ before 1.5 was released. Thought i'd notice this here in case others are getting it. On linux also.

**Comment by shacknetisp** [comment]
I do get this often, 6550 and 1.5, I've only noticed it after a /sendmap however.
Linux as well.

**Comment by Jigoku** [comment]
Yes, occured each time for me also with `/savemap` and no mapname supplied. Although, the map had been an existing one loaded via `/map <name>` (not a new map without an existing name).

**Comment by Jigoku** [comment]
Also occurs (very rarely) when a map automatically gets saved into the temp folder just before sending to other clients as they join. Specific to edit mode.

I don't have any other info than the screenshot below
![2015-08-13_00004](https://cloud.githubusercontent.com/assets/1535179/9262178/cd25327a-420a-11e5-995a-0ef9292727ef.jpg)

**Comment by qreeves** [comment]
These issues should be fixed in master.

**Comment by shirepirate** [comment]
i often get a map with associated files saved to my home folder, usually called tempfile. i never intentionally save it there. is is related to this?

**Comment by qreeves** [comment]
No, that's the temporary file used by the server side.
