### ISSUE TITLE
elara vars server appears above play.re

### ISSUE THREAD

**Issue by freezurbern** [red-eclipse/base#170]
elara.redeclipse.net appears above play.redeclipse.net in the server list (probably because of alphabetical?) which shouldn't happen. they should both be at the top, but play. should be the very first because it is 1.5.1 and elara is old stuff.

**Comment by bonifarz** [comment]
Agreed, the main server should be first. I guess once there are some clan servers for this setup, it will no longer be needed on redeclipse.net.

**Comment by shirepirate** [comment]
doesn't seem to be alphabetical as it is still listed first.

**Comment by qreeves** [comment]
This is just because it is hosted on the same IP address and is being (correctly) detected as an official server. I don't think it really matters how it gets sorted, the emulation server is well labeled.
