### ISSUE TITLE
cubescript "cases" "case" enhancement/ bug

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#171]
I saw yesterday that the commands cases and cases, have a big feature problem, they support only 12 conditions (Sauerbraten havent this problem).

For testing :
(you know what to do)
>
casecount = 0
casescount = ""
casecountmenu = [
	guistayopen [
		guilist [
			guibutton "-" [casecount = (- $casecount 1)]
			guistrut 1
			guitext $casecount
			guistrut 1
			guibutton "+" [casecount = (+ $casecount 1)]
			]
		guifield casescount 27 [] 0xFFFFFF [][][] [type a number until 20 like "one"]
		guistrut 1
		case $casecount 1 [
			guitext "1"
			] 2 [
				guitext "2"
			] 3 [
				guitext "3"
			] 4 [
				guitext "4"
			] 5 [
				guitext "5"
			] 6 [
				guitext "6"
			] 7 [
				guitext "7"
			] 8 [
				guitext "8"
			] 9 [
				guitext "9"
			] 10 [
				guitext "10"
			] 11 [
				guitext "11"
			] 12 [
				guitext "12"
			] 13 [
				guitext "13"
			] 14 [
				guitext "14"
			] 15 [
				guitext "16"
			] 17 [
				guitext "17"
			] 18 [
				guitext "18"
			] 19 [
				guitext "19"
			] 20 [
				guitext "20"
			] 21 [
				guitext "21"
			] 22 [
				guitext "22"
			]
		cases $casescount "one" [
				guitext "one"
			] "two" [
				guitext "two"
			] "three" [
				guitext "three"
			] "four" [
				guitext "four"
			] "five" [
				guitext "five"
			] "six" [
				guitext "six"
			] "seven" [
				guitext "seven"
			] "eight" [
				guitext "eight"
			] "nine" [
				guitext "nine"
			] "ten" [
				guitext "ten"
			] "eleven" [
				guitext "eleven"
			] "twelve" [
				guitext "twelve"
			] "thirteen" [
				guitext "thirteen"
			] "fourteen" [
				guitext "fourteen"
			] "fiveteen" [
				guitext "fiveteen"
			] "sixteen" [
				guitext "sixteen"
			] "seventeen" [
				guitext "seventeen"
			] "eightteen" [
				guitext "eightteen"
			] "nineteen" [
				guitext "nineteen"
			] "twenty" [
				guitext "twenty"
		]
	]
]
newgui test_gui [
	guitab  casetest
		[casecountmenu]
]
showgui test_gui 

The Problem is a little bit important for the options there are guirollover events which can not shown now, because of this limitation.

**Comment by qreeves** [comment]
This would be present in sauerbraten svn, as it is a limitation of the new cubescript compiler. It won't be fixed, and I will be coming up with a solution to the options rollover actions soon.

**Comment by bonifarz** [comment]
Hey Icy, your block of code nicely illustrates why indention is good practice :wink: 
Also, i think this will rarely be a practical limitation.

**Comment by IceflowRE** [comment]
tab havent work :(

(i still have it with tab :P  but github dont do it)

**Comment by qreeves** [comment]
You have to use markdown formatting for code { { { .. } } }

**Comment by bonifarz** [comment]
I know I am going off-topic in a closed issue, but anyway.

The tabs are also related to "good practice" or coding style, @IceflowRE 
Further reading: "tabs are evil" :wink: 
Most text editors can be configured to indent your code with white spaces as you press the tab-key.

Also, if you do the indention without tabs, you can just copy/paste the code and it will be shown correctly, without the need to use any tags like {{{ ... }}}

    case $casecount 1 [
        guitext "1"
    ] 2 [
        ...
    ...

This also works on the RE wiki.
