### ISSUE TITLE
Controls/keys menu (restore default binds)

### ISSUE THREAD

**Issue by Jigoku** [red-eclipse/base#173]
Have a guibutton to restore default keybinds in the controls options.

I've seen a few people now asking how to restore the defaults, currently it requires opening \<localconf\>/config.cfg and removing all of the lines starting with "BIND", which isn't too obvious. One player said they tried reinstalling the game (which doesn't remove the local config files) and was confused on how to reset their binds.

Maybe this could be useful.

**Comment by freezurbern** [comment]
I can't make the PR now, but it would be as simple as putting a button there that does this:
```exec config/setup.cfg```

**Comment by shirepirate** [comment]
yeah, the option should be there to remove everything using the uninstaller.
