### ISSUE TITLE
It's possible to lodge flags in vertical geometry

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#185]
Quite easy to reproduce reliably.

* Grab flag
* Parkour up a wall
* Drop the flag when you're relatively motionless against the wall.

The flag should stick there until it times out and resets.

**Comment by IceflowRE** [comment]
Only in third person possible or?

**Comment by JeffBobbo** [comment]
Works in 1p too. I didn't test it at the time as I've seen other people who died with flags and they got stuck.

**Comment by acz13** [comment]
Hmm, saw this too on some maps. I'll look into it

**Comment by qreeves** [comment]
It's a physics issue, projs::spherecheck is supposed to take care of this, but it seems like that isn't working in some cases still.

**Comment by qreeves** [comment]
I need some feedback on whether the recent `spherecheck` tweaks have solved this problem.

**Comment by JeffBobbo** [comment]
@qreeves Nope, sorry. Doesn't seem to be any difference.

**Comment by zaquest** [comment]
It seems that `collide` does not behave correctly in this situation. When this happens `collide` returns `false`, and flag doesn't bounce off geometry. Changing `cutoff` argument in `collide` calls inside `spherecheck` from `0` to `-0.01` for example makes `collide` return `true` and seems to behave correctly. However I'm not sure if it's the right way to fix it.

**Comment by qreeves** [comment]
This got me thinking about the physical size of the projectiles and how they could theoretically be zero at the start due to scaling. I've added a limit in ab935f2 to see if that is the problem.

**Comment by shirepirate** [comment]
409e7f0c8a9d5343aa53ea4c9d666b8cf7fabd71 did not fix the problem

**Comment by JeffBobbo** [comment]
This also effects weapons I've noticed (particularly the rocket in my experience).
