### ISSUE TITLE
clip bug

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#188]
Recent changes to deli exposed a bug with clip:

![clipbug](https://cloud.githubusercontent.com/assets/5425481/7903276/54bf81a8-07ce-11e5-82de-d02b512204ee.png)

This fence is fully clipped just like the other three fences (the one behind me on the screen shot and the other two on alpha side of the map).

Climbing up any of the other three fences leaves you falling to the ground, however you can easily climb up this fence on omega side and stand on top of it.

**Comment by shirepirate** [comment]
this isn't a bug, it simply wasn't clipped properly like the Alpha side and there's unclipped geometry on the top of the fence that the player is standing on.
