### ISSUE TITLE
Darken the row of dead players in the scoreboard

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#190]
As discussed here http://redeclipse.net/forum/viewtopic.php?f=4&t=716 , dead players' row on the scoreboard should be darkened to better allow us to see who's dead and who's alive at a glance.

**Comment by Calinou** [comment]
This would perhaps let us remove the side icons. Instead, colour the text of the player like this:

Dead = gray
Waiting = gray
Dominated by = flickers in orange shades
Dominating = flickers in green shades

**Comment by acerspyro** [comment]
The coloring is a good idea, but do not remove the side icons. Players will
have even less idea what it means.

**Comment by acerspyro** [comment]
The text should be darkened too.
