### ISSUE TITLE
There are some cases where bots should not be part of the game

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#191]
Cases like FFA Survivor with more than 3 people, Survivor with disbalanced teams, Team Duel (Bots are free points, not fair) and FFA with more than 4 people.

**Comment by IceflowRE** [comment]
Bots with a high skill level arent free points.
And i think bots should be there, they arent really hard to kill for good players, but they fill  the map and makes the (save) movement on a map harder.
Team duel doesnt need bots. but with the others iam not sure, if its good without.

**Comment by shirepirate** [comment]
don't open "issues" like this without discussing it on the forum first.

**Comment by bonifarz** [comment]
I'm not a friend of duel, but I agree that bots could be disabled per default for this mutator.
