### ISSUE TITLE
max connection limit variable for servers

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#209]
this would limit the amount of connections from the same IP address, to be used by master servers for unclogging the server list and individual servers for preventing abuse from more than 1-2 connections

possibly two variables would be needed if these are two separate issues

**Comment by Calinou** [comment]
Great, I can now shut down 2 of my servers. That sucks.

**Comment by freezurbern** [comment]
Perhaps instead of reverting the whole change, increase the default?
