### ISSUE TITLE
Inability to connect more than two servers to the master server.

### ISSUE THREAD

**Issue by shacknetisp** [red-eclipse/base#211]
With commit 1a678db (#209), there can be only two servers connected to the master from one IP.
This is greatly limiting, as I run unique servers: a parkour tutorial, a race server, an editing server, and my clan's server. This forces me to choose only two servers to host, however these four of my servers are often played on.

**Comment by freezurbern** [comment]
I would like to hear what others have to say on this. My opinion on it is that 2 is a good number (hey man used to be 1 in sauer before eihrul allowed changing the port). RE doesn't use much bandwidth, though it does have the rampant more-servers-than-players thing before #209.

**Comment by JeffBobbo** [comment]
@freezurbern #209 was done like 10 hours ago, there's the same number before as after.

Also, I can easily see why people would want more than two servers:
race
editing
normal
protocol break
custom vars

**Comment by Evropi** [comment]
I honestly don't see the point when there are almost no more than 3 servers ever actually in use. That's across the whole game.

**Comment by acz13** [comment]
Just because they're not in use at the same time does not change the fact that almost all servers don't allow race mode except for the race servers.

**Comment by acz13** [comment]
@freezurbern Have you ever considered that eihrul actually WANTED to have that many servers?

"Hey, back in the old days, we didn't have running water! So deal with it!"

**Comment by shirepirate** [comment]
i don't think "Inability to connect more than two servers to the master server" is a valid issue, as this variable was implemented on purpose whether the default should be changed or not.

personally i'm for the lower limit, as a measure of the game's quality control a small list of servers with some players on them compared to a huge list of servers with almost no players on them is more appealing. while the different purposes of servers is quite valid (i dabbled in hosting these kind of servers as well), there are already more than enough servers to serve all modes and this seems like a fair default limit to me. i always found it a little ridiculous from the beginning that we had to implement this search box to skim through some 50 odd empty servers, that should definitely not really need to be used before the next release. and then, it's also simply an IP address limitation and a different server could be hosted by the same party using another IP.

but @qreeves should have the final say on this default as it's really his hosted master server.

**Comment by qreeves** [comment]
It is also to prevent abuse, so I'm partial to keeping the default, but I'm willing to add an exemption list which can increase the limit on an as-needed basis. While we wouldn't want everyone hosting four servers, @shacknetisp is a moderator, and by extension, considered more trusted by the project.

I'll close this issue, please feel free to create another for an exemption list if you want to see that happen.
