### ISSUE TITLE
Not always told what picking up a weapon would replace

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#212]
In classic, when you've got a grenade or mine as your current weapon, you're not told what picking up a new weapon would replace.

**Comment by shirepirate** [comment]
it's always the last weapon you were wielding before explosives/spawn weapon.
i think this clarification is unnecessary and would only complicate and confuse

**Comment by JeffBobbo** [comment]
In the heat of battle or just generally running around (picking up and using mines/grenades) what you used last can easily slip you by. It's not a massive change which would complicate the system or confuse people, not any more than giving the impression that if you select a grenade you can pick up a third weapon (as you're not told it'd be swapped for something else).

**Comment by acerspyro** [comment]
I agree with Bobbo, clarification is required.

Also, when you say "complicate and confuse", there is NO possible way that showing a message saying "Picking up [weapicon]$weapon will replace [weapicon]$weapon." would complicate anything or confuse anyone. It's pretty clear.

**Comment by freezurbern** [comment]
I also agree that __*Picking up [weapicon]$weapon will replace [weapicon]$weapon.*__ would be a nice reminder. If the engine already knows which weapon (as shirepirate says, last) will be replaced, wouldn't it be nice to inform the user? I think that this change would improve consistency with the other replace notifications.
