### ISSUE TITLE
cannon -> blaster #214 

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#215]
@shirepirate I'm pretty pissed that you closed @freezurbern's pull request's comments.
We are a community, we get a say. And my brain literally exploded when you said that it was impolite to suggest. 

And yes, this is a valid issue: It's an issue about the community itself.

**Comment by freezurbern** [comment]
I don't think the community should decide everything, though I believe we should have the opportunity to suggest changes, as I have often done. Some have been implemented such as serverside demo saving, some have not such as renaming of a weapon to something I thought was more appropriate given the visuals.

**Comment by acerspyro** [comment]
@freezurbern I never said the community should decide everything, I said they should have a say in everything. Give their opinions, their feelings, the reasons they think like such.

**Comment by freezurbern** [comment]
Perhaps my english was flawed, I am agreeing with your point of discussion, @acerspyro. However, now I think the best course of action is for us to leave development alone for a while. Let people cool down for a few weeks.

**Comment by acerspyro** [comment]
@freezurbern I agree, cooling down is almost always the way to go.

**Comment by bonifarz** [comment]
Even if #214 is closed and comments are locked, i think it still works as a "suggestion". The proposed idea is there, and the devs are free to decide what will work best in the future. I don't see a problem. Peace :smiley:
