### ISSUE TITLE
Enlarging maps add cubes vertically

### ISSUE THREAD

**Issue by Honno** [red-eclipse/base#218]
If you use the /mapenlarge command, the map parameters gets bigger (obviously), and adds cubes to be in line with the default cube area that comes with a new map, but also cubes upwards as seen [here](http://i.imgur.com/zy0Vbxg.png). 

I suppose this is to show that the map gets bigger both horizontally and vertically, which is intuitive for new users. However, map creators likely want a flat plane to work with when enlarging the map so I recommend a new command such as /mapenlargeflat to accommodate for them.

**Comment by qreeves** [comment]
I've added the code to support this (`/mapenlarge 1` to use it). For it to work online will require a protocol change, so it only works offline for now.
