### ISSUE TITLE
W_N_SLIDE applies while you're in the air

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#220]
From a97749008faadfd070e38c25bfd41652d6688db9

This is pretty easy to reproduce, grab a flamer, parkour up a wall and try flamer2, you'll "glide" through the air and you're unaffected by gravity for half a second.

**Comment by qreeves** [comment]
This is actually not even possible, as `slidecoast` can't even take effect unless you're on something solid. It is just the fact that flamer2 stun settings cancel out gravity, and it has been this way since v1.5.0 was released.
```c++
bool slide = gameent::is(pl) && ((gameent *)pl)->sliding();
float c = pl->physstate >= PHYS_SLOPE || pl->onladder ? (slide ? PHYS(slidecoast) : PHYS(floorcoast))*coastscale(pl->feetpos(-1)) : PHYS(aircoast);
```

**Comment by JeffBobbo** [comment]
My apologies, then. flamer2's stun settings probably shouldn't cancel gravity, it's really weird.
