### ISSUE TITLE
Adding slide to stun causes a lot of weapons to inflict far too much hitpush

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#222]
Since this change, weapons push you around far too much.

Some suggested changes:
* Remove W_N_SLIDE from W_N_ADD (and perhaps the others, but they're not on weapons atm)
  * This returns the old behaviour all the weapons except sword, flamer2, plasma2 and zapper2 flak
* Reduce flamerhitpush2 and flamerflakhitpush2 to 33.0
 * This gives a maximum self-launch jump height of about 10m, which is roughly the same as a double jump
* Reduce flamerdelayattack2 to 800 from 1250
  * To compensate for the loss of power, although I haven't tested with actual players this seems to be a good value for pushing people around in the air/off the map
  * No damage reduction, imo the reduced push power is enough for the increased firing rate, I did play with reducing the damage but then flamer2 seemed far too weak.

**Comment by freezurbern** [comment]
Is this related to the fact that plasma1 now slides players around (a bit excessively IMO)?

**Comment by JeffBobbo** [comment]
Yes, this addresses that (first point), the rest is to fix flamer2 as its hilarious op now (you can push people on the ground about 20m)

**Comment by shirepirate** [comment]
i don't think we need to modify the weapon variables to compensate for this just yet, better to fix the issue that slide is only supposed to affect ground friction, and the fact that it's overexaggerated, both of which are already on the agenda from other open issues.

**Comment by JeffBobbo** [comment]
Clearly you haven't played this yet, because if you had you'd know that a smg2 shot is enough to push a player by 8m, that's about the same distance as an impulse slide.

**Comment by freezurbern** [comment]
Can we get an issue that speaks to adjustment of the sliding? All I see so far is that it applies while in the air.

**Comment by JeffBobbo** [comment]
@freezurbern This is to adjust it, there's two issues, one for the it being in air #220 and this, for it being too powerful on all the current weapons.
