### ISSUE TITLE
connecting to a server from offline with unsaved changes in edit mode fails

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#224]
If you start an offline game to edit a map then try joining a server to play without saving your changes, you're presented with a dialog with three options, save, don't save and abort. Regardless of which of the first two options you choose, connecting fails.

Only tested during master server being down, although I don't think that matters.

**Comment by freezurbern** [comment]
More info: The game fails to connect, after attempting a few times. Also, the game will save the map correctly if you choose to save.
