### ISSUE TITLE
Add hurt material

### ISSUE THREAD

**Issue by qreeves** [red-eclipse/base#23]
From: http://redeclipse.net/forum/viewtopic.php?f=9&t=8

Add a material like death material, which doesn't instantly kill players but puts them on fire/bleed/etc. For usage like when you run through a torch (e.g. map stone)?

**Comment by IceflowRE** [comment]
At this point i want to say maybe a material, where is no parcour possible (no kick, no wall run,... ) is usefull too. Like for the ends of maps maybe.

**Comment by qreeves** [comment]
> At this point i want to say maybe a material, where is no parcour possible (no kick, no wall run,... ) is usefull too. Like for the ends of maps maybe. Its like clip but without wall running there :D

@IceflowRE That's a separate issue. I have avoided adding this type of thing because there isn't a good consistent way to present this to the player. Being unable to parkour on something inexplicably is jarring.

**Comment by bonifarz** [comment]
That's pretty cool.
* Though, I got a few segfaults when loading a test map with hurt material. Not clear how to reproduce.
* Maybe you want this effect also enabled for ghost players, i.e. in race mode? Not sure.
* And: This is a must-have for the editing menus... I'll make sure the delay and damage can be set in the world menu, too.
