### ISSUE TITLE
Players getting automatically spectated mid-game

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#232]
http://redeclipse.net/forum/viewtopic.php?f=7&t=744

this can happen to be very annoying when mastermode is 2 (locked), but it is not unique to this and will happen when mastermode is set to 0. it is not unique to those with or without auth, can happen to an un-authed user up to a global admin.

cause unknown.

when it happens it usually happens immediately upon death, not after a longer period of time.

demos of this in action can be found in the forum thread.

**Comment by qreeves** [comment]
I still haven't been given a way to reproduce this problem or any information as to what might be causing it.

**Comment by zaquest** [comment]
Me and @shacknetisp tried to debug it. As far as I can tell the problems is caused by https://github.com/red-eclipse/base/blob/master/src/game/server.cpp#L5323 line. I can provide binary, core dump, modified source and demo on request.

**Comment by zaquest** [comment]
To reproduce mash mouse left (spawn) when you die (continue after death).

**Comment by shirepirate** [comment]
remember, this has also happened to authed users in an unlocked game. exact same symptom
