### ISSUE TITLE
seg fault after loading map offline

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#234]
Observed with 3f3216b709 on a win-64 client and also with some earlier commit from yesterday.
The game loads correctly when the specified map name is not found, e.g. when editing a new map, but crashes immediately after loading any existing map in any game mode.
Can someone reproduce this issue or maybe dump some debug info?

**Comment by freezurbern** [comment]
I'm having trouble reproducing it, can you tell some step by step instructions? I can provide debug binaries.

**Comment by bonifarz** [comment]
I just realize it works fine online. Step to reproduce is merely launching the client and starting any game offline. Will see if I can find out more.

**Comment by shacknetisp** [comment]
Confirmed on nix64:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000007251ae in server::getmap (ci=0x0) at game/server.cpp:2858
2858	            srvmsgft(ci->clientnum, CON_EVENT, "map is being requested, please wait..");
```
```
#0  0x00000000007251ae in server::getmap (ci=0x0) at game/server.cpp:2858
#1  0x00000000007378b1 in server::parsepacket (sender=0, chan=1, p=...)
    at game/server.cpp:5258
#2  0x0000000000588a54 in process (packet=0xf52a730, sender=0, chan=1)
    at engine/server.cpp:570
#3  0x0000000000588b39 in localclienttoserver (chan=1, packet=0xf52a730)
    at engine/server.cpp:578
#4  0x000000000042b251 in sendclientpacket (packet=0xf52a730, chan=1)
    at engine/client.cpp:220
#5  0x0000000000610bcb in client::sendmessages () at game/game.h:3388
#6  0x0000000000610c37 in client::c2sinfo (force=false) at game/game.h:3397
#7  0x000000000065fe8b in game::updateworld () at game/game.cpp:2803
#8  0x0000000000478e54 in main (argc=2, argv=0x7fffffffdf98)
    at engine/main.cpp:1058
```

**Comment by acerspyro** [comment]
I confirm on Win64, Windows 10, ATI Radeon HD 5470

**Comment by bonifarz** [comment]
Thanks! Such a small snippet of code saves quite some trouble :laughing:
