### ISSUE TITLE
Voice actions do not respect /saytextcolour

### ISSUE THREAD

**Issue by nyuszika7h** [red-eclipse/base#236]
If I do for example `/saytextcolour = "0x00FF80"`, messages sent from the voice compasses aren't colored.

**Comment by shirepirate** [comment]
please elaborate on this with the steps to either reproduce the issue you're bringing or a description of the change you'd like to see. "no description provided" is not acceptable

**Comment by nyuszika7h** [comment]
Sorry, I thought it's obvious, but I'll edit it.

**Comment by JeffBobbo** [comment]
@shirepirate I'm pretty sure it's clear that he means when you do "argh" or "sorry" from the voice compasses, they aren't coloured like your normal message are from /saytextcolour.

**Comment by freezurbern** [comment]
`say (format "%1%2" (getsaycolour) "argh!")` Might be a way of fixing it, but I can't get that to work in the compass. It works by pasting that into the console as `/say (format "%1%2" (getsaycolour) "argh!")` though.

**Comment by IceflowRE** [comment]
I have try this for a long long time ago heres the solution for compass colour?
```
compass "attack" [sayteam "^f[0xFF0000]attack!"]
compass "thanks!" [say "^f[0xFF0000]thanks!"]
```
or 
```
compass "thanks!" [say "^f["$playercolour"]thanks!"]
```

**Comment by bonifarz** [comment]
Nonononono :laughing: 

There are commands meant to be used with *saytextcolour*

    saytextcommand (getsaycolour)
    sayteamcommand (getsaycolour)

So I guess we can just put these in the compass menus.

**Comment by bonifarz** [comment]
Glad I could help :smiley:

**Comment by nyuszika7h** [comment]
Can confirm, it works now.
