### ISSUE TITLE
reverse player model

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#240]
as requested by a player called Last Camper, this would invert the position of the player model causing it to hold all weapons pointing toward the right rather than left (may be more natural for some left-handed players, and certainly makes somewhat of a difference in first person view).

whether this could be done without creating an inverted player model is unknown, but i said i would pass along the request.

i know in third person view there exists a variable called /thirdpersonside that can accomplish this, but to the best of my knowledge there is nothing similar for first person (also as far as i can tell this just changes where the view camera sits behind the player model)

**Comment by qreeves** [comment]
`thirdpersonside` doesn't change dominant hand, just the side the camera is on.

As there is no real engine support for this, duplicate player models would be needed with mirrored vertices, skeletons, and animations. A hefty undertaking.

**Comment by bonifarz** [comment]
Sounds tedious, even if the model has lateral symmetry and only the animations and weapon anchor (?) need to be recreated. If this is ever tackled, it could be reused to support dual pistol mechanics (which, however, is very challenging to get credible reload animations.)

**Comment by acerspyro** [comment]
Doing so would bring in a whole host of issues, it's not really worth it just to have a southpaw first-person model. Not only would it screw up the sword, which hits based on animation, but also other aiming bugs that we probably don't want to get into.

As mentioned, it would also require completely new first person model animations. It's just not worth the trouble for a left-handed player model.

Closing.
