### ISSUE TITLE
Some voice-overs don't play unless followed by other characters

### ISSUE THREAD

**Issue by freezurbern** [red-eclipse/base#241]
To reproduce: Type `argh` and nothing will sound. Next, type `argh!` or `argh.` or `arghhh`
Many of the voice overs behave like this, though a notable exception is `no problem` which works with just those two words.

I think this is inconsistent, and should be changed to allow someone to say for example `thanks` and have the voice over, instead of requiring more characters.

**Comment by bonifarz** [comment]
Could only reproduce with /say or /saycommand, but not with the default binds of chat keys. No clue why, though.

**Comment by swooboo** [comment]
My game works like @freezurbern described. It's also weird that if I say 'suck' there is no voice
over, but 'suck!' does have the same effect as 'suck it'. Also, 'suck it' is one more exception, just
like 'no problem' that works without '!'.
