### ISSUE TITLE
exctend the CS command guirolloveraction

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#254]
At the moment the guirolloveraction doesnt detected the action set in the guibody.
If its possible it would be a nice addition.

**Comment by bonifarz** [comment]
If i remember right, guibody has mouseover-actions buit-in, so why do you need guirolloveraction?

**Comment by qreeves** [comment]
@bonifarz is correct, `guibody` has an `onhover` parameter. The command isn't a widget like the others, it contains a set of widgets which it groups together as one. Plus, there's no `guirollovername` to give it, because it doesn't have a name to give it.

**Comment by IceflowRE** [comment]
I think you dont understand me, first i dont want the name i want the action.
Second the builtin onhover doesnt do what i need.

I will create a "fake" button, with the guibody command, because i want that the button looks like guitext (no transparency). But for adding a red glow when you hover over it, i need a specific identification for all, which is only the action behind. But this i cant detect, when i hover over one thing from the guibody content.

(Another way wouldbe a new parameter to turn the transparency of the guibuttons off) but at least detecting the action from them would be nice.

**Comment by bonifarz** [comment]
Let's figure out via PM or coop edit what exactly you want, icy. E.g. I once tried to make buttons that change colour when the mouse is hovering over them, and with some tricks, it worked. Not sure what you want, though. The onhover effect of images etc is disabled with *guinohitfx*. If you want to use something else than guibutton / guiimage, you can try guislice.

**Comment by qreeves** [comment]
You can detect it by setting your own alias in the onhover event.
```
mybodyrolloveraction = ""
guibody [ guitext "hi" ] [ myXalias ] [] [ mybodyrolloveraction = myXalias ]
cases $mybodyrolloveraction myXalias [
  echo "myXalias hovered"
] () [
  echo "nothing hovered"
]
```

**Comment by IceflowRE** [comment]
Thanks!
