### ISSUE TITLE
broken text colors 

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#256]
Just got 369f057d35 and the colors on the console, chat messages, weapon labels etc. seem broken, as if only the blue component of the hex colour values was used.

**Comment by qreeves** [comment]
Confirmed. Not sure what's going on there.

**Comment by shirepirate** [comment]
f402b650ea8c720d7a7b8c02f0d8a8ecbdaa3a43

**Comment by bonifarz** [comment]
Thanks for the quick bug fix!
