### ISSUE TITLE
survivor/duel > deathmatch mode-specific

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#260]
change survivor & duel into deathmatch mode-specific mutators
http://redeclipse.net/forum/viewtopic.php?f=4&t=708

**Comment by qreeves** [comment]
My only real question is, do we really want to remove functionality when it is present? I was actually thinking of revamping the ctf/bb survivor/duel modes to auto score a point when the opposing team is dead. I think that added dimension alone could be a reason for saving the idea.

**Comment by freezurbern** [comment]
>I was actually thinking of revamping the ctf/bb survivor/duel modes to auto score a point when the opposing team is dead. I think that added dimension alone could be a reason for saving the idea.

This sounds interesting, I wouldn't mind playtesting a few rounds to see how that goes.

**Comment by shirepirate** [comment]
i recall that idea being mentioned before but that would simply make it regular survivor (it's easier to kill all the other team with no regen than secure both flags at base, with balanced teams). so, is there a point to saving it then? it takes away from the primary objective of the mode anyway. seems like grasping at straws to simply save it when it would probably be better to just remove it (and more seem to agree with this, from the poll results).

**Comment by JeffBobbo** [comment]
I think it'd add an interesting dynamic to CTF/bb, where a single player could zerg the other team in hopes of a quick point, or work as a team to do the round in a more secure way.

However, I don't see much, if any, interest in playing su-ctf/bb that way.

**Comment by bonifarz** [comment]
I guess in bomber it is not necessarily easier to wipe a team than to score a goal.
I don't like survivor much, be it dm or other modes, but I agree this should be playtested to see if it is fun.

**Comment by shirepirate** [comment]
with deathmatch integrated into other survivor/duel modes this is no longer really needed, however it does take away from the purpose of extending the mutators to those mode at all.
