### ISSUE TITLE
player abovehead info disappear on death

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#261]
in this enhancement, abovehead icons for player models including names, team & event icons, weapons, status and everything else would disappear as soon as a player dies. this is to un-clutter aiming (especially with rifle zoom) and simplify game action (there is rarely a need to see dead players' info, it is only distracting).

**Comment by qreeves** [comment]
I'm actually against this idea. The name and death icon is an intentional "tombstone" so you know they're dead and can stop shooting them. I can add an option for this behaviour, but if the default is going to be the suggestion here, it'll need to be put to a vote.

**Comment by freezurbern** [comment]
I agree with Quin on this one, I like to know "oh snap he died over there" when looking at the kill feed.

**Comment by shirepirate** [comment]
i think an option for this behavior would be fine. personally i set the icons to be much larger than the default, but when a player dies i no longer care about that information, so you could see how it might be annoying to have it on dead bodies everywhere (especially for survivor). if this is added we could add all abovehead options to the actual options menu, too. something i've been meaning to do.
