### ISSUE TITLE
clearbans doesn't remove automatic teamkill bans

### ISSUE THREAD

**Issue by shacknetisp** [red-eclipse/base#262]
People banned for teamkills are still banned even after running /clearbans.

**Comment by freezurbern** [comment]
confirmed on 0d28505
To reproduce: teamkill until banned, use /clearbans, then try to reconnect.

**Comment by qreeves** [comment]
Y'know, even just copying the convo from IRC into the description field would go a long way toward helping me understand what's going on beyond that which is provided in the header. It may make sense to all of you, but I still need more information, whether you think I do or not.

**Comment by freezurbern** [comment]
Sorry, I thought if I provided how to reproduce that'd be enough to offset
the empty description.

**Comment by shacknetisp** [comment]
Sorry about that, the header looked good enough to me when I submitted it, but I see how it wouldn't be clear.

**Comment by qreeves** [comment]
:+1:
