### ISSUE TITLE
Peculiar shape of player

### ISSUE THREAD

**Issue by nyqvist** [red-eclipse/base#266]
I am using Debian 8 (Jessie).

Background
I first installed redeclipse from the Debian stable repo (version 1.4-6). When I wanted to play online I got a message that I should upgrade to the latest version of redeclipse. I uninstalled the first version and downloaded the latest (1.5.2) from the main website.

Issue
When I start redeclipse can see that my player looks very strange:
![redeclipse_main_2015-07-11](https://cloud.githubusercontent.com/assets/1544300/8634982/40cbc0aa-2810-11e5-87c4-99b8f3e08a1f.png)

This is also the case when I play.

**Comment by shacknetisp** [comment]
Run the command: /gpuskel 0

**Comment by nyqvist** [comment]
From where should I run this command?

**Comment by shacknetisp** [comment]
From the console (`/`)

**Comment by nyqvist** [comment]
Thanks, that worked.
