### ISSUE TITLE
bugged world textures

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#272]
i'm seeing bugged world textures like lava, have tried different texture settings but doesn't resolve the issue. happens in every map. happens in the latest stable version with a clean home folder.

![20150713155416](https://cloud.githubusercontent.com/assets/2275004/8659549/b2c72086-2979-11e5-8fb2-6c79e0ad3615.png)

there's nothing in the log to suggest something is amiss, if there's more info i can provide just let me know

![mwsnap0031 2015-07-13 16_13_23](https://cloud.githubusercontent.com/assets/2275004/8659615/22b9c448-297a-11e5-9d37-2f0d715fde7a.png)
![mwsnap0032 2015-07-13 16_13_29](https://cloud.githubusercontent.com/assets/2275004/8659618/270b666e-297a-11e5-90e4-e6565e5b1e2f.png)

**Comment by bonifarz** [comment]
At least, I don't see this in the current development version.

**Comment by freezurbern** [comment]
This doesn't happen on my `Nvidia GeForce 760` or my `Radeon HD 7400M`. Both `Windows 7, 64bit`.

**Comment by shirepirate** [comment]
this issue was caused by an outdated GPU driver, fixed in new DLLs
