### ISSUE TITLE
projectiles and some particles do not appear

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#273]
the projectiles from gun shots like shotgun's ball of flak, smg shots, even the laser from mine2 do not appear at all.

i took a video of this in action:
https://volafile.io/r/fxy325

it happens with a clean home folder on the latest stable version. if there's more info i can provide let me know.

![mwsnap0031 2015-07-13 16_13_23](https://cloud.githubusercontent.com/assets/2275004/8659743/c916893e-297a-11e5-86c5-9fa7f2d2754f.png)
![mwsnap0032 2015-07-13 16_13_29](https://cloud.githubusercontent.com/assets/2275004/8659746/cc504072-297a-11e5-800a-eb95fd0c3c8b.png)

**Comment by freezurbern** [comment]
This doesn't happen on my `Nvidia GeForce 760` or my `Radeon HD 7400M`. Both `Windows 7, 64bit`.

**Comment by shirepirate** [comment]
this issue was caused by an outdated GPU driver, fixed in new DLLs
