### ISSUE TITLE
abovehead info does not render properly

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#274]
abovehead info will not display properly anymore, instead some random black lines are above player models' heads. no names, team icons, nothing. happens in the latest stable version with a clean home folder.

![20150713162433](https://cloud.githubusercontent.com/assets/2275004/8659908/cd89af18-297b-11e5-9671-ab2ba14b07b1.png)

if there's more info i can provide on this let me know, i'm guessing it has something to do with the recent changes to abovehead vars on death but could be wrong.

**Comment by freezurbern** [comment]
This doesn't happen on my `Nvidia GeForce 760` or my `Radeon HD 7400M`. Both `Windows 7, 64bit`.

**Comment by shirepirate** [comment]
this issue was caused by an outdated GPU driver, fixed in new DLLs
