### ISSUE TITLE
editing menu overhaul

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#281]
Forum topic with preview images: http://redeclipse.net/forum/viewtopic.php?f=4&t=770

Summary: 
  :white_check_mark: stable branch (automatic updates)
  :white_large_square: master branch (devel version)
  :grey_question: ongoing or open for discussion

See also: https://github.com/red-eclipse/community/blob/master/bonifarz/menubackports.cfg

:white_check_mark: improve controls menu, so it serves as a key reference #255 
:white_check_mark: vars menu filters, so all world vars can be looked up #239
:white_check_mark: add new menus from forums, remove clearly unused ones
:white_check_mark: set up the glue and colour picker to start work on new edit menus
:white_check_mark: recreate v-tex menu using colour picker for vcol, glow, spec
:white_check_mark: button and checkbox macros with built-in display of edit bind, console tool-tip and console alt-action
:white_check_mark: split and recreate the editing main menu
:white_check_mark: split and recreate the editing environment menu
:white_check_mark: merge lighting and environment menus (to be expanded)
:white_check_mark: set up new editing main menu and compass
:white_check_mark: add newent icons in ents menu (work in progress)
:white_check_mark: create and merge pull request so the stuff can be tested #281
:white_check_mark: editbind E in setup.cfg, make it show and close the compass
:white_check_mark: revise editing controls in game options
:white_large_square: new tab in map info: waypoints (with file check) and routes (with counting)
:white_large_square: new tab in geometry menu: prefabs (with scrollable file list and gridsize info)
:white_large_square: replace util tab in texture menu with recreated blendmap menu 
:white_large_square: second PR for testing #292 
:white_large_square: tweak ents menu, fix sub-selection button, simpler entloop code
:white_large_square: scrollable list of sounds, enhanced mapmodel list, light presets with colour picker
:white_large_square: remove unused menus (newcolour, quick edit, teleport...)
:white_large_square: simple music menu (not only for editing)
:white_large_square: third PR for testing #294 
:white_large_square: new tabs in materials menu for properties and obits
:white_large_square: grass tab in world menu
:white_large_square: enhance sky tab in world menu with a large array of vars
:white_large_square: new submenus for picking skybox, cloudbox, cloudlayer, envlayer
:white_large_square: split geometry menu, new texturing tab 
:white_large_square: add glass2...4 to tab 2 of materials menu, a note about glass in tab 1
:white_large_square: fourth PR for testing #298
:white_large_square: explain coop edit restrictions (#302)
:white_large_square: improve attribute labels for editing particles (#280, #305)
:white_large_square: contextual pick buttons/menus for entity colours and particle shapes (#311)
:white_large_square: a tab for editlock in the editoptions menu (#317)
:white_large_square: overhaul of the ents menus, better selection and replacement #324 
:white_large_square: revamp menus to pick mapmodels and cloud/envlayers (#343)
:white_large_square: improve world menu (fogdome, grass previews, reset sky)  #354 
:white_large_square: various improvements, including entgroupedit, minimap, point aliases #356
:white_large_square: more tweaks (lighting options, grass, grayed out buttons) #359 
:white_large_square: enhance editoptions and map info menus #362 
:white_large_square:  improve colour/shader/palette options  #368 
:white_large_square: brand new previews for prefabs and new mapmodel previews, too #370
:white_large_square: remove support for maps/temp, add filter for downloaded maps  #407
:grey_question: support for palettes as shader options? Probably more confusing than useful
:grey_question: happy bug fixing
:grey_question: corrections for language/wording are welcome
:grey_question: a new serverprivs menu? Is *serveropen* needed at all these days?
:grey_question: suggestions for other functionality are welcome

**Original description:**
There's many, many ~~small~~ things in the editing menu that could be improved, added or removed.
I'd like to see what I can do about this and started some work-in-progress.
I have no clue how far I will get until release 1.5.3 is ready.

**Comment by qreeves** [comment]
Doesn't matter, the updater is working better now, so it can be patched in later.

I'll designate you lead for this, then everyone can coordinate with you if they have anything to add.

**Comment by bonifarz** [comment]
Okay, I hope it will work fine, because I am not sure where this will get...
Feedback is always welcome, be it on github or on the forums (I will list the relevant links in the commits).
If someone has a suggestion for my "edit-menu-wip" fork, they can make a pull request there, so their contribution will be listed properly once I make a pull request for the entire fork.

**Comment by shirepirate** [comment]
from irc:

<Dziq_PL> :) guys. Its possible for you devs to add a little info in texture browser contains some info about texture channels ? Like if texture has glow, bump, spec channels used ?

would be good to add as a tooltip in the texture menu perhaps

**Comment by bonifarz** [comment]
I won't touch the texgui menu for now, as it goes beyond cubescript (hardcoded).
On a related note, I remember there was once a feature request for getting texture modifier informations from a texture slot (vscale, vshaderparam etc.), but I don't see a ticket/issue. Could be useful for the menus as well. 
Another feature that could be useful here: Ent icons #51, but the placeholder i picked seem okay for now.

**Comment by qreeves** [comment]
> I won't touch the texgui menu for now, as it goes beyond cubescript (hardcoded).

Which will need a separate issue. Would probably be good if it was moved to CubeScript.

**Comment by bonifarz** [comment]
The latest commit on #298 should be a nice update.
There's a ton of vars for the sky environment, and I think I succeeded in arranging them nicely. Also, there's a significant improvement to the way you can pick skyboxes, envlayers and clouds, and a fix on the OK button of the colour picker. So, it would be nice to get this one merged.

**Comment by bonifarz** [comment]
More than a month, 30 commits and 1800 lines later, there are still ideas to improve these menus. But the progress so far looks okay, doesn't it?

**Comment by shirepirate** [comment]
will close this for now, as the improvements are mostly finished. any further feedback or ideas can be directed to @bonifarz or myself

**Comment by bonifarz** [comment]
I would have liked to close this myself with the rewarding feeling of having accomplished the project, but I guess this has been open for **way too long** :wink: 
Just kidding - I can polish the menus any time, and there's not really a need for an open issue.

I take it on a positive note that you consider this mostly finished, and that you don't see any critical issues atm. And as usual, further feedback is appreciated!
