### ISSUE TITLE
skip items entirely, skiprocket

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#285]
in this enhancement, skipgrenade & skipmine would both disable the ability to even pickup a grenade or mine. not only would the on-screen dialogue not appear, but pressing action would not add them to inventory.

also, a skiprocket following the same style would be nice

**Comment by JeffBobbo** [comment]
This is unclear, but I'm assuming you mean in similar fashion to skippistol for cycling weapon purposes?

Don't forget to make kamikaze ignore this if so. :P

**Comment by shirepirate** [comment]
um, no, skipgrenade & skipmine already have that functionality. this would go a step further and disable the ability for them to be picked up at all. kamikaze has no bearing.

**Comment by JeffBobbo** [comment]
So what happens if I play kamikaze with skipgrenade and skipmine on?

**Comment by shirepirate** [comment]
why would kamikaze be in effect when it's not added to your inventory? if you mean kaboom it should probably overrule all skip settings, yes.

**Comment by JeffBobbo** [comment]
... I meant kaboom... Apologies. XD
