### ISSUE TITLE
floody colour sliders in vars menu

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#287]
I realize the colour sliders I added to the vars menu tend to flood the console.

For the editing menu overhaul #281 I just made up a new colour menu, which I'd like to use for the editing and vars menus. So once that project is ready to merge, it will fix this issue as well. Here's a preview:

![pickcolour](https://cloud.githubusercontent.com/assets/10864175/8749165/04deb6a8-2ca0-11e5-8f1b-5e33b5d2d932.jpg)

**Comment by shirepirate** [comment]
i guess you mean the changes are flooded when playing online? didn't seem to be a problem offline. if so just adding a confirm button would fix it.

**Comment by bonifarz** [comment]
Exactly, dragging the slider can flood the console (also offline), as it does not use another var. The confirm button is what you see at the top right of the menu i just pushed on the wip branch.

**Comment by bonifarz** [comment]
fixed via #288
