### ISSUE TITLE
Leave channel when closing the IRC client window.

### ISSUE THREAD

**Issue by shacknetisp** [red-eclipse/base#291]
Currently the IRC client remains connected and joined while the game is running, even when the window is closed, which can be confusing since there is no notice when this happens. A solution would be to have the client leave the channel when it is closed.

**Comment by freezurbern** [comment]
This would mostly help those in the IRC channel providing support, so they know when someone has the GUI open or has closed it.

**Comment by shirepirate** [comment]
why would this be helpful? if someone has come to seek help and closes the irc window, they won't see whatever was said when they return. that's why it was bound globally to "I" for quick access anywhere.

you can't switch quickly between spectating a game and lobby chat if it leaves the channel each time. can't see any pros to this.

**Comment by freezurbern** [comment]
So the chat doesn't stay in the window?? I thought it would just stay in that field until they got back to it..

**Comment by shirepirate** [comment]
i don't think it does, but even if it does it would be overwritten by all the stuff that is initially output when you first join a channel like user list and motd

**Comment by qreeves** [comment]
I could maybe set the client as away when they close the UI.

**Comment by shirepirate** [comment]
>I could maybe set the client as away when they close the UI

other than the potential spaminess i don't see a problem there. but it still doesn't seem necessary to do anything at all.

**Comment by shacknetisp** [comment]
How would that be spammy?

For people in IRC, seeing when someone has closed their GUI would be convenient, as they could stop trying to talk to them when it won't be read.

**Comment by qreeves** [comment]
I'm talking about the proper IRC `AWAY` command, which is very different to all those scripts which announce it to everyone in every channel (like anyone cares).

**Comment by shirepirate** [comment]
sounds good then
