### ISSUE TITLE
If not moving and holding the Walk key, player is more accurate

### ISSUE THREAD

**Issue by Calinou** [red-eclipse/base#293]
If you do not move and hold the Walk key, you will be more accurate than if you don't move and don't hold the Walk key.

**Comment by shacknetisp** [comment]
Do you mean spread is less when the Walk key is pressed?

**Comment by Calinou** [comment]
> Do you mean spread is less when the Walk key is pressed?

Yes, **even if you are not moving, which is not what's expected**.

It'd be understandable if player was more accurate when crouching and not moving, but walking and not moving does not cause any stance change.

**Comment by bonifarz** [comment]
Yep, could reproduce this observation. 
Also, crouching does **not** reduce spread, but only negate kickpush. Though, the two modifiers can be combined  for a super slow walk mode...
