### ISSUE TITLE
Cubescript "guibody" doesnt accept a empty guibutton name in it

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#296]
```
newgui test [
    guibody [
        guibutton "" [echo "clicked"] [] $editingtex
    ]
]
showgui test
```

guibody doesnt accept an empty guibtton name.

**Comment by bonifarz** [comment]
well, there's no clickable or visible content in this example anyway, so what do you expect?!

**Comment by IceflowRE** [comment]
Theres the icon.

**Comment by bonifarz** [comment]
right... i remember guibodies require a click action on themselves, so maybe this is the problem you see?

**Comment by IceflowRE** [comment]
hm, thats maybe possible, it ignores then any other click actions.

**Comment by IceflowRE** [comment]
ok, the action should be in the guibody thing, but theres one other thing with an empty name the image has no glow when rollover.

**Comment by qreeves** [comment]
Use `guiimage`.

**Comment by bonifarz** [comment]
Maybe the forums are the better place for this type of issues :smiley:
