### ISSUE TITLE
changing flares size in light/sunlight entities

### ISSUE THREAD

**Issue by Dziq84** [red-eclipse/base#313]
I think that should be very usefull for making nice sun blind effect, also for normal lights. Now flares are very big even when light has very small radius. So it would be nice to add new option in these actors to allow mappers to change that flare size :)    Hope its possible and devs think about that :)   

Cheers

**Comment by shirepirate** [comment]
this was added before you posted this issue:
aaeb88e949256faeae6768653caeb1612147ebe7

**Comment by qreeves** [comment]
Yeah I told him to make this issue, then ended up remembering to do it later in the day. The new attributes are only in *master* at the moment, I will push to *stable* once I am sure the new rendering code is working properly.
