### ISSUE TITLE
Tear in skybox

### ISSUE THREAD

**Issue by shacknetisp** [red-eclipse/base#316]
![20150729002344](https://cloud.githubusercontent.com/assets/2333388/8950018/abfea6d6-3589-11e5-959f-c39a9ac84816.png)

So far I've only seen it on longestyard.

OpenGL Information:
```
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD KAVERI
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.5.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 10.5.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 10.5.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```

**Comment by qreeves** [comment]
Master or stable?

**Comment by qreeves** [comment]
Actually looks like a HOM glitch.

**Comment by shacknetisp** [comment]
Master only.

**Comment by qreeves** [comment]
This one still happening?

**Comment by shacknetisp** [comment]
Yes, I can reproduce it with the latest master on longestyard.

**Comment by shirepirate** [comment]
pretty sure this is relevant: when editing a brand new map, the default texture will often tear into the black skybox as you move the camera around. seems like the same glitch

**Comment by bonifarz** [comment]
Confirming @shirepirate's comment.

**Comment by shacknetisp** [comment]
I did some experiments and found that this glitch doesn't happen on longestyard if I change the skybox, and it does happen on canals if I change the skybox to skyboxes/stars. So it looks like skyboxes/stars is the problem here.

**Comment by bonifarz** [comment]
I think *stars* is one of the few skyboxes that support alpha/blending, so if you don't use it as cloudbox with a second skybox, you're back to a skybgcolour based component, similar to the one on a blank map.

**Comment by qreeves** [comment]
Sounds like an alpha/depth issue then.

**Comment by shirepirate** [comment]
![redeclipse_160407_2143157](https://cloud.githubusercontent.com/assets/2275004/14371897/f2ac7c00-fd09-11e5-9725-999b270288ec.jpg)

in my screenshot fun i've seen this happen on quite a few maps now. it'll need to be fixed before we can push a release (guessing @lsalzman might have an idea of why this happened?)

**Comment by qreeves** [comment]
OK, I've narrowed it down to this piece of code in drawskybox():
```
    if((!glaring || skybgglare) && blendsky)
    {
        SETSHADER(skyfog);
        notextureshader->set();

        matrix4 skymatrix = cammatrix, skyprojmatrix;
        skymatrix.settranslation(0, 0, 0);
        skyprojmatrix.mul(projmatrix, skymatrix);
        LOCALPARAM(skymatrix, skyprojmatrix);

        gle::color(vec::hexcolor(skybgcolour));
        drawenvboxbg(farplane/2, skyclip, topclip, yawskyfaces(renderedskyfaces, yawsky, spinsky));
    }
```
Commenting this out stops it from being weird in that location in the maps, but makes it weird in other ways (bleeding hall of mirrors). I'm guessing it is another matrix issue?

**Comment by pocak100** [comment]
Visually, it looks like some aspect of the skybox is being clipped by the far plane. Indeed, enabling depth clamping for `drawenvboxbg` hides the problem:
```
        glEnable(GL_DEPTH_CLAMP);
        drawenvboxbg(farplane/2, skyclip, topclip, yawskyfaces(renderedskyfaces, yawsky, spinsky));
        glDisable(GL_DEPTH_CLAMP);
```
There is also a HOM glitch in the sky if the camera leaves the map bounds, not related to the far plane.

**Comment by graphitemaster** [comment]
I'm on NV and I have this problem too 
![20160507180329](https://cloud.githubusercontent.com/assets/343195/15166732/aa7c7d2c-16ef-11e6-87e3-985306c16d77.png)

**Comment by bonifarz** [comment]
With 620e0a9 the far plane hack is reverted and the artifacts are indeed visible again, as seen in above screenshots. So, a proper fix would be cool :smiley:

**Comment by bonifarz** [comment]
Very nice! I guess  #421 (editing arrows/wires) will be a weird color buffer thing, too?

**Comment by bonifarz** [comment]
Strange, I get this (screenshots above) again in today's update for stable, but not on master.

**Comment by qreeves** [comment]
I removed my patch and updated stable before eihrul fixed this. Next update breaks protocol, will push next week. Nice to know it is fixed.
