### ISSUE TITLE
guifield / guieditor scrollbar issue

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#326]
If you are using a guifield with a fixed height (arg6), as soon as there are more lines to display than this height and a scrollbar is drawn, the content is no longer shown. Same when using a guieditor (arg3) to edit a new file. When loading an existing file the scrollbar seems to work okay, though.
Fixing this will be useful to get a reasonable layout in the vars menu when displaying long strings/list/aliases, e.g. botmalenames.

**Comment by bonifarz** [comment]
Could this be related to @swooboo's patches, #244?
I remember there was similar issue #78 related to an empty first line,  which was fixed via 9b99507. I think after that fix the problem described here did not occur yet.

**Comment by bonifarz** [comment]
Probably related: A guifield with negative width argument expands downwards before the current size is full. Seems the textwidth check is off? 

Also, I am not sure any more if the problem with the slider did not occur on 9b99507. The client I use as "stable" version has it, too, but maybe something went wrong with the updater.

**Comment by bonifarz** [comment]
This test case may be interesting 


    x = "this sucks"
    y = "this-sucks"
    loop i 4 [
        append x $x
        append y $y
    ]
    
    newgui test [
        guilist [
            guitext (textwidth $x)
            guispring
            guitext (textwidth $y)
        ]
        guilist [
            guifield x -10 
            guifield y -10 
        ]
    ]
    showgui test

**Comment by bonifarz** [comment]
I gladly confirm the wrap on guitext works fine now, yay.

However, I still get broken guifields as soon as they use the built-in slider.

**Comment by qreeves** [comment]
You should have included that in the test case :stuck_out_tongue:

**Comment by bonifarz** [comment]
Worse, I guess I kind of mixed up to distinct issues in this ticket.

**Comment by bonifarz** [comment]
Yeah, textwrap is fine. 
Shall we open another issue for the field/slider problem?
Test case:
```
x = "gone when the scrollbar pops up"
newgui test [guifield x -10 [] -1 0 "" 3 ]
showgui test
```
