### ISSUE TITLE
RE crashs

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#34]
http://redeclipse.net/forum/viewtopic.php?f=4&t=520&p=4787&hilit=big+list#p4787

black screen (RE crashs)
On my map fatalerror (https://drive.google.com/file/d/0B__JdfXlvXlxb2MtT25GMkJCck0/view?usp=sharing) (load it with edit), spawn and directly! (in the air) after spawn do one! shot with the pistol (otherwise do nothing dont move or jump) then at one point u get (every time) a black screen and the speed increases like lightspeed :D and then Fatalerror (Segmentation Violation), RE crashs. The special with this is, its possible without var change! (MaxPayne show me to do the same with var changes but this is without possible).

**Comment by freezurbern** [comment]
I was unable to reproduce this on Windows 7 x64 with git ce2505b1ceb0cd295c38928d59aace76fecf4361
