### ISSUE TITLE
Client doesn't show priv icon after voting.

### ISSUE THREAD

**Issue by shacknetisp** [red-eclipse/base#342]
To reproduce, join any server (master branch) and vote something else. You will still have all permissions, but your priv icon will not show in your client.

**Comment by qreeves** [comment]
I spent the better part of the last hour trying to find this one. The irony is, you introduced this bug [here](https://github.com/red-eclipse/base/pull/172/files#diff-255a3589e66b0c2c340777ff95a124b3R2650), haha. You forgot to add a `break` and I didn't notice it when merging, whoops.
