### ISSUE TITLE
bomberball issue

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#346]
when you throw the bomberball, you aren't able to pick it up again until it respawns (or until a long timer runs out, i imagine). not intended behavior, makes FFA Hold Bomberball near impossible to win. to reproduce play any bomberball match in latest stable and throw the ball

**Comment by qreeves** [comment]
`bomberpickupdelay` = 15 seconds, nothing else influences it in this mode (the code isn't shared with CTF, so it isn't anything from there).
