### ISSUE TITLE
check weapon descriptions

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#348]
I think it would be nice if someone who is familiar with the latest balance teaks to weapon rules could check the weapon descriptions: 
https://github.com/red-eclipse/base/blob/master/src/game/weapons.h#L122-L146
Maybe @shirepirate could have a look at these? They are used as tooltips in the loadout menu (e.g. #347) and I consider writing a new weapons page for the help menus that would use these as well.

**Comment by shirepirate** [comment]
these were added quite recently, is there a specific one you see that needs to be updated? if so just create a PR

**Comment by bonifarz** [comment]
As far as i remember, the slow/shock effect on the zapper's primary, but I don't know what other descriptions could be improved. Just opened the issue so this does not get forgotten.

**Comment by bonifarz** [comment]
Thanks for the texts you added, @shirepirate. I'll revise the weapon help layout later.
