### ISSUE TITLE
Respawn on new edit maps broken

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#35]
Respawn doesnt work on new edit maps 

When u fall down from the map u cant suicide or respawn with spec and spawn new and if you want to go up again with flying it can happens that u dont find the map back :D (it doesnt work until there is a playerstart)

**Comment by freezurbern** [comment]
I can confirm, client just waits with "Ready to respawn"
This was happening a while back too, not sure if it ever got fixed in edit like it was in fighting modes.
