### ISSUE TITLE
smudged border of guibackground

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#350]
When drawing boxes or bars using *guibackground*, the border looks sort of smudged.
My best guess is that after the *UI voodoo* tweaks 1647282fb2e7252a3be3bbd992938dfc147c3fa3, the filling colour does slightly overlap with the border/frame. Or maybe the *guiskinborder* texture is scaled and deformed, depending on the field's shape? 

A good example is the work-in-progress for a weapon help menu. Here are screenshots using stable and master:
![snip stable](https://cloud.githubusercontent.com/assets/10864175/9155376/2ddc9e30-3eb6-11e5-8c3e-3196c7b7ed99.jpg)
![snip master](https://cloud.githubusercontent.com/assets/10864175/9155377/2f79006c-3eb6-11e5-86f1-6bf30c6203be.jpg)

            looplist i $weapstats [
                guistrut 0.1
                guilist [
                    guibackground $[@[weapsel]colour] 0.8 0xffffff 1.0 1
                    guistrut (at $[weap@i] $weapseli1)  // width
                    guistrut 0.9 1 // height
                ]
                guistrut 50 1 
                guistrut 0.1
                guilist [
                    guibackground $[@[weapsel]colour] 0.5 0xffffff 1.0 1
                    guistrut (at $[weap@i] $weapseli2)  // width
                    guistrut 0.9 1 // height
                ]
                guistrut 0.5
            ]

**Comment by qreeves** [comment]
It's not an overlap, it comes from rendering the 256px GUI images at smaller sizes. This is the reason the sliders were made bigger.

**Comment by bonifarz** [comment]
All right, that explains why the shape of the corners changes when the field's aspect ratio varies.
But why is the border tex scaled, in contrast to earlier versions (stable).
Is that because the border used to be added around the field's size, and now the size is meant to include the border? A bit strange. And sort of limiting, if fields should at least how large, 1.4?

**Comment by bonifarz** [comment]
Okay, done some cheap testing by just adding a dot on the guiskinbordertex. Seems that in stable, the needed frame part is cut from the texture, no matter how small the field is. On master, it starts to scale and stretch if it gets smaller than one "tile".

**Comment by bonifarz** [comment]
Haha, okay, the fix came just at the same time - great :smiley:
