### ISSUE TITLE
Possibility to get the current mastermode

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#355]
Maybe "getmastermode" can return the current status.

Theres getserver but this isnt working for the current server. (Or better it would be very complicate)

**Comment by Croydon** [comment]
I missed such a thing basically in every cube based game :+1:

**Comment by graphitemaster** [comment]
I too like useless comments for they make this ticket get more flak on IRC.

**Comment by bonifarz** [comment]
This would be useful for an admin menu. But why adding a new command? I guess a return value could be added to *mastermode* if no arguments are given.
