### ISSUE TITLE
Confusing grid size in edit mode

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#36]
Theres a confusing gridsize on small and normal size maps. That means you can scroll (G+scroll) until 1/4 of mapsize, when you scroll further then nothing happens optical. The Confusing is now when u would like the cubesize smaller, you scroll dwon for a smaller gridsize and nothing happens.
Its only affects on smaller mapsize because theres a limit for the gridsize (one quarter of a 4x mapenlarge of a new map). And while editing it happens more often that you scroll more up as needed, and when scroll down u need scroll more as it should be possible.

**Comment by coornio** [comment]
That's intended behavior, but an improvement is easy.

delta_edit_1 = [ nodebug [ gridpower (min (+ $arg1 $gridpower) (- $mapscale 1)) ] ]
