### ISSUE TITLE
showtexgui needs to be rewritten as a cfg menu, not hardcoded

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#361]
Related issues: 

In order to show the texture list via _showtexgui_ (editbind F1), all other menus have to be closed first. If this was fixed, we could go back to a previous menu after opening said list, which may be useful for the editing menus, #281. 

In that issue, there was also a request for more information in the texture list. Related to feature request #366, cubescript hooks for texture infos. 

Also: Ability to search textures, #8

And furthermore: Hardcoded checkbox textures are outdated

**Comment by shirepirate** [comment]
i've renamed this to the larger encompassing issue

**Comment by bonifarz** [comment]
I've added one more issue to the list: Since the checkbox textures have been reworked (overlays), the hardcoded checkboxes here are broken, e.g. there's no checkboxtwo. Not sure if it is worth fixing in *texturegui*, given there are plans to port the menu to cubescript.

**Comment by graphitemaster** [comment]
This is already done as part of the newui stuff
