### ISSUE TITLE
 guifield scrollbar issue

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#363]
split from #326:

> If you are using a guifield with a fixed height (arg6), as soon as there are more lines to display than this height and a scrollbar is drawn, the content is no longer shown. Same when using a guieditor (arg3) to edit a new file. When loading an existing file the scrollbar seems to work okay, though.
> Fixing this will be useful to get a reasonable layout in the vars menu when displaying long strings/list/aliases, e.g. botmalenames.

Test case:

```
x = "gone when the scrollbar pops up"
newgui test [guifield x -10 [] -1 0 "" 3 ]
showgui test
```

**Comment by qreeves** [comment]
I know I've done a lot of work on the UI since this issue, can you still reproduce it?

**Comment by bonifarz** [comment]
Just checked with 2910ee6, if you fill in more text in above example field, the text still disappears. But it's not a serious issue anyway.

**Comment by graphitemaster** [comment]
Should maybe be closed because of newui?

**Comment by qreeves** [comment]
Yeah, shouldn't even need to use fields anymore for the new system as you can wrap to specific widths with the text object.
