### ISSUE TITLE
a vshader command

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#369]
What about a new command that adds a vslot based on the selected texture, but with a different shader, given as a similar argument as for _setshader_?

I admit only few shader changes make sense, e.g. to add pulse to a glowing texture.

With _vdelta_, this could possibly merge the current and specified shaders?

Related topic: http://redeclipse.net/forum/viewtopic.php?f=7&t=799
A cubescript work-around to test a similar functionality was added in #368

**Comment by qreeves** [comment]
I actually tried to do this the other night after our discussion on the forums, but got nervous half way in when I could really determine how to implement it. I would rather leave this one to eihrul so I don't mess things up.

**Comment by bonifarz** [comment]
All right, I had no clue how difficult this would be to implement. I cannot really tell how useful this would be anyway, that's why I asked on the forums first.
