### ISSUE TITLE
Stats: Hit ratio

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#376]
Maybe we should refine how the weapon hit ratios for the game stats are defined.
Weapons with multiple rays, explosions and radial tics can get hit ratios far beyond 100%.
I guess the current data is based on the number of hit events per shots fired.
Instead, maybe it is possible to count the number of actors hit per shot?
Or better, only take into account enemy players hit per shot?
Alternately, each shot counts either as hit or miss. Would that be possible?

**Comment by shacknetisp** [comment]
Currently each ray can hit one actor.

Counting actors per shot would be hard because rays from one shot aren't distinguished from rays of another shot.

There's already `m != v && (!m_team(gamemode, mutators) || m->team != v->team)` to ensure that team damage or self damage is not counted,

**Comment by JeffBobbo** [comment]
@shacknetisp What if you hit two players with one shot? e.g., rifle2. It sounds like that just counts as one hit instead of two.

**Comment by shacknetisp** [comment]
Yeah, I phrased that wrong, each ray can hit many actors, but only one hit will be counted for each actor.

**Comment by bonifarz** [comment]
Thanks for the feedback.
Honestly, I did not look at the code, but just observe the stats, e.g. >250% on shotgun1 or >1000% on plasma2. So, counting the radial tics seems more problematic than hitting several targets in a row.
If I got your explanation right, there's no problem with the shotty, and konfoozed hit an average of 2.5 enemies per shot. I thought that's unlikely and assumed each ray gave a hit.
Any ideas what to do with the radial tics?

**Comment by freezurbern** [comment]
>Alternately, each shot counts either as hit or miss. Would that be possible?

This sounds like the best so far.

**Comment by qreeves** [comment]
What should be done is that the hit ratio should be calculated *per impact*: ```totaldamage/max(impacts, 1)``

**Comment by shacknetisp** [comment]
In shacknetisp/statsdb-interface@1860c249fa9487ec5b0b6cc7715ad359d158a99e Hit Ratios are replaced with this formula to become Hit Damage Ratios. (Tell me if you have a better name for that.)

**Comment by qreeves** [comment]
@shacknetisp Ah I see what your problem is with naming it is. The database probably needs to store the actual values for the weapon variables in each game, though that's probably insane. What you could do is just store the value for `<weap>damage<1|2>` so you can then further divide the result by that and multiply by 100 to come up with a percentage value. Eg:

```(totaldamage/max(1, hits))/(weapdamage != 0 ? weapdamage : 1)```

Don't use `max(1, weapdamage)` because it might be negative.

**Comment by bonifarz** [comment]
Not sure if I got this right, but damage per hit does not depend on misses, right? E.g. for radial damage, it's just the value per tic, and for the shotty per ray. If there's one or 30 hits makes no difference, and the only variation will be due to hit zones, e.g. headshots?

**Comment by qreeves** [comment]
Yeah I guess. Suppose I'm not really sure how to display this metric :8ball:

**Comment by bonifarz** [comment]
If it is technically difficult to get an "all or nothing" hit ratio, maybe we should discuss what other derived stats could be interesting, such as damage per time (wielded).
But I'm going off-topic, that topic is probably better suited for the forums.

**Comment by shirepirate** [comment]
further stats algorithms can be discussed on forums

**Comment by bonifarz** [comment]
Actually, I think @shacknetisp's current choice of weapon stats works pretty well :+1: 
(Damage and frags, both normalized per minute in use)
Should you decide to bring back the hits per shot stats, I guess that's okay as well, if the ratio is simply shown as a float and not as a percentage (so it is not confused with "accuracy"). That's all for this issue, and sorry for the late comment.
