### ISSUE TITLE
botspeed bug

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#379]
when botspeed is set to 0, bots will still jump around and attack players and other bots, sometimes performing parkour moves such as wallrun if they are shot and land in the proper position.

desired behavior would be no movement at all.

**Comment by shacknetisp** [comment]
I can confirm this.

**Comment by qreeves** [comment]
Well, `botspeed` now controls their movement speed. The new variable `botabilities` (which is a bitwise set of abilities) controls what they can do:
```
move    = 1
jump    = 2
crouch  = 4
dash    = 8
boost   = 16
parkour = 32
melee   = 64
```
Setting this to `0` will probably render the desired results.

**Comment by bonifarz** [comment]
Thanks quin, I already tried to look up these abilities earlier and forgot to ask about this.
As a note for testers: As far as I remember, using an even abilities value will lock the bots in place, so they won't get pushed around. There's also similar vars for grunts, drones and turrets, so you can even make the latter run and jump around :laughing:
