### ISSUE TITLE
[enhancement] Vars changing display

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#38]
(http://redeclipse.net/forum/viewtopic.php?f=4&t=520&p=4607&hilit=big+list#p4607)

If u change a variabel in the game it shows only to what it was changed, i think (mainly for coop vars editing) its usefull and a good option to show from what it was changed, so not only changed to but also the value which was changed. Still an information to the others.
example:

    Iceflower set timelimit to 0

i would like to see :D

    Iceflower set timelimit from 10 to 0

**Comment by qreeves** [comment]
How about:
```somebody set timelime to 0 (was: 10)```
I think this would let people better identify which is the new and which is the old value.
