### ISSUE TITLE
shotgun sniping

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#382]
I guess this is not intended, so let's report this here.
Crouching and standing still reduces weapon spread, which seems to be a good idea.
Interestingly, it does to the point that the shotgun's primary has about zero spread and becomes quite deadly. Due to its short lifetime, the range is capped at some 20m, so the titular sniping is not really possible :wink: 
I don't see a variable relating crouch and spread, but altering ``spreadstill`` or kickpush did not make any difference here.

**Comment by Evropi** [comment]
Haven't seen anyone using this tactic effectively at all. Being still is a good way to get fragged quick. So I think this is a non-issue and attempting to 'address' it will just cause new problems.

**Comment by bonifarz** [comment]
Ah, I see, this is also the case with the stable version.
I'm not really worried about abuse of a glitch (although i see some potential for people with good aim).
It's just the impression that there are still some bugs.
I realize the spread while crouch-standing is not "about zero", but exactly zero. Furthermore, the spread modifier for crouch and walk mode seems to have no effect while moving. For testing, I just strafed to the side while facing a wall at constant distance.

**Comment by JeffBobbo** [comment]
This issue effects more than just shotgun and needs to be fixed.

Tested with zapper2, which also suffers from this problem, making it very powerful on unsuspecting players due to it's high damage, would likely also cause problems with smg2 and plasma1.

**Comment by bonifarz** [comment]
That's another damn fast bug fix.
Looks all reasonable now :smiley:
