### ISSUE TITLE
smg2 isn't exploding when hitting players

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#387]
On the master server smg2 hits aren't exploding when they hit players and are instead acting like when they stick to walls.

**Comment by shacknetisp** [comment]
This is intentional, smg2 was changed to stick to players in the master branch and was backported to the 1.5.3 official server.

**Comment by JeffBobbo** [comment]
Really?

It looks bad (projectile doesn't stick to the player properly), makes smg2 less fun and less responsive to use, as well as nerfing it (gives the enemy more time to try and kill you).

I suggest reverting it.

**Comment by JeffBobbo** [comment]
This change has also massively nerfed the damage output of smg2.

**Comment by JeffBobbo** [comment]
@shirepirate Made a forum topic, please reconsider: http://redeclipse.net/forum/viewtopic.php?f=4&t=815
