### ISSUE TITLE
Fix player sticky collision

### ISSUE THREAD

**Issue by qreeves** [red-eclipse/base#390]
Currently it is possible for a projectile to stick at seemingly weird points due to the way the physics are handled for collision on high speed projectiles. Need to fast forward the projectile position to the impact point and check fragoffset settings.

**Comment by qreeves** [comment]
I know I wrote this, but I forget what it was for, and my description is stupidly vague.

**Comment by bonifarz** [comment]
Wasn't this for the smg2 projectiles that used to stick on the model for a while before they burst into fragments?

**Comment by JeffBobbo** [comment]
It was for the smg2 change shire made where the projectile would stick to the player instead of instantly exploding.

See the forum topic about it: http://redeclipse.net/forum/viewtopic.php?f=4&t=815
