### ISSUE TITLE
sticky auto-crouch

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#395]
How to reproduce: Move towards geometry that forces the player to crouch, e.g. a low ceiling.
Expected/previous: Automatic crouching and smooth movement, regardless of crouch key.
Observed: Player gets stuck and camera shakes up and down quickly, unless crouch key is pressed.

**Comment by qreeves** [comment]
Have we got a test case for this?

**Comment by bonifarz** [comment]
For example, the tube obstacles in hinder (after the climb at the start) or cyanide (also after a climb section).

**Comment by IceflowRE** [comment]
This destroys a trap in one of my race maps :((

**Comment by bonifarz** [comment]
Come on, @IceflowRE , don't tell me 
> it is not a bug, it is a feature

because that's nonsense :stuck_out_tongue_winking_eye:

**Comment by IceflowRE** [comment]
Take a look at the Waterrun map at the water tunnel part.... now is THIS part nonsense :D
Ok nvm i will have to change something there. (But idk when i got 6 fps on that map......)

**Comment by bonifarz** [comment]
(i know that's off topic, but here's clue for the poor performance on that water-blocks map: http://redeclipse.net/forum/viewtopic.php?f=7&t=907#p8032)
