### ISSUE TITLE
broken collision on tilted mapmodels

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#400]
Something is strange with mapmodel collision (also in the stable branch).
Example: Mode-specific grates that block some entrances in the map vault.
pitch 90 and yaw 0 seems to work fine for grate mapmodels,
but pitch 90 yaw 90 gives almost no collision.

**Comment by shirepirate** [comment]
can you elaborate or show an image of what you're talking about? and how to reproduce?

**Comment by bonifarz** [comment]
I thought that was clear from the description.
`/ctf vault` and walk throught the grate - it has (almost) no collision.
Or try a race on sm64, same issue.

**Comment by qreeves** [comment]
It could be that that specific dimension of the model is too small to be adapted properly. You can see the collision box by using: `showboundingbox 2` - you can always change the cfg to make that dimension larger.

**Comment by bonifarz** [comment]
Thanks for the clue. As far as I remember, the bounding box is strange also on non-flat models, but only when yaw and pitch are applied. I'll have a look later and report back when I have some something useful to add.

**Comment by shirepirate** [comment]
is this a bug that is worth the effort to investigate, or one of the odd normalcies in RE like being able to break through geometry in some areas?

**Comment by bonifarz** [comment]
In my opinion, definitely a bug and worth resolving. This worked fine in earlier versions, and it breaks maps that rely on mapmodel collision.

**Comment by shirepirate** [comment]
ok, might be put on the backburner for a while though.

**Comment by bonifarz** [comment]
In case that helps, I'm pretty sure this problem did not occur when I was using the devel version for a custom map update on june 17th. Soon later the map went on the race server, and the first time I tested it there i noticed most mapmodel "blockers" were broken.

**Comment by pocak100** [comment]
Git bisect pins this on commit cd98f7dcfae6deecfd17fa192823538f077e47fd.

**Comment by lsalzman** [comment]
This should be fixed in latest master now. Small accident when I was changing the layout of how 3x3 matrixes worked, the collision code didn't get updated.

**Comment by shirepirate** [comment]
indeed, i can confirm it's fixed.
