### ISSUE TITLE
Spree breaker doesn't happen in new duel/survivor rounds.

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#404]
In duel and survivor, if you score a spree and then a new round happens and you're killed the killer isn't awarded spree breaker. However, if you end the spree in the same round then you are.

The dominating/revenge system work as expected though.

**Comment by qreeves** [comment]
Probably because of the "reset" at the end of the round, pushing the survivor into waiting mode. Will take a look at it when I get a chance.
