### ISSUE TITLE
Steam overlay freezes input when returning to the game

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#410]
I have no idea if this is even a valid issue, as it is one using a third-party program (adding redeclipse.sh as a non-steam game, that is), but what if people (like me, I admit) want to show off they are playing Red Eclipse through Steam, or just want the Steam overlay?

So basically, if you Shift + Tab (I recommend setting it to ctrl+shift+tab for Red Eclipse btw), the game can no longer receive input when you shift+tab back in.

Fedora 23, XFCE desktop.

**Comment by shirepirate** [comment]
yea, this is the sort of thing to start a topic in the help forum first. especially when it hasn't been confirmed it's even a Red Eclipse issue.

**Comment by acerspyro** [comment]
@shirepirate I would do that right away if the school didn't somehow manage to block redeclipse.net lol

**Comment by acerspyro** [comment]
@shirepirate I would do that right away if the school didn't somehow manage to block redeclipse.net lol

**Comment by acerspyro** [comment]
By the way I opened a new thread on the forums about it. http://redeclipse.net/forum/viewtopic.php?f=7&t=840

**Comment by qreeves** [comment]
Still needs verifying, especially now we've switched to SDL2 and newer OpenGL contexts. I think Valve might have fixed these issues as well, from what I can gather from Google.

**Comment by IceflowRE** [comment]
Hi, i just had a steam problem too, but on another way. Just having Steam open and starting RE follows not in a freeze, but will set the mouse in the middle and not moveable.

**Comment by shirepirate** [comment]
@IceflowRE does right clicking allow you to move the mouse? i've had this same issue in the master branch but it has nothing to do with Steam

**Comment by IceflowRE** [comment]
uh yeah :D i figured out myself :D your right

Offtopic: this freezing has to do with the redeclipse.bat with redeclipse.sh it does not happens.

**Comment by shirepirate** [comment]
is this still happening @acerspyro ?
