### ISSUE TITLE
guibutton loses some functionality when no text is defined nearby

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#416]
Make guibuttons possible with no name, atm ity shows only an icon if set, but have no overlay or you cant use the action.
This would be really good for buttons with only an icon and no text. Guiimage has not all of this, guibutton has three textures (two icons and the overlay icon). For example an own guiexit icon without a name isnt possible.

**Comment by shirepirate** [comment]
can you explain this better? it is possible to create a guibutton without any text and just an image, and it sounds like that's what you're asking for.

**Comment by bonifarz** [comment]
Technically, you can still simply insert the icon in the text argument with a format string.

**Comment by IceflowRE** [comment]
example:
guibutton " " [echo "test"] [] "textures/guiexit" [] [0xC0C0C0] 0 0 "textures/guiskinborder.png" [0xFF0000]

this will make an guiexit button with an overlay if you go over it, but it has the space.

guibutton "" [echo "test"] [] "textures/guiexit" [] [0xC0C0C0] 0 0 "textures/guiskinborder.png" [0xFF0000]

This will make an guiexit button but the hover overlay and the action will not work.

**Comment by shirepirate** [comment]
yeah, this can be worked around with:
guibutton (concatword "^fa^f(textures/guiexit)" ) [echo "test"] [] "" [] 0xC0C0C0 0 0 "textures/guiskinborder.png" 0xFF0000

but at least i can see what you mean now. changing the name of issue to reflect problem

**Comment by bonifarz** [comment]
I suspect this is "not a bug, it's a feature".
Do you remember when we had to insert all those guistrut spacings to fix the menu layouts? That was when guitexts or guibuttons with empty strings where changed to be omitted. I guess this was done for some reason, but I am not sure.
