### ISSUE TITLE
black/flickering entity wires

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#421]
In edit mode, arrows and wire spheres are useful to see the radii, angles and links of entities. Those wires are hardly visible (tested with nvidia and intelHD). Their colour is mostly overlaid with black, which sometimes flickers if you get very close or if the ent is near water/alpha.

This does not occur on the stable branch. It has been around in the development version for a while, probably since some engine/shader/gl tweakes (summer?). Sorry I forgot to report this earlier. Can anyone confirm this problem?

**Comment by shirepirate** [comment]
yeah, i have no clue what you mean either

**Comment by bonifarz** [comment]
So the arrows and radii on selected entities in edit mode look fine for you? That's strange, as I get this problem on two machines with 3 different "gpus" (also when user config.cfg is removed). E.g. when I try to link teleports, it is nearly impossible to see the link mode (faded black instead of orange or red).

**Comment by qreeves** [comment]
Yeah I see what you mean now. I can't seem to narrow down what's causing it.

**Comment by Dziq84** [comment]
Radius of envmaps,lights actors etc and also 'linking arrows' disappears from certain distance, can this distance be tweaked so these helpfull lines don't disappear so early? This should be very helpfull, especially on bigger maps.

**Comment by bonifarz** [comment]
I'm sure there already is a var for this... does increasing `showentdist` work for you?

Another question: Is there a chance to increase the width/thickness of the lines drawn to indicate radii and directions? Maybe all the problems I observe here is due to a zero-ish line width?

**Comment by Dziq84** [comment]
Thank you boni, I dont know about this var, now its ok, this should be set by default to something like 20000 because "why not" ? :-P

**Comment by qreeves** [comment]
Because too many particles is a bad idea in general, and these things spawn between two and five different particles for each entity to achieve the effect.

**Comment by pocak100** [comment]
Git bisect leads to commit e2c3b4fb73861bfe040c6294a687856c308678f6 where the arrows etc. turn black.

**Comment by qreeves** [comment]
Appears to be fixed now in `master`, probably related to the matrix issues.

**Comment by bonifarz** [comment]
Thanks for getting these two issues resolved.

**Comment by bonifarz** [comment]
This indeed looked better on a blank map, but I still occasionally get invisible or flickering arrows for entity links (also when disabling config.cfg). How does this look for other players, does the issue need to be reopened? And what else might be causing this?

**Comment by qreeves** [comment]
Needs to be reopened, I saw it yesterday going through an existing map in edit mode. It happens to all entity wire particles.

**Comment by qreeves** [comment]
![20160520191948](https://cloud.githubusercontent.com/assets/3297929/15423222/d62fe36e-1ebf-11e6-9451-a720129d0ea2.png)
Done on `discontinuity` with `/entfind trigger`.

**Comment by FaTony** [comment]
Ok now the wire are not pitch black, but very transparent, it's almost impossible to see them.

**Comment by coornio** [comment]
As far as i'm concerned, I'm not seeing any black triangles emanating from entities. I did however see this oddity that wasn't mentioned. Happens are specific camera angles.
![20160830233246](https://cloud.githubusercontent.com/assets/11655762/18106229/7194f48e-6f0b-11e6-8e6c-3e68a6cbb49d.png)

Additionally I noticed the following:
1) outlines of entity radii tend to flicker underwater
2) said lines are not thick enough, so lights cannot be measured very well
3) it seems that mid-air waypoints are invisible from above?

**Comment by qreeves** [comment]
I think the best way to resolve this is to include a texture ("textures/blank" perhaps) for the particle primitive render types. It would both improve the look of the of the render and probably eliminate the issues we're currently having with them.

**Comment by bonifarz** [comment]
Boy, I'm happy to see this one is finally fixed. An important step towards V1.6 👍

**Comment by FaTony** [comment]
Now I see no wires or waypoints at all.

**Comment by qreeves** [comment]
`git pull --recurse-submodules`
Your "data/textures/blank.png" is probably out of date.

**Comment by FaTony** [comment]
Still the same.
