### ISSUE TITLE
Redeclipse 1.5.3 doesn't start Fedora

### ISSUE THREAD

**Issue by mastaiza** [red-eclipse/base#429]
When trying to execute the app, it crashes. It occurs always, as normal or super user.
2015-12-24 12:24.52 loading enet..
2015-12-24 12:24.52 loading game..
2015-12-24 12:24.52 identity: v1.5.3-nix64 client (Aurora Edition) [0xa6f7e4da]
2015-12-24 12:24.52 loading sdl..
2015-12-24 12:24.52 loading video..
2015-12-24 12:24.52 vsync is disabled
2015-12-24 12:24.52 loading gl..
2015-12-24 12:24.52 renderer: Mesa DRI Intel(R) Sandybridge Mobile  (Intel Open Source Technology Center)
2015-12-24 12:24.52 driver: 3.0 Mesa 11.0.6 (git-2555e00)
2015-12-24 12:24.52 loading sound..
2015-12-24 12:24.52 allocated 32 of 32 sound channels
2015-12-24 12:24.52 loading defaults..
2015-12-24 12:24.52 loading gl effects..
Fatal signal 11 (Segmentation Violation)
[Trace of RedEclipse execution .txt](https://github.com/red-eclipse/base/files/81898/Trace.of.RedEclipse.execution.txt)

**Comment by acerspyro** [comment]
Why did you close your previous issue to open it again? >.>

**Comment by mastaiza** [comment]
I did it by accident .

**Comment by acerspyro** [comment]
You may want to come over on IRC (go to http://webchat.freenode.net/, channel is #redeclipse) so that we can further assist you with your issue.

**Comment by mastaiza** [comment]
ок 
I'm on the channel

**Comment by mastaiza** [comment]
why is the bug closed

**Comment by shacknetisp** [comment]
An answer was written [replying to your other issue](https://github.com/red-eclipse/base/issues/428#issuecomment-169857193).

**Comment by qreeves** [comment]
It is a help and support issue, as per our issue reporting guidelines the tracker is for confirmed bugs in the Red Eclipse software, not for driver and operating system issues.

**Comment by mastaiza** [comment]
GNU gdb (GDB) Fedora 7.10.1-30.fc23
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/libexec/redeclipse/redeclipse...
warning: the debug information found in "/usr/lib/debug//usr/libexec/redeclipse/redeclipse.debug" does not match "/usr/libexec/redeclipse/redeclipse" (CRC mismatch).

Reading symbols from /usr/libexec/redeclipse/redeclipse...(no debugging symbols found)...done.
(no debugging symbols found)...done.
Missing separate debuginfos, use: dnf debuginfo-install redeclipse-1.5.3-1.fc24.x86_64
(gdb) r
Starting program: /usr/libexec/redeclipse/redeclipse 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
could not find config directory
[Inferior 1 (process 2508) exited with code 01]
(gdb) q

**Comment by qreeves** [comment]
Seeing as you seem to be ignoring everyone who is telling you this is not the place for getting help, I'll be blunt: _You **cannot use Mesa DRI drivers**, you need to at least have the drivers from Intel. If they don't work then it will never work because there are huge problems with Intel Graphics Drivers. Don't post here again without having a real bug that is our fault and not someone else's, **use the forums**_.
