### ISSUE TITLE
capture-the-flag enhancements

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#430]
when carrying your own flag and the enemy flag, walking over your base (or more specifically, the cubic area of the sphere surrounding the entity in which you are defined as near enough) should immediately score and return both flags. it should not be necessary to wait there for any period of time or walk over it several times before something happens, this should happen without a delay. also when the enemy flag is sitting loose within the base area, entering the base area with the home flag will become an immediate score.

currently you can pick up your flag using the affinity button (default F). pressing F again should return a flag if you are within the defined area of it's base, no matter the team. currently, pressing F will drop a flag on the base but not actually register that it has been returned. to prevent your own flag from being returned immediately after you've picked it up, a timer should be used (similar to how it is done currently most likely, 5 seconds seems appropriate as default), after which it will be returned automatically. important: this timer should be automatically interrupted if both flags enter the same base at any time, becoming a score.

when a loose flag or a player holding a flag comes within the defined area of a base by any means, the flag should return to its own base when appropriate, similar to destroying a base with the bomberball (a player holding an enemy flag in their own base when their own flag is not there would not be an appropriate time, for example). this means if a player is carrying both flags and runs toward a base and is killed, and both flags fly into the area of the sphere it counts as a point for the team of that base. even if they do not touch at the same time, the home flag touching this area will return it to that base and the enemy flag touching this area will count as a capture. this has the added benefit of preventing the cheap tactic of carrying your flag to the enemy base, grabbing that flag and returning to your base (instead, you will have scored a point for the enemy when you bring your own flag into the enemy base when their flag is also there).

so to sum these up (flag will be defined as *either* a **loose flag** or a **player holding a flag**):

both flags enter a base --> immediate capture for that base/team
flag enters home base --> immediately returns to that base
flag enters enemy base --> becomes a capture if the other flag is there
pressing F while holding a flag over a base --> returns it to that base
remove all timers related to when a flag may be picked up after it has been dropped, in favor of other balance mechanisms

these summed up points may seem very similar to how the current mechanics work, but there are quite a few small things that need tweaking as explained in the prior paragraphs. it may even need some test plays after the changes have been made, before closing the issue, to make sure everything was caught.

**Comment by JeffBobbo** [comment]
Not sure these are the best of ideas.

> flag enters home base --> immediately returns to that base

Using an area around the flag point (as you mentioned earlier), depending on it's range this could get annoying for people who like to secure their flags (not that this is a good mechanic anyway, this isn't an appropriate way to fix it).

> pressing F while holding a flag over a base --> returns it to that base

Is this rendered useless by the above?

> remove all timers related to when a flag may be picked up after it has been dropped, in favor of other balance mechanisms

There's no addressing of flag toss resets (and currently there is a timer for that, although the duration has been reduced in 1.5.3 from earlier 1.5 releases).

In your prose you suggest:

> this has the added benefit of preventing the cheap tactic of carrying your flag to the enemy base, grabbing that flag and returning to your base (instead, you will have scored a point for the enemy when you bring your own flag into the enemy base when their flag is also there).

This seems like bad suggestion. If a capture area is implemented you might score a capture for the enemy team by trying to recover your flag from their base. Additionally it means if you cleared their base, grabbing the flags in the wrong order could score them a capture when you were about to get one yourself.

Removing timers associated with making captures and such (except the one for flag toss resets until that is addressed) is a good idea though, they're often annoying and cause confusion and frustration.

**Comment by shirepirate** [comment]
>Using an area around the flag point (as you mentioned earlier), depending on it's range this could get annoying for people who like to secure their flags

i'm not talking about extending this range or creating a new "capture area," it's fine as it is now. the cubic area of the current affinity entity is what i was referring to (you don't need to be standing directly on the base to secure or capture, being close to it is enough). securing flags will not change at all, it will be the same as it is now (press affinity button to secure, if you hang in the base too long the flag is returned automatically).

>Is this rendered useless by the above?

if dropping it within the base area (thereby making it a loose flag) immediately returns it then the issue resolves itself, but that would have to be implemented first otherwise it's still an issue.
Currently pressing the affinity button will just drop the flag right on top of the base, which is sort of stupid and can lead to situations that might change a CTF match outcome given the current timer that does not allow you to return both flags immediately.

>There's no addressing of flag toss resets

This issue will be addressed by qreeves at the same time as the rest of these changes when he comes to a decision, so the timers will no longer be necessary when they are replaced by other balance mechanisms

>If a capture area is implemented you might score a capture for the enemy team by trying to recover your flag from their base

as mentioned before: both flags enter a base --> immediate capture for that base/team
they can't both be loose hanging out in a base, this will just turn into a score. the objective is to grab your own flag and return it to safety, if you have the enemy flag you need to ditch it before entering the enemy base to recover your own. it's not absolutely necessary to add this, it could instead be:
both flags enter a base loose --> immediate capture for that base/team
this would prevent an enemy score when holding the enemy flag and recovering your own, but the "flag hog" issue isn't solved
