### ISSUE TITLE
new console menu: Tab/ Esc/ textscale

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#434]
61bdaf6 is a very nice improvement, as we get a new menu for the console history.
However there are two issues with important keys:
* Tab-completion does not work, pressing *Tab* will execute the input line instead
* ~~people are used to close a menu or command prompt via *Esc*, right now only middle click works~~

Side note: I'm also missing the leading slash (/) in the command prompt line.

**Comment by qreeves** [comment]
Yeah, this is really a WiP. The old method of `inputcommand` is still bound to `/` (SLASH). I'll be working on this more to better implement the features of the old method.

**Comment by bonifarz** [comment]
I see, and it's a cool experiment. So at the moment, it's just limitations with gui input fields that are kept in focus.
For now, players who don't have a forward slash on their keyboard layout can just use another bind, e.g.
`/bind BACKQUOTE "saycommand /"`

**Comment by bonifarz** [comment]
I'd like to note this here as well: Once you use the console menu, `textscale 2.75` is set in the user's *config.cfg*. Upon restart, this gives a very large font for the default console, chat promt and the info text at the bottom right. Entering `/textscale 1` works fine as a quick fix.
