### ISSUE TITLE
thirdpersonside 0 causes loads of bugs at high frame rates

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#436]
When thirdpersonside is set to 0, the gui doesn't render properly when at high FPS (starting at around 170fps on my system, unplayable at my usual FPS levels of 300~380).

**Comment by qreeves** [comment]
Seeing as I can't get RE to run that fast on my aging systems, I can't debug this.

**Comment by bonifarz** [comment]
>starting at around 170fps

So, this only gets problematic if you have a monitor with a comparable refresh rate or if you want to use your GPU as a heating, right? :wink:

**Comment by JeffBobbo** [comment]
Default max fps is 200, RE is single threaded, faster FPS is faster logic.

Another symptom is that the cursor distance value sometimes changes to nan for a frame, I can get a video when I go home.

**Comment by qreeves** [comment]
That actually helps a bit, might be the camera plane is colliding with the player model.
