### ISSUE TITLE
check menus for textwrap

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#441]
Just a note so we don't forget to check the menus, mostly those many many help pages.
With the recent tweaks to skin/fonts/text padding, several of these menus have a broken layout, in particular  the text wrap (multiple lines per guitext) does not seem to work.

**Comment by qreeves** [comment]
The values are probably just a lot smaller now that I've restored `guitextscale` to `1` and set `guiscale` accordingly. Everything was technically 2.5 times bigger before.

**Comment by bonifarz** [comment]
Right, i remember we had to make the wrap values bigger by a similar factor before. So, this should be easy to fix.

**Comment by bonifarz** [comment]
closed via #442
