### ISSUE TITLE
backquote key not recognized

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#448]
This one might be exclusive to my keyboard layout (german-switzerland).
The top left key below Esc  worked fine earlier for the map "backquote". With the latest master version, there is no response, even when i click a *guikeyfield* and press that key.
Does anyone else observe a similar issue?

**Comment by IceflowRE** [comment]
You mean the "cmd key" ?

**Comment by bonifarz** [comment]
Yes (although there's two default keys for that, backquote and backslash). So, does it work for your german layout?

**Comment by IceflowRE** [comment]
It wasnt working (i have Linux now) but i get fixed :D (around the SDL2 changes)

**Comment by qreeves** [comment]
Works for en-AU too. Gonna need more information to track this down.

**Comment by bonifarz** [comment]
Right, maybe not an issue of RE at all. When switching to US keyboard layout, the key is recognized just fine as BACKQUOTE. On german (germany), it works as CARRET. On german or french (switzerland) it is dead. Maybe I'll try another OS later.

**Comment by bonifarz** [comment]
I conclude they key mapping did not work correctly for this layout in earlier versions, including stable. Some keys were just mapped as if it was an US layout, now the mapping is done properly. If there's no backquote on the keyboard, that's not RE's fault :smile:

**Comment by IceflowRE** [comment]
Just as information but if you use it as CARRET it automaticaly insert a " ^ " in the command line which can follow into a ê/â and so on which is really annoying. Can the input of the ^ prevented?

**Comment by bonifarz** [comment]
I guess that has nothing to do with RE. Best we could do on our side is provide alternate default binds for foreign language keyboard layouts.

**Comment by IceflowRE** [comment]
But it wasnt there before :D
