### ISSUE TITLE
Var for scaling vampire regen

### ISSUE THREAD

**Issue by HeroesGrave** [red-eclipse/base#45]
There currently does not appear to be a var for scaling the amount of health gained from damage when vampire mode is selected.

It would be nice to have games where players who deal lots of damage get some sort of bonus, but without a scaling factor it can make one player overpowered with very little effort (one well-placed shot).

The scaling would work by multiplying the damage dealt before adding it to the players health. (I'm not sure what the current algorithm is but something like `playerHealth += vampireScale * damageDealt`)

Values from 0-1 would decrease the amount of health regained, values >1 would increase the amount gained, and values <0 would cause the player to lose health when dealing damage (if possible. Not sure if there's actually a good use for this so it's not a big issue)

**Comment by qreeves** [comment]
Can you elaborate on how this scaling would work?

**Comment by HeroesGrave** [comment]
Yes, sorry. Updated top of thread.

**Comment by qreeves** [comment]
So the "scale" is a fixed amount, and it just skews the incoming health value? Easy enough to do.

(See, this is why the forums are better as a first point of contact, I have to ask too many questions that the community could've figured out days ago).
