### ISSUE TITLE
claws icon

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#454]
I know the claws are work in progress, and it will take a while to fully support the models from the community repo. Though, it would be nice to fix the missing icon for this new weapon, which causes some clutter in the console.
 @V-ktor / Unnamed has made nice weapon icons earlier, maybe he finds the time to create one for his claws, too :smiley:

**Comment by qreeves** [comment]
Sounds like you need to git pull --recurse-submodules

**Comment by bonifarz** [comment]
It's fine now after a simple pull - cool. I'll close this one.
