### ISSUE TITLE
Halo effect in light actors

### ISSUE THREAD

**Issue by Dziq84** [red-eclipse/base#458]
As Quinton working on that at some point, might be a good idea to revisit that idea.
Basically light sources now lacks something very important, especially in fogged maps - the halo effect like in street lamps in real live. this might be just a selectable texture with color reflecting actual color of an given light actor.  This might be a great visual improvment, like faking volumetric light without performance drops, also this should give a light more natural look and of course, great eye candy :) How about that ?

PS:  @qreeves:  I found a little bug with flares you implemented in master, but it's need a verify from someone else, basically just make sunlight actor, give it a flare parameter and set its scale to something like 30000, now look exactly at center of sunlight source and you'll see strange flickering, especially outside editmode (because first person camera moves a little with player).

**Comment by shirepirate** [comment]
a value of 30,000 for flare scale is ridiculously high (should never really be set above 1,000).
there does seem to be a bug though
https://youtu.be/cMmuDq-U0po

**Comment by qreeves** [comment]
Does it happen if you turn off glare? It looks like changes in the overall screen gamma contributes to the glare changing dramatically, which is to be expected as it is/was a cheap trick for older hardware without shader support.

In general, you spend very little time in one spot looking upward at the sun when playing RE, the effect is supposed to be additive to the feel of a level, not a centrepiece. This thread is actually off topic from the original post, @Dziq84 should have created a separate issue for it.

**Comment by qreeves** [comment]
Volumetric lights are now available in master.
