### ISSUE TITLE
Sometimes Weapons do no Damage until next Respawn (RE 1.4)

### ISSUE THREAD

**Issue by DrAzraelTod** [red-eclipse/base#46]
I'm not really sure if it's a bug or feature, but sometimes after a respawn my weapons do no damage at all until my next death. I hear hit-sounds and everything seems normal, but enemies will never die.

I've verified that with a suicidal modification to the rifle (no range, large explosion, no timeout till damage) that does 90 damage to myself. If that bug happens, i can fire it repeatedly for minutes and i won't die. It works otherwise, killing me on second shot (if i had 100 health before).

It might be that i ran into some kind of cheat-prevention, since i modified other vars too. I.E.: people who do massive damaged to multiple players/bots in short time are probably "cheaters". But this even occured in insta-gib, where i managed to hear the hit-sound dozens of times, without scoring a single kill.

**Comment by IceflowRE** [comment]
Have you this problem online or offline?

**Comment by qreeves** [comment]
Have you verified this in the development version as per http://redeclipse.net/wiki/How_to_contribute#Issue_Reporting_Guidelines?

**Comment by DrAzraelTod** [comment]
@IceflowRE 
online, on my own server (well, lag _might_ be a problem, but is imho highly unlikely)
as stated before it's instantly solved after getting killed and respawning, so i doubt that beeing the reason.

@qreeves 
Ugh... no, i did not.
Maybe i'll do that this weekend.

**Comment by shirepirate** [comment]
this is a common bug when your client becomes de-synced from the server (i'm assuming it only happens online?)
sometimes you also can't pick up explosives properly, and there are other strange effects as well.
a /reconnect always fixes it

**Comment by DrAzraelTod** [comment]
i could reproduce it by throttling my network and creating artificial network-traffic.

so i guess that's the main reason, even though i did see it on pretty good network before
