### ISSUE TITLE
/edit <nonexisting map> should act as a new map online

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#460]
If you type online /edit XYZ (a nonexisting map) you will go into a requesting screen. (i think unendless), if the map is not existing it should act as a kind of newmap. That it loads an empty map.

**Comment by shirepirate** [comment]
yeah, ran into this one once earlier and was trying to reproduce it.

**Comment by qreeves** [comment]
No, you should use /newmap - the /edit command calls a vote under normal conditions.

**Comment by shirepirate** [comment]
the /edit command has been fixed in master
