### ISSUE TITLE
guinohitfx does not work

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#461]
*guibutton* or *guiimage* elements inside a *guinohitfx* block should have no hover overlay.
This is useful for images that do not act as a button, e.g. on the mode help menus.
Currently, *guinohitfx* seems broken on master.

**Comment by IceflowRE** [comment]
guinohitfx only works not if you use guinoskinfx.

**Comment by qreeves** [comment]
Yeah, there are different commands for `guinohitfx`, `guinoskinfx`, and `guinocursorfx`.

**Comment by bonifarz** [comment]
Okay, then I will see if I can update the corresponding menus and instructions accordingly.

**Comment by bonifarz** [comment]
@IceflowRE, I'm not sure if I get your answer right.

As far as I can see, what we need for non-button images is *guinocursorfx*, while  *guinoskinfx* reverts to the old style text hover. I don't see the use of *guinohitfx* - should that act on click sounds (which we don't have)?
Can you verify if this gives the intended behavior?
```
tt = 0
newgui fx [ guistayopen [
    guilist [
        looplist i [guinohitfx guinoskinfx guinocursorfx] [
            guilist [
                guitext $i
                $i [
                    guiimage $questiontex [] 4
                    guibutton "sample button"
                    guicheckbox testbox tt 
                    guiradio testradio tt
                    guislider tt 0 2
                ]
                guistrut 1
            ]
        ]
    ]
]]
showgui fx
```

**Comment by IceflowRE** [comment]
Combo: combinations of the three no fx's
buttons: old style or new style while onhover
image: if the image is colored while onhover
cursore: colored while onhover
a check means colored or new, no (or black) check means old or not colored

Combo | buttons | image | cursor 
--------- |-------- | ---------|--------
guinohitfx | :white_check_mark: | :white_check_mark: | :ballot_box_with_check:
guinoskinfx |:ballot_box_with_check: | :white_check_mark: | :white_check_mark:
guinocursorfx | :white_check_mark: | :ballot_box_with_check: | :ballot_box_with_check:
guinohitfx, guinoskinfx | :ballot_box_with_check: | :white_check_mark: | :ballot_box_with_check:
guinohitfx, guinocursorfx | :white_check_mark: | :ballot_box_with_check: | :ballot_box_with_check:
guinoskinfx, guinocursorfx | :ballot_box_with_check: | :ballot_box_with_check: | :ballot_box_with_check:
guinohitfx, guinoskinfx, guinocursorfx | :ballot_box_with_check: | :ballot_box_with_check: | :ballot_box_with_check:

**Comment by IceflowRE** [comment]
Yes we dont need guinohitfx anymore.
Only pro for it is, that you can surround buttons and images with guinohitfx without using two things or seperate them, but this is not necessary and makes everything much more complicate.

I would remove nohitfx and change it in every gui.

((If theres nothing different we didnt see))

**Comment by bonifarz** [comment]
Ah right, the effects on the mouse pointer... that's why one of the commands is named cursorfx. Maybe the intended behavior was to keep the hitfx option backwards compatible, and its current effect was meant for nocursorfx. I adapted the menus earlier today, so all the images work as they used to - and in case the conventions for gui*fx change again, it will be easy to revert the menus.

**Comment by qreeves** [comment]
What you're probably not understanding is that with certain elements like buttons, etc. turning off `skinfx` falls back to using a `hitfx` (skins are a "layer" on top of the old interface, and variables exist to revert to the old behaviour, which is why it is a little complicated). You have to turn them both off in those cases to remove all effects, and in many cases, if you turn off `hitfx` it will skip the `cursorfx` as well.

**Comment by bonifarz** [comment]
Of course, and the skin improvements compared to stable are nice. The only issue I wanted to report is what you get in the official menus, and that was readily fixed, thanks to your first comment.
