### ISSUE TITLE
ability to get player deaths/kills amount by cubescript

### ISSUE THREAD

**Issue by Dziq84** [red-eclipse/base#467]
I know its not that hard for devs to make this possible. For example I want to create a simple script for some kids (like my nephew) to auto-bot-hardness level based on these variables, but with more capabilities like:
  -bot abilities
  -bot spawn weapon
  -bot speed

I just need to get by cubescript a player deaths/kills amount.
It would be ideal to get more info - like how many times a bots killed a player and vice versa, but its not necessary :)  thanks in advance for making my request possible ;p

**Comment by Dziq84** [comment]
Thank you guys for make his possible :)

**Comment by bonifarz** [comment]
Yes, could also be very useful for unofficial tutorial maps that address modes and mutators.
