### ISSUE TITLE
glare 0 segfault

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#472]
split from #323
Steps to reproduce with current master:
* launch the client
* set glare to 0
* /race testchamber
* try to spawn

Seen on some other maps and modes. Does this happen for other players, too?

**Comment by qreeves** [comment]
Backtrace provided by @graphitemaster - http://pastebin.com/raw/nCKMzMq2

**Comment by IceflowRE** [comment]
I can say it crashs for me one!! time, after it i have no problems with. Can you tell me where the problem is too (other maps etc.)?

**Comment by lsalzman** [comment]
Fixed.

**Comment by graphitemaster** [comment]
Good job @lsalzmal
