### ISSUE TITLE
enhance vanity menu

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#473]
Feature request by @Dziq84: Group the vanity item buttons in the profile menu such that it is more clear which of them can be used together, since some vanities will override others if they have the same anchor point.

I realize that vanity items are already sorted by their "type", as returned by `(getvanity id 0)`, so maybe that's a good starting point. Maybe a collapsible bunch of radios for each "type" will work better.

This should be useful as the number of vanities is further increased.

**Comment by Dziq84** [comment]
exactly, I planning to make more vanities so imagine how that existing vanity list will be confusing for users  later

**Comment by bonifarz** [comment]
I see that the tags will be needed for this, `(getvanity id 3)`, not the types, which are not really clear to me. I managed to purge vanities as you replace them with one of the same tag, but the menu still looks confusing with the old layout. First experiments with radios per tag did not look any better. This needs some more experiments until I will make a PR or commit.

**Comment by bonifarz** [comment]
This is how the draft looks that i just committed.
![vanities](https://cloud.githubusercontent.com/assets/10864175/14767559/0d791120-0a29-11e6-8dcb-d26eb0cc9d42.jpg)

I'd like to leave the issue open, as this may still need some tweaks.
Also, maybe it will be cool to add a mapmodel preview for the vanities as well?

**Comment by Dziq84** [comment]
This is looking much better than old one, maybe start this list with slot 1 rather than 0 ?
Also player preview is now constantly rotating, it be ideal to add ability to rotate and zoom by yourself in that preview window (especially when making vanities its hard now to see how its fitting a player mesh)

**Comment by bonifarz** [comment]
Yes, the playermodelpreview... I've already requested this in issue 44
Will fix the slot offset when i have another update.

**Comment by bonifarz** [comment]
After some more tweaks, I think this is ready. Details: http://redeclipse.net/forum/viewtopic.php?f=4&t=931
