### ISSUE TITLE
gladiator maps?

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#476]
The deathmatch mutator *gladiator* has its own map list, which currently only holds *dutility*.

What are the plans for this, should we get a few simple "platformer" maps for the next release?

**Comment by qreeves** [comment]
Yes. Even if they're just basic they can be improved later by better artists.

**Comment by bonifarz** [comment]
I think the last section of the race map *purge* could work well for gladiator. Should be easy to add mut-specific doors and playerstarts. Shall we give this a try?

**Comment by qreeves** [comment]
Go for it.

**Comment by bonifarz** [comment]
Done on the maps repo (purge.mpz). Have not updated the map submodule pointer on base, since there's lots of other changes.

Another map that might work even without any modifications is deathtrap.

**Comment by bonifarz** [comment]
I've had a look at the four original SUMO maps on the "DOOM USA" server, and I guess they are not suitable for inclusion. I'll think about more maps from the main rotation that can be made gladiator-compatible, e.g. abuse, biolytic, rooftop or maybe affluence. Again, the idea is to lock a section via mapmodels, or to place a platform somewhere in the "background" of the map.

**Comment by bonifarz** [comment]
I'll leave this open in case there are more last-minute maps, or in case some tweaks are necessary. Can also be discussed here: http://redeclipse.net/forum/viewtopic.php?f=5&t=939

**Comment by bonifarz** [comment]
If the map "disco" is acceptable for inclusion, it would be really great to also include snipergoth's disco-ball mapmodel. The latest version of disco which uses this mapmodel is found on http://redeclipse.net/forum/viewtopic.php?f=5&t=939#p8442, the mapmodel is in the previous post.
![disco](https://cloud.githubusercontent.com/assets/10864175/15097846/554fef6c-152a-11e6-940e-b7832ce6cf38.png)

**Comment by bonifarz** [comment]
I guess we can close this for now. 
In case the disco-ball model cannot be kept, we can simply revert 0ee7995 on the maps repo.
