### ISSUE TITLE
male and female based vanities

### ISSUE THREAD

**Issue by Dziq84** [red-eclipse/base#478]
This can improve positioning of vanities and allow to do more of them.
Now its hard or impossible to attach vanity items that fit both male and female body nicely.
Quin suggested that this can be done by putting vanities in two subdirectories (vanities/male and vanities/female) and later, a certain check will be writen to make this possible.
I'm looking forward to it :)

**Comment by shirepirate** [comment]
as long as it doesn't needlessly duplicate the files in /data/ it sounds good. separate anchors for each model is probably something that should have already been in place anyway

**Comment by Dziq84** [comment]
Leave a comment I'm thinking more about ability to use another mesh of given vanity when female is choosen

**Comment by shirepirate** [comment]
>I'm thinking more about ability to use another mesh of given vanity when female is chosen
why is this needed? sounds more restrictive than anything, rather than allowing them to be used on either model. plus both meshes would have to be added to the data folder, inflating size. i'm against it.

**Comment by Dziq84** [comment]
in my point of view its not possible to make some vanities that fit a both bodies of male and female. I updated previous post when you typing btw :-P

**Comment by shirepirate** [comment]
maybe we're better off without those vanities, then, rather than making the menu even more complicated and needless redundancy.

**Comment by Dziq84** [comment]
hmmm this have nothing to do with menuses (?) since its should be automatic in background. If separate vanity models is a bad idea, maybe just use another cfg of given vanity item with own positioning for females. (and really I have a very game fitting vanities in mind but its not possible since these two bodies are totally different, even separate iqm.cfg can't help in this case. Also each model is just around 40kb of size, no additional textures or so for separate vanities needed)

**Comment by bonifarz** [comment]
I thought this request was just about fine tuning the positioning of a vanity, where a small difference in the f/m meshes matters. Though, you probably have to get pretty close to see the misplacement?

The menus could easily be tweaked to ignore some vanities based on a male/female keyword in their identifier. Also, no problem to switch the corresponding vanitites if the player changes the model gender via the profile menu.
