### ISSUE TITLE
visible edges of skyboxes

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#481]
This is usually hard to notice, but on many skyboxes, the edges of the cube are visible, as if the texture was shifted by a pixel. For example, *skyboxes/yellow*:
![yellow skyboxedge](https://cloud.githubusercontent.com/assets/10864175/14989192/f50b28a0-1156-11e6-848b-09a410708374.jpg)
Interestingly, I cannot see this issue on some other skyboxes, such as *skyboxes/stormydays*.
This does not occur on stable. I think i have seen it quite a while ago, but forgot about reporting it earlier.

**Comment by qreeves** [comment]
I can't reproduce this one.

**Comment by bonifarz** [comment]
Seems to be fixed with the latest changes to *src/engine/rendersky.cpp* :+1:

**Comment by bonifarz** [comment]
Okay, since the patch for "tear in skybox" was removed, I see this again. 
Another example where this is well visible: _elyvisions/sh_
![edge-elyvisions-sh](https://cloud.githubusercontent.com/assets/10864175/15774481/ca560862-297c-11e6-86cb-02941501a2bd.png)
Can anyone reproduce this?

**Comment by bonifarz** [comment]
Now, this gets weird. I do not observe the issue when i load a map or set the skybox without using the menu. More specifically: Only when the preview (net) of a skybox is shown before applying the skybox, these edges get visible. Really strange. But reproducible for me.

**Comment by lsalzman** [comment]
In the gui code that does the guiimage call with the skybox previews, concatword the prefix "<thumbnail>" onto the filename first. The guiimage call is loading the image with different settings than the skybox code and that is messing things up. The thumbnail prefix should disambiguate it.

**Comment by bonifarz** [comment]
That makes sense, thanks for the clue!
Though, this limits the resolution of the guiimage, right? So, I'll either have to make the preview much smaller, or it will look really bad. Current scale is 5, anything larger than 2 gets visibly blurred. I'm not sure what's the best solution, since large previews are nice to have, and the edge artifact is a relatively small issue.

**Comment by lsalzman** [comment]
In this case it is not an option to just ignore it, since you are loading the textures with the wrong options. That is always going to cause problems and should just not be done. You can also supply a max size to the thumbnail command, i.e. thumbnail:128. I would not go any larger than 256 though, and 128 would be best if it works.

**Comment by bonifarz** [comment]
Thanks again for your useful feedback.

I'd say the difference btw 128 and 256 can be noticed with the current image scale, but 128 looks definitely good enough for the menu.

I'm happy with this solution :+1:
