### ISSUE TITLE
Fix OSX build

### ISSUE THREAD

**Issue by qreeves** [red-eclipse/base#484]
As far as I remember, the Xcode project still needs updating for the new SDL2 stuff. There's probably some other things that need fixing in relation to this too.

**Comment by acz13** [comment]
Is it possible to target OSX on Linux?

If not I could probably get my hands on a mac...

**Comment by qreeves** [comment]
I've updated everything so far but can't find universal (ARCHS="i386 x86_64") SDL2 frameworks, so I either have to figure out how to build them, find someone else who has built them, or go to having releases compatible only with "x86_64".

**Comment by TheAssassin** [comment]
SDL2 frameworks can be extracted from the dmgs that can be downloaded from SDL's homepage:
https://www.libsdl.org/download-2.0.php

I'm not sure whether they're universal, but they definitely contain x86_64 symbols.

**Comment by bonifarz** [comment]
This is the most important release blocker, right? The other two 1.5.5 milestones are annoying, but I guess they can still be fixed with automatic updates.
