### ISSUE TITLE
dm-mutator icons

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#485]
We have new deathmatch-specific mutators, but no icons for them.

Obviously, the claw/melee icon will be be okay as placeholder for *gladiator*, but I have no idea what to use for *old school*. 

Maybe @V-ktor or @IceflowRE can come up with some new, shiny icons?

Also, I guess the *basic* icon (pistol) is still a placeholder, but I cannot think of anything better :wink:

**Comment by IceflowRE** [comment]
I can do it :D but we still ne an idea :D

**Comment by qreeves** [comment]
I guess "gladiator" should be two guys racing toward each other with claws drawn or something. Maybe "old school" can be a picture of a school? It should be noted that "classic" still uses the old "arena" icon, from before the whole game was inverted to use loadout weapons by default, but maybe it is still apt.

**Comment by shirepirate** [comment]
for old school, if a building is not easy enough to identify it could be a symbol of something that easily represents school

http://i.imgur.com/XeuFQds.jpg

might get some ideas from that (recreate from scratch of course, so as to avoid conflicts)

**Comment by bonifarz** [comment]
Or maybe a pixelated deathmatch (skull) icon? Old school shooters pun.

**Comment by IceflowRE** [comment]
Ok, i will make some previews tomorrow.

**Comment by IceflowRE** [comment]
https://drive.google.com/open?id=0B__JdfXlvXlxdXF2S255YVhqcG8
Any other ideas and improvements are welcome.

**Comment by bonifarz** [comment]
If i had to choose, I'd pick gladi a) and oldschool c)

**Comment by JeffBobbo** [comment]
gladiator a looks good, but the old school c is a bit misleading to the name, although I'm not really sure what old school is supposed to be?

**Comment by IceflowRE** [comment]
I add two small other things. (broken building)

**Comment by shirepirate** [comment]
i kinda like the old_school_c, but the crown is not very good. we already have a crown in privs so perhaps you could make it similar to that? maybe lopsided on the skeleton so it is actually wearing it? you could also add a lower jaw to give it the appearance it is smiling, and make the eye sockets more narrow.

**Comment by qreeves** [comment]
Old school is "most frags" instead of the default "most points", like old school fps games.

**Comment by bonifarz** [comment]
that's why i suggested a pixellated icon, but i guess it is impossible to make that look any good.

**Comment by JeffBobbo** [comment]
Perhaps a person standing over a recently deceased one with a +1 (and maybe a +3 cross out)?

**Comment by bonifarz** [comment]
Okay, so two icons are now in place. In the help menu, i just expected different texture var names. *modedeathmatchgladiatortex* seems very long, though.Now it's "modegladiator* without a *tex* suffix. Maybe *modedmgladiartortex* is a fair compromise? Well, really does not matter and will be trivial to fix.
