### ISSUE TITLE
lightfx broken?

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#488]
I just had a look at glow/pulse lightfx and I am not sure if something is broken.
I know the last (blue) section of "escape" uses glowfx on green light for some pulsing color effects. These are nicely visible on stable, but not on master. I think the map is identical.

EDIT: When i place a light and a lightfx ent on a blank map, it seems that only spotlight is working in master, compared to doing the same thing on stable.

**Comment by qreeves** [comment]
Works for me?
![20160508134028](https://cloud.githubusercontent.com/assets/3297929/15095877/7ed6e8de-1522-11e6-894e-4751a65b1ba9.png)

**Comment by bonifarz** [comment]
Works all right, I did not realize I had messed with some graphics settings earlier and forgot to revert them. Sorry for the false report.
