### ISSUE TITLE
enhance player name customization

### ISSUE THREAD

**Issue by shirepirate** [red-eclipse/base#489]
add a few more open source fonts for player chat and name customization
add ability to choose font or multiple combined fonts for player names
add ability to customize player name colors down to each individual letter
add ability to bolden, underline, italicize, and change to one of three text sizes (and combinations thereof) for player chat and name customization
create command similar to /getclientnameconfig to fetch all name customization information to be used for global stats pages or other purposes

**Comment by JeffBobbo** [comment]
If these things are added, I also hope there are options to strip them client side, I actually want to be able to read what gets said, not get headaches.

**Comment by shirepirate** [comment]
i'm sure that could be added too :unamused:

**Comment by qreeves** [comment]
Absolutely not, these things are purposefully missing from Red Eclipse.

**Comment by shirepirate** [comment]
but why? these are the types of features that repeat players actually like. people love ways to express themselves in games and stand out from the rest. it encourages uniqueness in competitiveness.

if it's purposefully missing at least explain the reason, who knows, maybe there's a good one. you can't just take this attitude any more when new ideas come up, the project is openly developed

**Comment by qreeves** [comment]
You'd have found out had you followed the proper procedure for suggestions.
