### ISSUE TITLE
server icon for stats tracking

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#497]
I think with the new stats system, it would be pretty cool to display some sort of special icon in the server list for those verified game servers that allow tracking of game stats. I guess if such servers are full, locked or private, the corresponding icon should override this new one.

**Comment by IceflowRE** [comment]
What about use an overlay on the right bottom, like this: https://exablaze.com/img/statistics.png

**Comment by qreeves** [comment]
Added the code and place-holders for this one, just needs a real icon I guess.

**Comment by IceflowRE** [comment]
https://drive.google.com/folderview?id=0B__JdfXlvXlxdXF2S255YVhqcG8&usp=sharing

**Comment by bonifarz** [comment]
While these stats icons are really nice, I once again realize how small the icons in the servers menu are. We always used them as part of the guitext, so the height is that of one text line. For the new overlay, that leaves just a few pixels :smile: 

We could use guiimage instead, but then the non-square shape will need a bit of negative guistrut, which is no problem, as it is in a guimerge. Here's snapshot for you to compare the icon as an image and as part of the text. I've chosen option c) for this.
![servers](https://cloud.githubusercontent.com/assets/10864175/15626483/00ed6fc0-24c6-11e6-80d5-e5dea9b3e5b5.jpg)

Side note: When i put the server's guiimage in a guinoskinfx (the hover looks really bad on the rectangular shape!), it messes up the body to the right, even though it is not in that block. No clue what's going wrong there.

**Comment by qreeves** [comment]
Did anything come from this?

**Comment by IceflowRE** [comment]
Iam there if you need some other icons previews or so.

**Comment by bonifarz** [comment]
I guess this one is also a design decision: How do you want this menu to look like, and what resources to you really need for that.

**Comment by qreeves** [comment]
This is being worked on in the `newui` branch.
