### ISSUE TITLE
Continuous resource failure messages

### ISSUE THREAD

**Issue by qreeves** [red-eclipse/base#5]
From: http://redeclipse.net/forum/viewtopic.php?f=9&t=143

If a model or texture can't be found, the client continually tries to reload it every time.

This has two effects:
1. It's extra load that isn't needed.
2. Because the event log and chat log are tied together for maximum number of messages, if something requests something every frame (say... models/vanities/chestplate/mesh.md5mesh), it clears the chat log out, often before one can read a message.

Suggested fix is two part:
1: Save failed loading attempts in memory and don't do them again.
2: Separate the event (kills, caps, etc) log from the chat log.

**Comment by artost** [comment]
I noticed the issue in 1.4, but not in 1.5. It may have been fixed.

**Comment by IceflowRE** [comment]
Yes, it isnt already existing.
