### ISSUE TITLE
[enhancement] edit: find ents - attributes

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#50]
At the moment if you want to search ents, all attributes are on with "0" but its not usefull, because its more often that you need them off or only some on with some other parameters. So its more usefull to turn them on default off.

**Comment by qreeves** [comment]
The description you've supplied makes no sense. You are also not following Issue Tracker guidelines. You must post suggestions in the forums and discuss with the community before flooding my issues with stuff like this.
