### ISSUE TITLE
prefebpreview single cube pivot

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#500]
This is just a small detail, and I'm not even sure if it is a bug or intended.
When a prefab is larger than its grid size for pasting, the preview is centered perfectly fine.
But if you try a prefab that uses this grid size as a bounding box, the preview is off center.

**Comment by qreeves** [comment]
Demonstration screenshots/video?

**Comment by bonifarz** [comment]
Related forum topic: http://redeclipse.net/forum/viewtopic.php?f=4&t=966
The prefabs attached in the first post demonstrate this pretty well. 

`/showgui geometry 2` and you'll see what I mean.
![offcenterprefabpreview](https://cloud.githubusercontent.com/assets/10864175/15625906/60a7ed32-24b7-11e6-8b34-130b39a064ab.jpg)

**Comment by acerspyro** [comment]
This menu no longer exists. Closing.
