### ISSUE TITLE
Filter for modified values in variables menu

### ISSUE THREAD

**Issue by qreeves** [red-eclipse/base#502]
Along with the other filters we have, in order to easily allow people to scan what vars are changed on a server it would be useful to have another filter which only shows modified values for easy scanning.

**Comment by bonifarz** [comment]
Agreed. This would be more useful than the "advanced" filters, so checkbox for this could go somewhere in the top panel.

**Comment by acerspyro** [comment]
What variables menu? :P

Closed. Will re-open if another variable menu comes into our plans for the future again.
