### ISSUE TITLE
Entities having wrong position

### ISSUE THREAD

**Issue by FaTony** [red-eclipse/base#503]
Sometimes entities are in the wrong place. So far I've seen only spawn points and affinities do that. I have the demo but GitHub doesn't want to upload it.

**Comment by shirepirate** [comment]
i've only seen this happen in the 1 map so far, rooftop, when i was playing with you. are you saying it's a repeat occurance?

**Comment by FaTony** [comment]
It happened on train with spawn points and on spacestation with affinities.

**Comment by shirepirate** [comment]
probably /crclock was off causing map desync. anyway, if you can't find a way to reproduce it i'll close the issue.

**Comment by FaTony** [comment]
No, the affinities never were in places that the bomb spawned. It is a real issue.

**Comment by bonifarz** [comment]
Maybe it is a good idea to describe and discuss this in more detail on the forums, where you can attach your dmo record.

**Comment by FaTony** [comment]
Done: http://redeclipse.net/forum/viewtopic.php?f=7&t=978

**Comment by shirepirate** [comment]
can't reproduce it, and you seem to have only the one example. the bombs spawned at the base or bottom of the bomberball set affinity, rather than the center (not a random spot). if you can find a way to reproduce it the issue can be reopened, but it was probably a fluke.
