### ISSUE TITLE
Installation .tar.bz2 archive v1.5.3 for GNU/Linux missing some binaries

### ISSUE THREAD

**Issue by Zujalich** [red-eclipse/base#505]
The Red Eclipse archive for Linux "redeclipse_1.5.3_nix.tar.bz2"
with MD5 Hash 43bcf7941c9eccafe8173dd706feb373
is missing Linux binaries, while it contains some of the OS X ones (/bin/redeclipse.app/).

This is not really an issue while running the game on a computer with an active Internet connection because the script redeclipse.sh at the first run downloads them and updates all.

I run in this issue while running Red Eclipse for the first time on a Linux system (which had some temporary connectivity problems for some reason) getting the error:
```
$ ./redeclipse.sh
Checking for updates to "stable". To disable set: REDECLIPSE_BRANCH="inplace"
branch: stable
folder: /home/user/games/redeclipse-1.5.3_nix
cached: /home/user/.redeclipse/cache/stable
---SNIP---
bins: 05297ccd841a3dd83614ffaa7c14a386d339a112 is installed.
bins: Failed to retrieve update information.
Unable to find a working binary.
There was an error running Red Eclipse.
$
```

Doing a diff on extracted redeclipse_1.5.3_nix.tar.bz2 and redeclipse_1.5.3_combined.tar.bz2 archives:
```
$ diff -r redeclipse-1.5.3_nix/ redeclipse-1.5.3_combined/
Only in redeclipse-1.5.3_combined/bin/amd64: redeclipse.exe
Only in redeclipse-1.5.3_combined/bin/amd64: redeclipse_linux
Only in redeclipse-1.5.3_combined/bin/amd64: redeclipse_server.exe
Only in redeclipse-1.5.3_combined/bin/amd64: redeclipse_server_linux
Only in redeclipse-1.5.3_combined/bin/redeclipse.app/Contents/MacOS: redeclipse
Only in redeclipse-1.5.3_combined/bin/redeclipse.app/Contents/MacOS: redeclipse_universal
Only in redeclipse-1.5.3_combined/bin/redeclipse.app/Contents/Resources: redeclipse.icns
Only in redeclipse-1.5.3_combined/bin/redeclipse.app/Contents/Resources: redeclipse.sh
Only in redeclipse-1.5.3_combined/bin/x86: redeclipse.exe
Only in redeclipse-1.5.3_combined/bin/x86: redeclipse_linux
Only in redeclipse-1.5.3_combined/bin/x86: redeclipse_server.exe
Only in redeclipse-1.5.3_combined/bin/x86: redeclipse_server_linux
$
```

This could be a real blocker for people wishing to try Red Eclipse offline, with slow connection or no Internet connection.

**Comment by qreeves** [comment]
Seeing as we're releasing 1.5.5 soon anyway, I won't bother to redeploy 1.5.3.
