### ISSUE TITLE
More Modern Gamemodes (Gmod inspired)

### ISSUE THREAD

**Issue by alugarius** [red-eclipse/base#513]
I started to play funny gamemodes like prop hunt and Hide and Seek in gmod, 

I imagined that these modes would be very cool to have in RE!

The sense of adding addictive gamemodes: Make RE more popular and interesting for youtubers and other players.

**Comment by qreeves** [comment]
This is an issue tracker, not a discussion forum for feature suggestions. Please see http://redeclipse.net/forum
