### ISSUE TITLE
getmap required to fetch a server map

### ISSUE THREAD

**Issue by shacknetisp** [red-eclipse/base#522]
When fetching a server map on a non-edit server, everyone who did not have the map needed to run /getmap. They were stuck at "requesting map" before.

**Comment by qreeves** [comment]
Need more information.

**Comment by shacknetisp** [comment]
Players who did not have the map were stuck at the "requesting map" stage and were only able to fetch the map by using /getmap.
The map was in the server's maps directory as well as one of the player's maps directory.
This apparently only occurs outside of editing mode, map sending in editing mode works without the extra /getmap step.

**Comment by qreeves** [comment]
Did the server get past the initial pre-round phase still (eg. game starts, timelimit starts to count down, people can spawn etc)? Did it end up picking the player or server map? [this is why demos help]

**Comment by shacknetisp** [comment]
Here's a demo where I don't automatically receive a player map.
I join the game in this demo a little after the 3:50 mark and don't receive the map until I run /getmap.

[getmap_problem.dmo](http://beha.zapto.org/files/demos/getmap_problem.dmo)

**Comment by shacknetisp** [comment]
Here is another demo, where players don't receive a server map without /getmap:
[getmap_problem2.dmo](http://beha.zapto.org/files/demos/issues/getmap_problem2.dmo)
