### ISSUE TITLE
[1.5.5] Build error on Ubuntu 16.04 amd64

### ISSUE THREAD

**Issue by ckorn** [red-eclipse/base#526]
## Have you verified that you can reproduce the problem? [Y/N]
Y

## Have you checked on the forums or issue tracker to see if your issue has already been reported and/or resolved upstream? [Y/N]
Y

## Provide a good description along with a link to your original forum topic (if applicable).
On Ubuntu 16.04 the build failes on the amd64 architecture. The i386 architecture succeeds.
/usr/bin/ld: support/sqlite3.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
support/sqlite3.o: error adding symbols: Bad value

## Attach, or provide direct links to, any files which demonstrates your issue and any patches you might have here.
Here is the complete build log:
http://zulu309.server4you.de/build/logs/redeclipse_1.5.5-1~getdeb1-amd64-20160630-2319

**Comment by TheAssassin** [comment]
I cannot reproduce this problem. I have built Red Eclipse in a fresh Docker container running 16.04, but it works as expected.

Have you actually tried adding `-fPIC` in the Makefile in line 6 (after `CXXFLAGS?= -O3 -fomit-frame-pointer -ffast-math`), as your compiler suggests to you?

Just in case: My compiler version:
```
root@99b8a873a720:~/redeclipse/src# g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.3.1-14ubuntu2.1' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2.1) 
```

**Comment by qreeves** [comment]
Did you `make clean` before switching architectures?

**Comment by TheAssassin** [comment]
@qreeves: Since the log is about a amd64-only build, I am very sure this does not apply to @ckorn's situation.

**Comment by ckorn** [comment]
Nevermind, the system lib of sqlite3 works. So I let RE link against that one.

If all goes well, soon to be published on playdeb.net ;)
