### ISSUE TITLE
The WPT file is not renamed when renaming the map

### ISSUE THREAD

**Issue by FaTony** [red-eclipse/base#528]
If you rename the map in edit mode, all files are renamed except the wpt file. I think it should be renamed too.

**Comment by bonifarz** [comment]
This was not the case in earlier versions either, was it? I mean, with rename, you mean savemap, that does not save waypoints, right?

**Comment by FaTony** [comment]
Right. I've actually lost waypoints several times when I forgot to save them. Really annoying.

**Comment by IceflowRE** [comment]
So at least savemap should save the waypoints too?

**Comment by FaTony** [comment]
I think savemap should do this. I don't see a point of saving the map without waypoints.
