### ISSUE TITLE
First blood/headshot/carnage signs are not displayed

### ISSUE THREAD

**Issue by FaTony** [red-eclipse/base#529]
Pretty self-explanatory. Confirmed by several people.

**Comment by qreeves** [comment]
Above head or on the HUD?

**Comment by shacknetisp** [comment]
Both, I don't see the firstblood or headshot texture anywhere, only the flashing text in the obituary.

**Comment by zaquest** [comment]
I see above head icons, but not on the hud. It seems that code for displaying it on the hud was removed [here](https://github.com/red-eclipse/base/commit/e020aacdb69f4dedebff90eefd19f489586bd351#diff-bedb77d00b027320990fbe0691024b98L1683) and never restored.

**Comment by FaTony** [comment]
Now they are rendered incorrectly: http://redeclipse.net/forum/viewtopic.php?f=7&t=1001

**Comment by FaTony** [comment]
Still not centered: http://redeclipse.net/forum/viewtopic.php?f=7&t=1001&p=9137#p9137
