### ISSUE TITLE
Incorrect rendering of water when it touches skybox

### ISSUE THREAD

**Issue by Lyberta** [red-eclipse/base#532]
When water touches skybox it renders incorrectly. The parts of skybox inside the water glitch.

**Comment by qreeves** [comment]
Not enough information.

**Comment by Calinou** [comment]
This is a longstanding bug in Cube 2 games: whenever water refraction is enabled and water touches the map border (leaving the skybox visible), a "hall of mirrors" effect is created. This can be solved (with a very small performance cost, in my tests) by using `/refractsky 1` in Sauerbraten (this is a map variable, I'm not sure if it's in Red Eclipse, too).

**Comment by FaTony** [comment]
Screenshot here: http://redeclipse.net/forum/viewtopic.php?f=7&t=998

**Comment by FaTony** [comment]
Yeah refractsky 1 mostly fixes it but there are HoM glitches at the very edge of the water.

**Comment by qreeves** [comment]
This is possibly due to using `vertwater` without properly occluding the corners of the water with geometry.
