### ISSUE TITLE
textkeyimages 0 renders incorrectly

### ISSUE THREAD

**Issue by FaTony** [red-eclipse/base#533]
Screenshot here: http://redeclipse.net/forum/viewtopic.php?f=7&t=1000

**Comment by zaquest** [comment]
I have similar issue, but for me it's because of missing textures for some keys in `data/textures/keys`. For example textures for keys `ralt`, `lalt`, `leftbracket`, `rightbracket` are missing. There's texture for `return` so it might be something different.
