### ISSUE TITLE
Edit mode: at first time weapons doesnt spawn

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#535]
#### Have you verified that you can reproduce the problem? [Y/N]
Y

#### Have you checked on the forums or issue tracker to see if your issue has already been reported and/or resolved upstream? [Y/N]
Y
#### Provide a good description along with a link to your original forum topic (if applicable).
In edit mode already places weapons want spawn until you clicked them in edit mode, then they spawn immediatly. Else not.

**Comment by qreeves** [comment]
Online, offline, or both?
