### ISSUE TITLE
uifade causes flicker

### ISSUE THREAD

**Issue by Robalni** [red-eclipse/base#536]
If the variable uifade is anything except 0 then some of the ui will flicker, like the server list (see [this video](http://www.robalni.org/redeclipse/uifade.webm)).

The problem can be in this line of code:
    gle::colorf(r, g, b);
in src/game/hud.cpp at line 828 in function drawblend, because it works (looks like after I set uifade to 0 in the video) when i comment it away or change it to gle::colorf(1, 1, 1);.

This function _drawblend_ is called by _drawhud_ at src/game/hud.cpp:3495

I'm using commit 4d121eb42d345245b692385506425e224115dcd3

Graphics info from log.txt:
renderer: Gallium 0.4 on AMD RV730 (X.Org)
driver: 3.3 (Core Profile) Mesa 10.3.2

Operating system: Debian 8.5 (Jessie)

**Comment by qreeves** [comment]
I think this might be caused by clearing the colour buffer every frame. It was done in attempt to fix a skybox HOM glitch but it seems to have caused other issues.

**Comment by qreeves** [comment]
Is this improved in latest stable?

**Comment by Robalni** [comment]
No, I still have this problem.

**Comment by graphitemaster** [comment]
This maybe should be closed because of newui?

**Comment by graphitemaster** [comment]
Okay so uifade still exists but it doesn't appear to do anything anymore?

**Comment by Robalni** [comment]
This bug does not happen anymore with the new ui.
