### ISSUE TITLE
sv_timelimit is not taking effect.

### ISSUE THREAD

**Issue by shacknetisp** [red-eclipse/base#538]
I have sv_timelimit set to 0 in the servinit.cfg, but it does not apply, instead the default 10 minutes is used.
Here is a game where that happens:
[timelimit_problem.dmo](http://beha.zapto.org/files/demos/issues/timelimit_problem.dmo)

**Comment by shacknetisp** [comment]
Oh, completely missed that there's a new variable `timelimitrace`

**Comment by qreeves** [comment]
Yeah, a few variables are now mode specific.
