### ISSUE TITLE
I can't use all my mouse buttons

### ISSUE THREAD

**Issue by Robalni** [red-eclipse/base#541]
On my mouse there are two buttons that get number 8 and 9 in SDL. I can't use these buttons for two reasons:
1. config/keymap.cfg doesn't list mouse buttons higher than 7
2. The _checkinput_ function in src/engine/main.cpp only looks at some mouse buttons

One way to solve this could be to replace the _switch_ starting at line 653 in main.cpp by this line:
`processkey(-event.button.button, event.button.state==SDL_PRESSED);`
or if that causes problems we could just add a default to the switch with that line.

Then I could just add these lines to my autoexec.cfg to make the mouse buttons work:

```
keymap -8 MOUSE8
keymap -9 MOUSE9
bind "MOUSE8" [showcompass voice]
bind "MOUSE9" [showcompass team]
```

One solution could be to also add:

```
keymap -8 MOUSE8
keymap -9 MOUSE9
```

to config/keymap.cfg but it feels weird to have a list with mouse buttons like that because we don't know how many mouse buttons people have. What if someone has a MOUSE10? Could we instead make the game automatically find all the mouse buttons and keymap them?

I'm using commit fd3d59480cb6f88bad6feaf1ce4b75b3b9ea5cb0

**Comment by IceflowRE** [comment]
Same issue, here, but the hardware mouse7 button is not recognized too.
If you have a mouse where you can set the mouse button to an other key (e.g. Mouse7 to "H" then he can get it, but not if Mouse7 or higher is another mouse key :D ).

**Comment by Robalni** [comment]
This makes it possible to bind the mouse buttons but I still can't use them and I think it's because the game doesn't check those buttons in engine/main.cpp at lines 653-660. I think a default line to that switch would fix it.

**Comment by qreeves** [comment]
The fix added may not work, as it seems SDL only defines 5 buttons: 
```
#define SDL_BUTTON_LEFT     1
#define SDL_BUTTON_MIDDLE   2
#define SDL_BUTTON_RIGHT    3
#define SDL_BUTTON_X1       4
#define SDL_BUTTON_X2       5
```

**Comment by Robalni** [comment]
It works for me now, thanks!
