### ISSUE TITLE
Setting RGB 000 does yellow instead black

### ISSUE THREAD

**Issue by n0zing** [red-eclipse/base#543]
Well, it just like as is

I managed to customize player model, and have found that small issue

**Comment by bonifarz** [comment]
I think what you found is a semi-official feature that we did not document (yet): 
If the profile color is set to zero, it will take the color of any weapon that you are currently wielding (e.g. yellowish for the claw in the preview). 
If you want black, you can take a similar hex value, such as 0x010101.

**Comment by bonifarz** [comment]
I'll think about adding a clue for this in the menu, maybe a tooltip, since there is not much space for longer explanations.
