### ISSUE TITLE
Sometimes you have to scroll the server browser to join

### ISSUE THREAD

**Issue by FaTony** [red-eclipse/base#550]
It usually happens to the servers on the bottom half. When you click on them, they warp upwards and you have to scroll up to join.

**Comment by freezurbern** [comment]
I'm unable to reproduce this on stable (not enough servers to do it on master), here's what I tried:

1. Open server browser
2. Wait for all servers to respond
3. Scroll down to just above incompatible servers
4. Click the last (second to last, etc.) server
5. Game connects to selected server as expected

**Comment by shacknetisp** [comment]
I've experienced this a few times, I click on a server, it goes out of view, and I have to scroll to it before it begins to connect.  I don't have a method of reproducing it however.

**Comment by FaTony** [comment]
This is usually happens when servers are sorted incorrectly. When you click on such server, it is re-sorted to the correct position and you have to scroll to connect.
