### ISSUE TITLE
Add option to revert "You are holding flag/bomb" messages to the bottom half of the screen

### ISSUE THREAD

**Issue by Lyberta** [red-eclipse/base#556]
Previous versions had these messages at the bottom. Now they are at the top which makes it too crowded. I want to revert.

**Comment by graphitemaster** [comment]
Since newui is scriptable this should be possible for anyone to change to their liking. It's more a question of if we want to support some sort of standard layouts as presets which you can chose from, either case that should probably be a new issue?
