### ISSUE TITLE
player model opression

### ISSUE THREAD

**Issue by graphitemaster** [red-eclipse/base#557]
The male and female character models are alright except this could be opressing some other players which identify as an apache attack helicopter.

I think this would work well for their needs
http://www.turbosquid.com/3d-models/apache-attack-helicopter-3d-obj/513078

**Comment by FaTony** [comment]
Troll.

**Comment by acerspyro** [comment]
@graphitemaster Thank you for your input. The Red Eclipse Team values equality over everything else.

A few releases ago, we have added a propeller vanity to represent the heligender properly in the game.

You can enable it by going to Profile > Vanity Items and selecting Scalp, followed by Propeller, as seen below:

![image](https://user-images.githubusercontent.com/4400999/33864872-ca3c41e2-debc-11e7-8473-1a2e3ea7b8d6.png)

You can now save your changes and return to the game to show your beautiful true gender to the world!

We are actively taking steps to end heliophobia once and for all, and we hope to satisfy all our heliosexual players.

**Comment by acerspyro** [comment]
Troll.
