### ISSUE TITLE
No warning when closing profile menu

### ISSUE THREAD

**Issue by qreeves** [red-eclipse/base#560]
Reviewing a number of YouTube videos, it has come to my attention people are pressing the red 'X' at the top right after making changes to their loadout, etc. which loses their selection. There should either be a warning/check, or a larger/more obvious (and universally applied) effect for important buttons.

**Comment by bonifarz** [comment]
Since the close button or Esc takes you to the previous menu, we could just put one menu between main and profile, with a short note about the OK / cancel buttons? Maybe we could list all profile/preview diffs there as well.

**Comment by graphitemaster** [comment]
Wouldn't it make more sense to just maintain the selection on every change within the loadout menu? Is there a reason changes made in the menu are deferred until they accept the changes?

**Comment by bonifarz** [comment]
Good question. For the profile colour's rgb sliders and the vanity selection, a preview with an ok button is very reasonable. I'm not sure about the loadout weapons. But my lazy fix does not apply to opening the loadout tab via the COMMA default bind. Which is maybe okay, so you can get out more quickly when opening it by mistake :wink:
