### ISSUE TITLE
Reduce tooltip delay

### ISSUE THREAD

**Issue by coornio** [red-eclipse/base#563]
It's rather straightforward. Currently they take roughly 500ms to become fully opaque, i suggest dropping the delay closer to 200ms. No one likes waiting for a tooltip to come fully into view :)

**Comment by bonifarz** [comment]
You can change this already client side using the variable *guitooltipfade*.
Changing the default value (indeed 500ms) will be trivial, it's here:
 https://github.com/red-eclipse/base/blob/master/src/engine/ui.cpp#L45

**Comment by coornio** [comment]
Of course i could, but i was calling for a change of the default value rather than personally customizing it to my liking. It's just way too high by default. Personal opinion of course but not invalid in the least

**Comment by IceflowRE** [comment]
Please discuss further in our forum redeclipse.net/forum .

**Comment by bonifarz** [comment]
Well, I don't think this is such a big deal to discuss. Seems reasonable to me, but it's not my decision. I just pointed at the vars, since it may take a while until the next update to stable.

**Comment by coornio** [comment]
Exactly my point, I didn't figure it was anything worth poking the whole community over since no one really pays attention to things like this except for, well, people like me. I like picking at the little things :p 

Ultimately it's up to @qreeves to decide if he wants to go along with it, but, imo, it's kind of a no-brainer :)

**Comment by qreeves** [comment]
I agree with the change, everyone else is just unfamiliar with you and we've got a procedure to follow regarding the issue tracker that states all proposals should be discussed on the forum before a ticket is made. This is rather trivial though and I trust you not to propose major changes without following the procedure, so it's ok.

**Comment by coornio** [comment]
Thanks quin. And don't worry, if i find anything "important" i'll be sure to follow the highway ^^

**Comment by graphitemaster** [comment]
I would imagine this is fixed in the newui @qreeves

**Comment by qreeves** [comment]
Yeah, this is 250ms in the newui version.
