### ISSUE TITLE
Make gsp mutator filter work only with specified gamemode

### ISSUE THREAD

**Issue by Lyberta** [red-eclipse/base#568]
So I'm making a map which supports attack bomber ball and I want to have specific affinities to be turned on and off for this specific gamemode. Now making affinity that turns on is simple: mode: bomber ball, mut: gsp3. But making affinity that turns off is not possible because filter "not gsp3" disables the affinity in protect CTF. I suggest gsp mutator filter to only apply to the mode that is selected for this affinity. So to disable an affinity in attack bomber ball I would just use: "mode: not bomberball, mut: not gsp3".

**Comment by bonifarz** [comment]
I had similar thoughts when modding maps for gladiator games. The conventions can be confusing, and the options are limited.

In your example, you want the affinity in all modes but attack-bb, right? Does it work if you enable *all* other modes and muts? E.g. *$mutsbitall $mutsbitgsp3* = 131071, *$modebitall - $modebitbomber* = 95?

**Comment by FaTony** [comment]
Where are these constants defined and how to use them?

**Comment by qreeves** [comment]
What people typically do is create separate entities designed for the modes they intend. You can have more than one entity in exactly the same spot. It isn't pretty, I know, but this is more an issue with how I implemented the game specific mutators to save space, not with how the mode/mut attributes filter (because that's what they are, just a filter, not a definition).

**Comment by FaTony** [comment]
Then make a global "not" parameter that will reverse the mode/mut combo.

**Comment by bonifarz** [comment]
Let me get this straight:
- flag > 0 : any of these, *A or B or C...*
- flag < 0 : none of these, *not (A or B or C ...)*
- flags for mode and muts are connected with *and*

So, if you want to disable the affinity for attack-bb, duplicate it, make one of them *bomber-not-gsp3*, make the other one *not-bomber*. Or does this contradict with other mode criteria you want to apply?

**Comment by FaTony** [comment]
I guess it works.

**Comment by qreeves** [comment]
Is that OK or do we need some finer controls on it?

**Comment by FaTony** [comment]
I'd prefer not having gsp, but I separate mutator for each mode specific mut.

**Comment by qreeves** [comment]
OK, I'll leave this one here for consideration. Might be a clusterfuck to do, but it might be best in the end.

**Comment by FaTony** [comment]
How many bits does mutator value have? 32? Can RE entities have 64 bit properties?

**Comment by bonifarz** [comment]
atm there are about 18+13 muts, so that should not matter right now.
Don't know if it's worth the effort to disentangle the gsp.
