### ISSUE TITLE
Follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by Lyberta** [red-eclipse/base#572]
Currently, Red Eclipse puts everything in ~/.redeclipse which contributes to a lot of clutter. XDG Base Directory Specification tries to solve this problem by defining environment variables which define where programs should store their data.

**Comment by graphitemaster** [comment]
Note if we're using SDL2 (I think we are now) There is a function `SDL_GetPrefPath` which follows the proper convention on all platforms. Unfortunutely it takes two arguments `org` for organization and `app` for the application name. This leads to pathnames like `~/.local/share/<organization>/<application>`. It would be nice if you can just supply `NULL` for one of the arguments but you cannot. The trick I use is to call it like `SDL_GetPrefPath("redeclipse", "")` which would yield something like `~/.local/share/redeclipse//`. Then you can just remove the last `/` from the path with `strrchr`.

**Comment by FaTony** [comment]
Note that not all data should go into `XDG_DATA_DIR`. Some config files should go into `XDG_CONFIG_DIR` and autoloaded maps should go into `XDG_CACHE_DIR`.

**Comment by graphitemaster** [comment]
I disagree with going all out on following the XDG stuff like that. I don't know of anyone who actually does to be honest. The preferred path technique is pretty damn straight forward and these more exotic directory specifications are political masturbation.

**Comment by FaTony** [comment]
Here's the list of apps using XDG: https://wiki.gnome.org/action/show/Initiatives/GnomeGoals/XDGConfigFolders?action=show&redirect=GnomeGoals%2FXDGConfigFolders

The point here is to separate data by the type so the user can easily understand the prpose of different files. For example, they can safely empty the XDG_CACHE_HOME to free some disk space.

**Comment by graphitemaster** [comment]
Redeclipse isn't part of GNOME. Look closely at that initiative. It clearly states `GNOME Goals`. One can argue that all applications should adhere to that specification but that is purely a Free Desktop ORG specification (which has been updated to included that cache path and the other crap, the first iteration of the XDG home directory didn't have any of those additional subdirectories.) I agree we should be using the `XDG_DATA_DIR`, which is what `SDL_GetPrefPath` will give us.

**Comment by TheAssassin** [comment]
Has any of you actually tested if the `XDG_DATA_DIR` (or, according to the GNOME document @FaTony referenced, `XDG_DATA_HOME`) variables exist in your environment?
On my XFCE system, I can see some variables prefixed with `XDG_` but none of the ones you want to use.
I wonder how that would work if these variables are not set.

But besides that, I agree that the data should be moved to some other directory. My home directory  is quite of a mess of hidden directories.

**Comment by shacknetisp** [comment]
`SDL_GetPrefPath` will work without the appropriate XDG variables, it will fall back to `$HOME/.local/share/`

**Comment by FaTony** [comment]
@TheAssassin XDG specifies default values if variables are not defined.

**Comment by TheAssassin** [comment]
Well I think `SDL_GetPrefPath` is the solution to use then, as `~/.local/share` looks like what we should use according to the XDG specs, too. Splitting up the current `.redeclipse` directory contents on three different directories will be too annoying to maintain.

**Comment by TheAssassin** [comment]
So I just started implementing this feature, and encountered a problem: When using `SDL_GetPrefPath`, the server would need to depend on SDL2, too, to be able to resolve the home directory. I am not sure whether it's worth adding this dependency just to implement this feature.

**Comment by TheAssassin** [comment]
@qreeves just confirmed my assumption that this would be a bad idea. Therefore we reject this feature request.
