### ISSUE TITLE
Lots of bugs caught by Valgrind

### ISSUE THREAD

**Issue by Lyberta** [red-eclipse/base#573]
I wanted to debug the crash with the latest git version so I've run it under Valgrind. To my surprise, it started spamming errors so I've run the server for only about 30 seconds. Here are the errors with backtraces:

Conditional jump or move depends on uninitialised value(s)
    game.h 568
    game.h 558
    server.cpp 280
    server.cpp 399

Use of uninitialized value of size 8
    stream.cpp 1035
    server.cpp 2531
    server.cpp 5658

Conditional jump or move depends on uninitialised value(s)
    stream.cpp 1032
    server.cpp 2501
    server.cpp 2535
    server.cpp 5658

Conditional jump or move depends on uninitialised value(s) / Use of uninitialized value of size 8
    stream.cpp 1032
    server.cpp 2502
    server.cpp 2535
    server.cpp 5658

Conditional jump or move depends on uninitialised value(s)
    server.cpp 362
    server.cpp 4853
    server.cpp 2913
    aiman.h 319
    aiman.h 409

Syscall param write(buf) points to uninitialized byte(s)
    stream.cpp 726
    stream.cpp 1014
    stream.cpp 1031
    stream.cpp 2501
    server.cpp 2508
    server.cpp 440
    Address 0x73213d6 is 198 bytes inside a block of size 4096 alloc'd
    stream.cpp 726
    stream.cpp 791
    stream.cpp 866
    stream.cpp 1241

Syscall param write(buf) points to uninitialized byte(s)
    stream.cpp 726
    stream.cpp 1014
    stream.cpp 1031
    stream.cpp 2501
    server.cpp 2508
    server.cpp 440
    Address 0x630fc66 is 4086 bytes inside a block of size 16386 alloc'd
    stream.cpp 860
    stream.cpp 1241
    server.cpp 2518

Use of uninitialized value of size 8
    stream.cpp 1032
    server.cpp 2502
    server.cpp 2508
    server.cpp 5554

Conditional jump or move depends on uninitialised value(s)
    stream.cpp 903
    stream.cpp 927
    stream.cpp 785
    stream.cpp 786
    server.cpp 2486

**Comment by graphitemaster** [comment]
Valgrind information like this is basically unusable since you did what appears to be a debugless run in Valgrind. The memory checker typically spits out information regarding not just the file and line, but the function, and even shows in the output the code that caused it. It's safe to ignore basically anything involving `write` systemcalls with uninitialized data. This is one glibc and it does it everywhere, common false positive.

**Comment by FaTony** [comment]
You can open the file, scroll to mentioned line and see what's going on. I could dump the raw XML but it's huge.

**Comment by graphitemaster** [comment]
Every single one of the uninitialized warnings is from the lack of zeroing out arrays in the structures. They are valid and there are even places in the constructors of these structures which do zero out some of the arrays. These are bugs.

**Comment by graphitemaster** [comment]
Closing this because the issues that this reports have largely changed over time. Valgrind is still reporting issues in other areas so a new issue should be reported for those instead.
