### ISSUE TITLE
/viewtype 1 (side-by-side) seems broken

### ISSUE THREAD

**Issue by TheLastProject** [red-eclipse/base#575]
**First seen in**:
Stable version 1.5.5 (probably existed earlier, although 1.4.5 is fine)

**Observation**:
In 1.5.5, the side-by-side option seems to not render properly.
![2016-08-25-220458_1360x768_scrot](https://cloud.githubusercontent.com/assets/1885159/17984655/7d9e08f8-6b12-11e6-8a56-6ce85f87c675.png)
In 1.4.5, this worked fine:
![2016-08-25-222034_1360x768_scrot](https://cloud.githubusercontent.com/assets/1885159/17984678/92380b10-6b12-11e6-8213-ad2583edcd51.png)

I'm running nouveau, but @shacknetisp reported this on the free AMD drivers too.

**How to reproduce**:
Open the console and run /viewtype 1
Alternatively, go to Options, then graphics, then 3Dfx and click side-by-side.
... 

I searched the issue list and checked that this is not a duplicate :white_check_mark: 
I tried to rename my _config.cfg_, and the problem also occurs with default settings :white_check_mark:

**Comment by shacknetisp** [comment]
`viewtype 2` also displays this.

**Comment by acz13** [comment]
just asking, what is the point of this???

**Comment by shacknetisp** [comment]
[It is for stereoscopic viewing](http://redeclipse.net/forum/viewtopic.php?f=4&t=423#p8400).

**Comment by acz13** [comment]
Just tested using 1.5.3, viewtype 1 and 2 work fine

this seems to be related to the switch between SDL1 and SDL2

**Comment by lsalzman** [comment]
https://github.com/red-eclipse/base/commit/e2ccf5333555566c68a2c4bf87eaae5037273d95

**Comment by acz13** [comment]
time to close this issue?

can confirm master works (as expected)
