### ISSUE TITLE
usage line: fields of aliases

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#576]
When you enter an alias in the console, for example `/ctf` or `/insta`, the **usage:** line does not show the args (fields from _usage.cfg_), but just <value>.

I guess it's this, https://github.com/red-eclipse/base/blob/master/src/game/hud.cpp#L1956

Side note: I don't think we have any aliases for bitfield variables, so this should not be a problem.

**Comment by qreeves** [comment]
Yeah, when we first added the arguments we didn't have that list, and because aliases don't have predefined arguments like built-ins there wasn't any information to really show before.

**Comment by graphitemaster** [comment]
I suppose what you could do is check if the alias aliases a builtin `ICOMMAND` and then return the argument list thusly.

**Comment by graphitemaster** [comment]
I actually implemented this for fun but noticed that it doesn't really make sense unless you parse the alias and make sense of the argument order.

For instance imagine an command `bar` which takes three arguments `int, float, string` and then you have an alias `foo` such that it's constructed like so
```
foo = [ bar $arg2 $arg1 "constant" ]
``

If you simply supply the arguments from "bar" as the usage for "foo" then the
result is clearly wrong as `foo` only needs two arguments; furthermore it has the first and second argument swapped.

So parsing the contents of the alias is required to make sense of argument order and when they show up. It's even more troublesome for usages of `@` where the result of an expression can be used which can then form the argument lookup. Take `@[arg$arg1]`for example.

The best you can do is effectively ignore the more complex cases and just parse for instances of "($|@)argN" and remember the order, such that you can index the fields in correct order when assembling the usage string.

**Comment by qreeves** [comment]
We can just source them from usage.cfg. - don't worry about it lol.

**Comment by bonifarz** [comment]
Yes, that's exactly what I had in mind. For some aliases, we have detailed usage instructions, with a list ("field") of argument names that match the description text.
