### ISSUE TITLE
Joining a game is confusing

### ISSUE THREAD

**Issue by graphitemaster** [red-eclipse/base#577]
When you're thrown into a spectator mode, typically when joining a server or game after picking your loadout; SpecTV tells you to `press  to join game`. There is a very obvious whitespace there inbetween `press` and `to`. I generally presumed it was space character (so space bar).

![SpecTV](http://i.imgur.com/GBMbYal.png?1)

Though that doesn't actually work. I must be doing something incredibly wrong because I pressed every single key on my keyboard and mouse to join a game and couldn't. The only way I can join a game is to bring up the team select option with `F7` and pick a team (Which causes a join somehow). But even that doesn't always gurantee you'll join a game (if the loadout is not selected correctly for instance it silently just brings up the loadout menu again)

This is actually really confusing from a user input perspective, especially for new comers. I was almost sure I broke something.

**Comment by qreeves** [comment]
Delete your ~/.redeclipse/config.cfg - it has stale binds in it.

**Comment by graphitemaster** [comment]
This _is_ a fresh configuration. I deleted it again, problem still persists.

**Comment by bonifarz** [comment]
This tip should display key icons. I just tried `/echo dobindsearch [spectate 0] spec` and that works fine, it displays `data/textures/keys/mouse2.png` and whatever other keys are used to spawn.

**Comment by bonifarz** [comment]
Ah, I think in https://github.com/red-eclipse/base/blob/master/src/game/hud.cpp#L1650 `spectator` should be `spectate`.

Though, that does not explain why you could not join. A few days ago, another player complained about being unable to spawn for a while. I don't have a dmo, though.

**Comment by graphitemaster** [comment]
What is the default spectate key anyways? It could be related to my keymap file.

**Comment by bonifarz** [comment]
It should display the keys now correctly (at least it does now for me). Default key to enter spec mode is Home, and for leaving spec mode it's any of right-click, End or E.

**Comment by graphitemaster** [comment]
Yeah I did not try Home or End, E works but didn't work for me before. Odd.
