### ISSUE TITLE
update.sh line 413

### ISSUE THREAD

**Issue by freezurbern** [red-eclipse/base#59]
>    echo ")"

doesn't write to the file, causing an error:

> Deploying: "/home/zachery/.redeclipse/cache/devel/install.sh"
/home/zachery/.redeclipse/cache/devel/install.sh: 9: /home/zachery/.redeclipse/cache/devel/install.sh: Syntax error: end of file unexpected (expecting ")")
Administrator permissions are required to deploy the files.
bin/update.sh: line 463: return: can only `return' from a function or sourced script

**Comment by qreeves** [comment]
Ugh, I actually copied that bug from the batch file :frowning:
