### ISSUE TITLE
ctf - enemy flags in deathmat don't reset to base

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#593]
Commit 78ada55 (ctf fixes (#587)) introduced some good fixes, but it seems it introduced a bug.

If I drop the enemies team's flag into deathmat, it resets to the last position much like my own flag. Enemy flags into deathmat should reset to their base.

A demo is included, first instance is at the 7 minute mark (I kill Some Assassin with a rocket, the flag falls into deathmat), another instance occurs at 2:05 (I kill zaquest and the flag bounces off the bridge into the deathmat), last instance is around the 1 minute mark.

[enemyreset.zip](https://github.com/red-eclipse/base/files/533576/enemyreset.zip)

**Comment by qreeves** [comment]
Not sure if that's really a bug more than a feature suggestion. Part of the reason is the mechanics deliberately make you hand deliver your flag back to your base (that is, without the *quick* mutator). If anything, this is just enforcing this mechanic even more.

**Comment by JeffBobbo** [comment]
The only times when someone would drop the enemy flag in deathmat is to troll their team mates, because the messed up (parkour) or because they died. It seems counter-intuitive to enforce someone to wait around for the flag to reset so they can take it and go.

It also devalues the worth of weapons with stun/hitpush, flamer2 and plasma2 can't be used as effectively to mess with people's parkour to drop the flag as they're running. You're also locking defenders potentially into a scenario where they can't shoot if their flag is over deathmat, since they might be dead by the time it's reset (and another enemy can take it the rest of the way).

Also, lastly I'd say note TheAssassin's and zaquest's reaction in the demo of "wtf" when it happened.

**Comment by TheAssassin** [comment]
Aside this discussion, changing such a central behavior on a single server is not a good idea. This should be reverted IMO until this issue is closed.

**Comment by pocak100** [comment]
Those are good arguments, @JeffBobbo. I could add a setting for `captureresetfloor` that does what you suggest. But won't it be confusing to new players?

Let's consider *multi-ctf*, too. Shooting an enemy holding a third team's flag near deathmat would become counterproductive. Is that ok?

**Comment by JeffBobbo** [comment]
Perhaps, but if I'm near death I can just jump off the map and use that to buy time as it is now.

>Let's consider multi-ctf, too. Shooting an enemy holding a third team's flag near deathmat would become counterproductive. Is that ok?

That's how it used to be anyway (and IMO, is fine, like how its best for everyone whose not got the bomb to work together to stop whoever has the bomb in hold bomber ball).

**Comment by qreeves** [comment]
I haven't exactly had time to look at the demo, why does everyone have to wait for the flag to reset? Is it stuck in the deathmat and not being returned to solid floor?

**Comment by JeffBobbo** [comment]
Yeah, its stuck. If you drop it on some thin piece of map (like the arms which stretch across the rocket spawn on Suspended), it can fall and it will reset, once it resets it will fall again and this time it won't reset.

**Comment by bonifarz** [comment]
Wasn't there a recent fix to have flags stick to their reset spot, such that they can't fall down right again?

**Comment by qreeves** [comment]
Ah OK. That is indeed just because the fix was pushed to *master* before *stable* got it (and the master server runs *master*). #596 will fix this until I push to *stable*.

**Comment by pocak100** [comment]
@bonifarz Yeah, that was part of my patchset, but it's a client side fix. Until it's deployed to players, `captureresetfloor` should be kept 0. It wasn't working right anyway.

@JeffBobbo That's because you were using the `stable` client on the `master` server. If you play back the demo (the one attached to issue 595) on a client compiled from `master`, the flag doesn't fall again.

Yes, I realize this is half breaking the protocol -- while the syntax is the same, (no disconnects), the semantic is a bit different. However, old demos should still work as flags were instantly double reset all the time. Thus, I don't think the protocol version needed incrementing. Had I included the new default for `captureresetfloor`, no one would have noticed my patch went live.

![20161018082713](https://cloud.githubusercontent.com/assets/12238757/19467150/e17a858c-950f-11e6-9707-64f8bec41a31.png)
