### ISSUE TITLE
flags can reset to unstable positions (and then sit on deathmat and not reset)

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#595]
Flags can reset to a position where they're not stable and will fall again.
If the flag falls again, it'll sit on the death mat and not reset, waiting until the timeout to reset (although it can be retrieved by a player occasionally and force it to reset).

Example with omega flag at the 8:30 ish mark while contesting for the rocket (me, yeatta and beha).

[flagdeath.zip](https://github.com/red-eclipse/base/files/534213/flagdeath.zip)

**Comment by pocak100** [comment]
This is on me, I forgot to mention in #587 that `captureresetfloor` should be set to 0 on servers until the fixes are rolled out to players (i.e. to the stable branch).

**Comment by qreeves** [comment]
Related to #593 and #596 - closing.
