### ISSUE TITLE
Improper custom map handling

### ISSUE THREAD

**Issue by Lyberta** [red-eclipse/base#598]
When I start an offline editing session with my custom map, the server acts as if the client doesn't have the map. It creates mapname_0x0.mpz and transmits it to client.

**Comment by zaquest** [comment]
This is not what happens. Since in edit mode maps are sent w/o some data (like lightmaps) new map files are written before sending them to a server. I think one solution is to put these files in /tmp and the other is to avoid disk io and write map files directly to a socket.
