### ISSUE TITLE
Add GUI to display v-parameters of the selected texture

### ISSUE THREAD

**Issue by FaTony** [red-eclipse/base#600]
Currently, there's no way to show you the modified v-parameters of the selected texture. It makes it hard to reuse, for example, vcolour if you forgot which one you've used before.

**Comment by FaTony** [comment]
Looks useful, but now the texture previews are way too small. I suggest to make it into separate window which opens when you right click on the texture slot.

**Comment by qreeves** [comment]
Yeah, I've been meaning to do that for a while but figured it might be better to remove the hard coded texture gui in favour of one written in cubescript. What's been done now is just to help you out in the short term.

**Comment by shirepirate** [comment]
close this now? https://github.com/red-eclipse/base/issues/366

**Comment by qreeves** [comment]
Nah my hack doesn't really fix that issue.
