### ISSUE TITLE
Backspace registers twice per press in text input

### ISSUE THREAD

**Issue by Hirato** [red-eclipse/base#609]
If I open the ingame console and type, the text enters normally.

If I press backspace, each press deletes TWO characters instead of just one.
This applies to the built in text editor as well (ie, autoexec.cfg editor)

EDIT:
Input driver is libinput on Arch Linux.

**Comment by Hirato** [comment]
Actually this is way worse.
If I hold W, I just impulse/dodge forward the entire time.
There's probably a missing if (!repeat) check in the input loop itself for keydown events.

**Comment by acz13** [comment]
Is this latest master?

**Comment by Hirato** [comment]
Yeah, it was.

I just built SDL2 itself from master and that fixed this issue, so it looks like it was one of their bugs.
It'll probably get fixed in SDL 2.0.6 or 2.1, which ever comes first.

**Comment by acz13** [comment]
Hmm, what SDL2 version were you using before? I was going to say this wasn't happening to me on latest RE master

**Comment by Hirato** [comment]
@acz13 Yeah, it was SDL 2.0.5.

**Comment by qreeves** [comment]
I thought it might be this! 👍
