### ISSUE TITLE
Massive lag with edit mode cube guide

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#614]
The edit mode cube guides cause massive lag, I believe this bug has been triggered by the switch to SDL2.

You can access the cube guides (self-made term) by pressing tab multiple times in Edit mode.

---
**First seen in**: stable version, also present in master

**Observation**: 
Ubuntu 16.10, latest proprietary NVIDIA drivers, GT 740 2GB
**How to reproduce**:
1.  Enter Edit mode
2. Press Tab until you reach the last (fourth?) cube guide mode
3. Lag like hell

I searched the issue list and checked that this is not a duplicate :white_check_mark: 
I tried to rename my *config.cfg*, and the problem also occurs with default settings :white_check_mark:

**Comment by graphitemaster** [comment]
If you make a large selection with a small enough grid size it does lag insanely but that's because it's rendering a ton of geometry for those lines. It may be benefical to limit the effective area of selection for the guide so it has a limited local radius instead of the entire map.

**Comment by graphitemaster** [comment]
For instance the following situation shouldn't even be allowed
![20170308215450](https://cloud.githubusercontent.com/assets/343195/23733973/f7c2e8e4-0449-11e7-9c3a-8994098b86b7.png)

**Comment by acerspyro** [comment]
The FPS drop is no longer massive as it used to be, I will consider this to be fixed.
