### ISSUE TITLE
Fix grab input in SDL2

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#617]

**Comment by TheAssassin** [comment]
@acerspyro please provide at least a description. Ideally use the issue template.

**Comment by acerspyro** [comment]
Quin said he'd understand. Oh well, just for you luv.

The bug pertains to not being able to release the mouse at will, via I
think F10 in previous versions of RE, or by moving the cursor outside the
window.

**Comment by qreeves** [comment]
Unrelated to #654 - this issue is just for re-implementing an old behaviour the engine had prior to the SDL2 port (if possible).
