### ISSUE TITLE
official devel binaries do not have "strncasecmp" defined

### ISSUE THREAD

**Issue by freezurbern** [red-eclipse/base#62]
So, I got "unknown command: strncasecmp" when sending a chat message. I compiled the game myself, and the problem went away. Can someone else confirm this?

bins.txt:
> dbae407c902d2b18f0a30a18164829cc0e87012c

Windows 7 x64
git commit: 378f944

**Comment by freezurbern** [comment]
Actually, I think the game might be using the wrong binaries, based on bins.txt and the most current git commit.

**Comment by qreeves** [comment]
Works for me, maybe they're not getting installed properly?

**Comment by qreeves** [comment]
Try this; delete gitdir/bin/bins.txt (effectively tell it to start over) then run the bat file. Check cache install.bat and paste it here.

**Comment by freezurbern** [comment]
>Checking for updates to "devel". To disable: set REDECLIPSE_BRANCH=inplace
Press any key to continue . . .
Branch: devel
Folder: D:\VersionControl\redeclipse-git
Cached: E:\Zachery\Documents\My Games\Red Eclipse\cache\devel
[I] bins: none
[R] bins: dbae407c902d2b18f0a30a18164829cc0e87012c
[D] bins: http://redeclipse.net/files/devel/windows.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3410k  100 3410k    0     0  1595k      0  0:00:02  0:00:02 --:--:-- 1595k
Deploying: "E:\Zachery\Documents\My Games\Red Eclipse\cache\devel\install.bat"
Archive:  E:/Zachery/Documents/My Games/Red Eclipse/cache/devel/windows.zip
  inflating: D:/VersionControl/redeclipse-git/bin/x86/redeclipse_server.exe
  inflating: D:/VersionControl/redeclipse-git/bin/x86/redeclipse.exe
  inflating: D:/VersionControl/redeclipse-git/bin/amd64/redeclipse_server.exe
  inflating: D:/VersionControl/redeclipse-git/bin/amd64/redeclipse.exe
Updated successfully.
Press any key to continue . . .

I added some pauses in, that's the output. it certainly downloads some files, and runs it. But, the things it downloads do not have strncasecmp.

On a second run, after it has got the binaries the first time: 
> Checking for updates to "devel". To disable: set REDECLIPSE_BRANCH=inplace
Press any key to continue . . .
Branch: devel
Folder: D:\VersionControl\redeclipse-git
Cached: E:\Zachery\Documents\My Games\Red Eclipse\cache\devel
[I] bins: dbae407c902d2b18f0a30a18164829cc0e87012c
[C] bins: dbae407c902d2b18f0a30a18164829cc0e87012c
[R] bins: dbae407c902d2b18f0a30a18164829cc0e87012c
Everything is already up to date.
Press any key to continue . . .

My cache folder: https://dl.dropboxusercontent.com/u/42922158/share/re-devel-cache.zip

**Comment by freezurbern** [comment]
install.bat after deleting bins.txt in the bin/ folder
> @ECHO OFF
setlocal ENABLEEXTENSIONS
set REDECLIPSE_ERROR=false
"D:\VersionControl\redeclipse-git\bin\tools\unzip.exe" -o "E:\Zachery\Documents\My Games\Red Eclipse\cache\devel\windows.zip" -d "D:\VersionControl\redeclipse-git" && (
    (echo dbae407c902d2b18f0a30a18164829cc0e87012c)> "D:\VersionControl\redeclipse-git\bin\bins.txt"
) || (
    del /f /q "E:\Zachery\Documents\My Games\Red Eclipse\cache\devel\bins.txt"
    set REDECLIPSE_ERROR=true
)
if "%REDECLIPSE_ERROR%" == "true" (exit /b 1)

**Comment by freezurbern** [comment]
Some more information:

- Applying the .zip from semaphore to my git folder manually results in the command still being missing.
  - http://redeclipse.net/files/devel/windows.zip
- Using the binaries compiled by Jenkins does not have the problem.
  - http://build.freezurbern.com/job/RedEclipse-base/60/artifact/REdev-dbae407c90_60-win.zip

**Comment by freezurbern** [comment]
After deleting the cache folder, cleaning and reverting my git folder, this issue still persists.

The binaries are downloaded and applied correctly, but they still have the problem of strncasecmp missing. Also, the Jenkins binaries are still working correctly.

**Comment by qreeves** [comment]
I think we might need to rename the command itself, it must be expanding inline and ending up with some stupid name like `__gnuc_strncasecmp`.

**Comment by freezurbern** [comment]
In that case, might want to test any other commands that might be the same in C++.

**Comment by qreeves** [comment]
Please tell me c560cc882f56e88cf4efb72e656649e3d0502ea0 fixes it :worried:

**Comment by bonifarz** [comment]
This fixed the reported issue for my pre-compiled win64 bins :smile: 
Another detail: When launching the client, I get this now 
```
unknown command: strcmp
6) arg1
5) guicenter
4) arg1
..1) guibox)
```
