### ISSUE TITLE
Can't join an empty server with custom map

### ISSUE THREAD

**Issue by FaTony** [red-eclipse/base#620]
If the server is running a custom map which you don't have and it's empty, the map is never transmitted.

**Comment by shacknetisp** [comment]
Have you tested this with the master branch? I believe this is already fixed with 2caa6ac734cde2a1cad9e97989caa5472b30eb6e.

**Comment by FaTony** [comment]
Just tested on Dziq's server. Still happens.

**Comment by TheAssassin** [comment]
Does manually executing `/getmap` trigger the server to send you the map?

**Comment by TheAssassin** [comment]
The bug has been solved in 2caa6ac, as it does not occur on servers like Snisp Dev who run a newer version of the master branch.
