### ISSUE TITLE
New command: /warn

### ISSUE THREAD

**Issue by TheAssassin** [red-eclipse/base#624]
As discussed previously, it would be nice to have a `/warn <cn> <message>` command.

The command is supposed to be used by moderators as a less aggressive method to discipline misbehaving players (following the rules in the guidelines).

The warning should be displayed similar to the teamkilling warning so that it is actually effective.

**Comment by bonifarz** [comment]
Actually, when I added some moderation stuff to the client menu, I included this functionality on one of the buttons.

**Comment by IceflowRE** [comment]
But the warning is not displayed similar to the teamkilling warning ;D

**Comment by TheAssassin** [comment]
@bonifarz I cannot find the menu you mentioned, could you please describe how to find it?

**Comment by bonifarz** [comment]
Oops, have not seen the last line on the description. Seems nice to have, and in return, will be a must have for said menu.

**Comment by TheAssassin** [comment]
This is WIP btw, I am going to publish this someday in February.
