### ISSUE TITLE
Maps with CRC are not openable

### ISSUE THREAD

**Issue by Lyberta** [red-eclipse/base#626]
If you try to start editing map that you've downloaded from the server (which has the name "mapname_0x12345678.mpz"), you get an empty map.

This bug only shows when you don't have the map with the same name but without CRC.

**Comment by shacknetisp** [comment]
I can confirm that when I could not download the map when I did not previously have it and the `mapname_<crc>` form was voted.

I don't think the `mapname_<crc>` maps should be saved directly in the maps folder anyway, which would bypass most or all instances of this problem, but that's a separate issue.

[Related demo (where the others had the map)](https://beha.zapto.org/files/demos/issues/crc_download.dmo)

**Comment by TheAssassin** [comment]
I guess one shouldn't even be able to vote for `mapname_<crc>`. This is a bad style of namespacing anyway (map names can just include underscores, too). A player should just vote for `mapname`, and after it passed they should upload it to the server and have the server distribute it to the clients that don't have it yet.
