### ISSUE TITLE
Game renders more than it should

### ISSUE THREAD

**Issue by FaTony** [red-eclipse/base#630]
So I was trying to optimize my map and used `dtoutline 0` to see what is being rendered and I've found that the game consistently renders parts of the level that I have no way of seeing. I have 2 floor map and while I'm on the 2nd floor, the 1st floor directly under me was rendered. It seems like the game will render any geometry within some radius regardless of visibility. My tests indicate the value somewhere between 128 and 192 units.

**Comment by Hirato** [comment]
dtoutline disables depth testing, so absolutely nothing gets culled, unless you've generated PVS data.
On more modern video cards, there are certain extensions that cull even more, one of which is called GL_ARB_occlusion_query (everyone playing RE now should have one of those)

The PVS system also uses a cell size of 32 units if you don't specify one; I assume it's aligned to the map, so it will probably work most efficiently if you align the map with Size 5 cubes.

**Comment by FaTony** [comment]
Does calclight generate PVS data? Not all of the level was rendered.

**Comment by Hirato** [comment]
that is done via /genpvs.
you can use /testpvs to fix it to your current view cell.

**Comment by FaTony** [comment]
Wow, it takes forever. About 5 cells per second out of the 18000. What are the benefits of this?

**Comment by TheAssassin** [comment]
This is not really a bug, nothing has to be fixed here.
