### ISSUE TITLE
error while loading shared libraries: libSDL2-2.0.so.0

### ISSUE THREAD

**Issue by Arinerron** [red-eclipse/base#634]
Hello. While trying to set up version 1.5.6 of redeclipse on Linux Mint 17.3, an error occurred. First, I executed `sh redeclipse.sh`. After downloading the resources, it reported an error:
```
/home/<snip>/Desktop/redeclipse-1.5.6/bin/amd64/redeclipse_linux: error while loading shared libraries: libSDL2-2.0.so.0: cannot open shared object file: No such file or directory
```

Every time I run the script, I get the same error. If you need any specs or info, feel free to comment.

Thanks!

**Comment by Robalni** [comment]
Have you installed the sdl library? You need these packages: libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0

more information here: http://redeclipse.net/wiki/How_to_Install_Red_Eclipse

**Comment by TheAssassin** [comment]
This is not a bug, you just don't have the relevant libraries.
@Robalni pointed in the right direction, although you need a few more libraries to be able to use `redeclipse.sh` completely:

    sudo apt-get install git curl libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0

**Comment by Arinerron** [comment]
Thanks. I do already have git and curl.

**Comment by Icekhaos** [comment]
I have this, and I have all of the above libs.

Any tips?

**Comment by Arinerron** [comment]
@Icekhaos the exact same error or is it a different lib?

**Comment by Icekhaos** [comment]
Was the exact same error. Linking around fixed it.

**Comment by qreeves** [comment]
Thanks for providing an update when you solved it!

**Comment by debruben** [comment]
> This is not a bug, you just don't have the relevant libraries.
> @robalni pointed in the right direction, although you need a few more libraries to be able to use `redeclipse.sh` completely:
> 
> ```
> sudo apt-get install git curl libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0
> ```

Thank you so much, this helped!
