### ISSUE TITLE
Unnecessary demo recorded

### ISSUE THREAD

**Issue by TheAssassin** [red-eclipse/base#635]
When a player connects to an empty server and tries to auth before the "readying" phase is over (manually with `/auth` or using `authconnect 1`), the server unnecessarily records a demo.
It seems irrelevant whether the auth request succeeds or not (I tested the latter with the "auth failed, server is not connected to master" scenario).

**Comment by shacknetisp** [comment]
I cannot reproduce this in the master branch, please confirm this still occurs and if so, give detailed steps to reproduce it.
