### ISSUE TITLE
Prevent moderators from quarantining other mods

### ISSUE THREAD

**Issue by TheAssassin** [red-eclipse/base#637]
In cooperation with @acerspyro, I discovered that moderators (or better) can put other moderators (or better) into quarantine, which should be forbidden to prevent trolling.
We should implement a privilege level check that checks the target's privilege and prevents the operation if they have the same or higher privileges.
This is related to #636.

**Comment by acerspyro** [comment]
Admins and up should be able to unquarantine thrmselves at least
