### ISSUE TITLE
Gib sound plays through entire map

### ISSUE THREAD

**Issue by Jigoku** [red-eclipse/base#64]
I assume this is a bug.

I was playing some bot matches on the latest version (whatever git is at right now) and randomly heard gib sounds although nobody near me had died, confused, i went into spectator mode, and flew about, while still hearing the occasional gib sounds, even without a bot nearby

At first i thought the sound spam that occured with the underwater noise recently was still there, but with the gib sound instead. Me and bonifarz played about, spawning bots and it seems there is no proximity/positional location to the gib sound when a player/bot dies.

Reproduce:
1. load a map
2. spawn a bunch of bots
3. spectate while flying far away from the map
4. you can hear gib sounds as the bots die.

**Comment by freezurbern** [comment]
It is reproducible for me. Confirmed?

**Comment by qreeves** [comment]
Is it just the gib sound (S_SPLOSH)?

**Comment by Jigoku** [comment]
Yeh, just these:
```
data/sounds/sfx/splosh1.ogg
data/sounds/sfx/splosh2.ogg
data/sounds/sfx/splosh3.ogg
```
