### ISSUE TITLE
Bind alt + enter to fullscreen by default

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#646]
Because that's how it is in a lot of the games I saw, so why not? 

If possible, also bind Ctrl + Alt + Enter to fake fullscreen (Borderless window), if it's not too much work.

**Comment by TheAssassin** [comment]
On my system, <kbd>alt</kbd>+<kbd>enter</kbd> switches from windowed to borderless window and vice versa.
Could be that this is implemented already.
But yeah, this is not too hard, just add a bind that toggles the `fullscreen` variable.
