### ISSUE TITLE
Cull bug on particle effects

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#650]
[Link](https://youtu.be/ld0enBbS8P8)

The video shows what I assume is a geom cull bug on the plasma ball particle effect, as seen on Space Tech.

Dziq can testify, it is not just me.

Configuration:

Windows 10 64-bit
Latest Nvidia drivers (as of writing this)
Red Eclipse 1.5.8
GT 740 graphics

**Comment by qreeves** [comment]
Is this still present in master?

**Comment by acerspyro** [comment]
No.
