### ISSUE TITLE
Initial mouse input strangeness running fullscreen on Weston / Wayland with SDL2 2.0.5

### ISSUE THREAD

**Issue by Valmar33** [red-eclipse/base#654]
## **Edited to reflect observations**

**First seen in**

Current master

**Related forum topic**

http://redeclipse.net/forum/viewtopic.php?f=4&t=1131&p=10178

**Observation**

Attempting to run Red Eclipse in Weston using SDL_VIDEODRIVER=wayland works fine, except that the cursor is responding to mouse input strangely. Sometimes, it's restricted to an area, sometimes it's not, sometimes, it just reacts to mouse movement without any pattern.

However, if I can enter a submenu, mouse input suddenly works completely fine without issue.

**How to reproduce**

1. Install latest Wayland, Weston and Wayland Protocols.
2. Install SDL2 version 2.0.5.
3. Run "weston-launch" in virtual terminal.
4. Open terminal.
5. Run "SDL_VIDEODRIVER=wayland redeclipse"
6. Move mouse around significantly and watch the strangeness unfold.

**Comment by TheAssassin** [comment]
Could you please provide more information? Specifically your distribution, its version and how you installed SDL2 (if it was your package manager, please provide the exact version string, they might have patched it or compiled it differently).

**Comment by Valmar33** [comment]
Sure.

I'm using Arch Linux, with fully updated repo packages. It's at version 2.0.5, which includes relative pointer support. Pointer confinement relies on the Wayland compositor, which Weston fully supports.

The repo package has been configured with:

../SDL2-$pkgver/configure --prefix=/usr \
    --enable-sdl-dlopen \
    --disable-arts --disable-esd --disable-nas \
    --enable-alsa --enable-pulseaudio-shared \
    --enable-video-wayland \
    --disable-rpath

They haven't patched it or anything. Here is the full PKGBUILD:
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/sdl2

**Comment by TheAssassin** [comment]
This might be related to #617. @acerspyro needs to provide more information on that issue.

We'll also need someone to confirm this issue independently.

Could you please try to run some older version (e.g. 1.5.6 release) and see if the bug happens there, too? If yes, it's very likely related to SDL2.

**Comment by Valmar33** [comment]
I've tested some more, and I discovered that if I enter a submenu after wrangling with the cursor, input works perfectly fine. I'll also test this with the current stable release. Should update the title to reflect.

Why the initial weirdness though?

**Comment by zaquest** [comment]
I can confirm it. The same issue with tesseract. Starts working properly after the first MouseLeft/MouseRight click regardless of whether submenu was opened.

**Comment by Valmar33** [comment]
I've also confirmed this happening with Tesseract.

@zaquest 
After the first right or left mouse click? Never thought to try that. :P

**Comment by zaquest** [comment]
It seems that this behaviour is due to weston sending WindowEnter/WindowLeave events when it should not. It seems that something is wrong with cursor grab, since in windowed mode (before the first click) it allows cursor leaving window's area when the cursor is grabbed. So when desktop's cursor leaves the game's window, WindowLeave is generated and RE releases cursor grab, game's cursor stops moving until cursor is back inside the game's window. It might work with other games because they don't release grab on WindowLeave, probably.

**Comment by acz13** [comment]
Is this Weston specific or does this happen on other Wayland compositors?

**Comment by acerspyro** [comment]
This is weston-specific.
Tested in Gnome 3.26.2 in Wayland mode on ArchLinux and the mouse cursor behaves correctly. The bug still exists in Weston, however.
