### ISSUE TITLE
Limit length of custom version suffix

### ISSUE THREAD

**Issue by TheAssassin** [red-eclipse/base#656]
At the moment, it is possible to set the `RE_BRANCH` environment variable very long strings, which increases the scoreboard width a lot. We should limit its length in some way.
A hard coded limit should do it, there is no need for a variable. We have to sanitize user input, so if the string is longer than e.g. 20 characters, we'll just clip it.
Limiting it to a set of predefined strings was suggested too, but this is more effective. It could be considered a feature to be able to set version strings to custom values, too.

**Comment by qreeves** [comment]
Yeah, I considered it a feature to set them as well. Probably other things that need this as well.
