### ISSUE TITLE
Add missing people to the credits

### ISSUE THREAD

**Issue by TheAssassin** [red-eclipse/base#658]
We noticed that quite some people are missing on the credits list.
I will collect a list of people and what they added to our project, and add them to the credits list later.

People that need to be added:
 * @JeffBobbo 
 * @Dziq84 
 * @shacknetisp 
 * @TheAssassin

I welcome any suggestions, don't be shy.

**Comment by shirepirate** [comment]
you can really just push it through yourself, no need for an issue. just list contribution and name/alias

**Comment by TheAssassin** [comment]
I wanted to have an issue so this is not forgotten again. Long time contributors haven't been credited for quite a while, and this is a no-go IMO.

**Comment by qreeves** [comment]
I should do it when I raise their access level on the master server, but I always forget. It's not like I'm trying to leave people out, just the number of tasks that I have to do is so large things get lost.

**Comment by TheAssassin** [comment]
Fixed in 912f13b.
