### ISSUE TITLE
Water refraction splits framerate in half

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#662]
Water refraction is not that much of an intensive effect, and yet, it manages to split my framerates in half when there is a lot of it (See: Bath)

A quick fix for now is to disable the effect for both falling and stationary water.

CPU: FX 8320
GPU: GT 740

Tried on Windows 10 and Ubuntu 16.10.

**Comment by TheAssassin** [comment]
You should also check out that one racing map @IceflowRE made (I don't remember the name) that uses a lot of water elements. It totally kills my framerate (it drops to < 10) and I have an overclocked GTX 760. On the race map, disabling increases the frame rate just marginally.
On bath, the frame rate is significantly lower than on other maps, I can confirm that issue.

**Comment by acerspyro** [comment]
Why was this closed?

**Comment by qreeves** [comment]
It is not fixable in Cube 2 and I don't accept issues that are purely speculative in nature. Considering you don't know the architecture of the engine and its history, you aren't qualified to judge that it isn't an intensive effect within the given framework. I've said it a million times, issues are for *confirmed bugs* and *approved suggestions*, not opinions, use the forums to discuss those.

The rule here is not a new one for any Cube 2 project, and is as old as water reflections: You are not to have more one than water feature visible from any given viewpoint. The effect already has options to disable it, and problems are far less noticeable on newer hardware.

**Comment by acerspyro** [comment]
Could have stopped at "This is a non-issue and should be discussed on the
forums", but thanks.

**Comment by IceflowRE** [comment]
@acerspyro @TheAssassin 
It was waterrun: https://github.com/IceflowRE/community/tree/ice_WIP/maps

**Comment by Hirato** [comment]
You can try changing `/maxreflects` to 1 and see if that reduces the impact.
That variable controls the maximum number of water surfaces updated per frame.

This is probably better discussed on the forum.
