### ISSUE TITLE
Include git revision details in version string

### ISSUE THREAD

**Issue by TheAssassin** [red-eclipse/base#663]
It is potentially useful to include some more information in our version string than *just* the version major, minor and patch IDs.

The most useful information to include would be the Git revision ID (some short version, e.g. the first 8 chars, is fine) and whether it is a clean build or there's modifications in the source tree. We can get both information by running those commands:

  git rev-parse HEAD | cut -c 1-8
  git diff-index --quiet HEAD

There might be a more elegant way to do that using CMake (see e.g. this [StackOverflow thread](https://stackoverflow.com/questions/1435953/how-can-i-pass-git-sha1-to-compiler-as-definition-using-cmake)).

We should add some C++ header for that including some `#define`s, and pass the information when running the compiler (`-D...`). I suggest `GIT_REV_ID` and `GIT_DIRTY` as names.

As a fallback when building without git client available or when building from a source tarball without `.git` directory, we should use `00000000` for `GIT_REV_ID` and set `GIT_DIRTY` to false.

**Comment by TheAssassin** [comment]
(Sorry for commit spam, had a few issues with my new development environment (bla@bla.bla email address etc).)

The implementation provided in #665 implements the requested features, but has some caveats detecting the state with non-cleaned builds (the Makefile implementation for example lacks caching at all, the CMake one needs caching for the dirty flag). Though, it works, and the caching doesn't affect building in a CI environment.

Further discussion is needed about how to cache the data properly. The [CMake implementation](https://github.com/TheAssassin/redeclipse-base/blob/master/src/CMakeModules/GetGitRevisionDescription.cmake) for example creates some copies of files in the `.git` directory, this approach could be used by the Makefile, too.

**Comment by acerspyro** [comment]
https://github.com/red-eclipse/base/pull/665 seems abandoned, closing.
