### ISSUE TITLE
Add Github topics

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#668]
Github has now tags, maybe some admins should add some.

**Comment by TheAssassin** [comment]
Well, you could suggest us some. I've thought about it, too, but I wouldn't know what to add. Perhaps `c++` and `cube2`.
The [feature](https://github.com/blog/2309-introducing-topics) is brand new and not necessarily important, so this is not really urgent.

**Comment by qreeves** [comment]
This is a [discussion topic](http://redeclipse.net/forum), not an issue with the code.
