### ISSUE TITLE
Mutator to turn off radar

### ISSUE THREAD

**Issue by Honno** [red-eclipse/base#67]
EDIT: I swear hard was going to have no impulse regen/other stuff, but I've heard conflicting reports that it's just no radar and regen. Sorry if that's the case heh.

I suggest that RE has a mutator to disable radar. I personally enjoy radar on/off respectively just like I enjoy the added experience other mutators offer.

Promode/hard mutator disables radar, but I and dare I say others prefer just disabled radar and nothing else. Similar case to the classic mutator with the prospected promode (afaik anywho), unless that's going to go too.

Reasons for: It's easer to change then using a server variable/client turning it off (although there's a nice bind [here](http://redeclipse.net/forum/viewtopic.php?f=7&t=206), ensures everyone in-game is not using radar more easily, and doesn't require permissions on a server to change.

Reasons against: Most players would not use it, only those pros who enjoy the 'competitive depth' of disabled radar, so it clutters the mutator selection. Radar is also more related to higher level of play rather than how the other mutators just mix things around, maybe defeating their purpose.

Don't get me wrong here, I'm not one of those pros who always disables it, and actually prefer radar competitively (duels), I just want the accessibility of a mutator.

**Comment by freezurbern** [comment]
Sounds like something that should be left to hard mode, or perhaps be a server variable like #66.

**Comment by shirepirate** [comment]
this is already a mutator <i>and</i> a server variable.
