### ISSUE TITLE
Cursor accuracy decreases as distance increases in edit mode

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#671]
---
**First seen in**: Current master

**Observation**: In edit mode, looking far away with a small brush, the brush will be to the right of the cursor.

![20170214210805](https://cloud.githubusercontent.com/assets/4400999/22957996/40ccbcce-f2fa-11e6-8b8e-dde49c2559c5.png)

**How to reproduce**:
1. Go into edit mode
2. Use something around brush 4
3. Aim at a distant point

I searched the issue list and checked that this is not a duplicate :white_check_mark: 
I tried to rename my *config.cfg*, and the problem also occurs with default settings :white_check_mark:

**Comment by qreeves** [comment]
Hmm, this might be why we were using `game::focusedent()` instead of `camera1`.

**Comment by acerspyro** [comment]
Fixed during Tesseract port.
