### ISSUE TITLE
arm architecture refuses to run (server)

### ISSUE THREAD

**Issue by Jigoku** [red-eclipse/base#69]
I run the server on a raspberry pi, but since changes to the launcher scripts (redeclipse.sh, redeclipse_server.sh) running it results in:
```
Unsupported architecture: armv6l

There was an error running Red Eclipse.

```

In the case of arm, the standalone server builds and runs fine. 'redeclipse.sh' should check if it is being run as a server and allow other architectures such as arm to work around this. 

I did try adding to 'redeclipse_setup()' in 'redeclipse.sh' :
```
arm*)
    [ "${REDECLIPSE_BINARY}" = "redeclipse_server" ] && REDECLIPSE_ARCH="arm"    
;;

```

However it returns:
```
Unable to find a working binary.
```

All i know in this case is that it should try to launch the binary named 'redeclipse_server_native'

**Comment by Jigoku** [comment]
Also, if i run the binary directly without the launcher scripts (unable to set path/home)
```
/opt/redeclipse/bin/redeclipse_server_native 
2015-02-25 11:30.47 identity: v1.4.9-nix32 server (Development) [0xa19118e9]
2015-02-25 11:30.47 configuration loaded
2015-02-25 11:30.47 loading server (*:28801)..
2015-02-25 11:30.47 dedicated server started, waiting for clients...
2015-02-25 11:30.47 looking up play.redeclipse.net:[28800]...
2015-02-25 11:30.47 updating master server
2015-02-25 11:30.47 master server reply: server registered (port 28801), sending ping request (on port 28802)
```
It's identifying itself as nix32 for some reason.

**Comment by qreeves** [comment]
> It's identifying itself as nix32 for some reason.
It is still a 32 bit program running on Linux then, doesn't matter if it is ARM or whatever.

**Comment by qreeves** [comment]
Can you give me the ouput of "gcc -dumpmachine" on the RasPi?

**Comment by Jigoku** [comment]
Here it is
```
arm-slackware-linux-gnueabi
```
