### ISSUE TITLE
Missing button to release the mouse

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#701]
Older versions of the game used to feature a mouse release button on the F9 (?) key.

The fact that this key is now missing is extremely irritating in conjunction with the fact that the game automatically minimizes itself upon alt-tab. This prevents me from right-clicking its titlebar to change the window to Fullscreen in KDE. Even if I can get the menu to open via Alt + F3, it cannot be controlled, as the game also captures the keyboard.

The best fix would be to let the mouse leave the window if it goes beyond the edge of the window.

**Comment by qreeves** [comment]
See #779
