### ISSUE TITLE
4 FPS Bug

### ISSUE THREAD

**Issue by TheAssassin** [red-eclipse/base#712]
Here it is, the GitHub issue for the infamous 4 FPS bug that has causing trouble for me for quite a long time.

When I alt-tabbed out and back in, sometimes the game's frame rate dropped to <= 4 fps. As I recently found out, this only occurs in windowed mode. Executing `fullscreen 1` eliminated the problem, going back to windowed reintroduces the issue.

After some debugging, I suspect that it's my compositor compton which causes the problem, as `killall compton` also solves the problem. I presume that the issue is caused by compton's OpenGL based vsync feature which I use to get rid of tearing (something xfwm's compositor cannot solve properly).

As running my DE without a compositor is not an option, I'll try to replace it with some different software, e.g. compiz.

The question is, how could SDL2 possibly interact with compton after alt-tabbing back in so that the frame rate is dropped to such a low value?

@graphitemaster any ideas? You have a good amount of SDL2 experience afaics.

P.S.: The issue is not 100% reproducible, which makes it super annoying to debug.

(CC #614)

**Comment by acz13** [comment]
in general not such a great idea to play video games  w/ compositor on :shrug:

weird stuff seems to happen to me

**Comment by TheAssassin** [comment]
Well, a compositor brings a lot of advantages to non-gaming time, e.g., prevents tearing due to vsync.

**Comment by acz13** [comment]
yeah, I have a quick shortcut to turn on/off compositing in i3

**Comment by qreeves** [comment]
Invalid due to compositor issues.
