### ISSUE TITLE
Changing shaderdetail in a weird way causes segfaults

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#713]
While developing the future settings UI, I encountered a segfault bug. In that menu, a fancy shader details button can be found.

If you toggle water reflections from the on position (which turns itself off, flickers the screen, and turns itself back on for some reason when done through a checkbox) on a map that has water (I found it helps to attempt reproduction after looking at water at least once), and then change the shader detail level, the game will (likely) segfault.

I find it's easier to trigger the bug if you wait one second between each click in the settings menu.

This bug is quite the special little flower, @shacknetisp thinks it has to do with some memory being overwritten with the UI.

Here is a link to the UI so you can reproduce the bug:
https://gist.github.com/acerspyro/8978e8f1910a9149268cc5382ff6d4d1

## Backtrace
https://gist.github.com/acerspyro/5facf1ce3195dac152ab6b214dd54850

## Result of ldd on redeclipse_linux
`        linux-vdso.so.1 =>  (0x00007ffc20bcd000)                                                                                                                                                                     
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f824965b000)                                                                                                                                    
        libSDL2-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0 (0x00007f8249343000)                                                                                                                          
        libSDL2_image-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2_image-2.0.so.0 (0x00007f824911b000)                                                                                                              
        libSDL2_mixer-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libSDL2_mixer-2.0.so.0 (0x00007f8248ec3000)                                                                                                              
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f8248ca3000)                                                                                                                                            
        libGL.so.1 => /usr/lib/nvidia-378/libGL.so.1 (0x00007f8248a13000)                                                                                                                                            
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f824880b000)                                                                                                                                          
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f8248483000)                                                                                                                              
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8248173000)                                                                                                                                            
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8247da3000)                                                                                                                                            
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f8247b7b000)                                                                                                                                    
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8247973000)                                                                                                                                          
        libasound.so.2 => /usr/lib/x86_64-linux-gnu/libasound.so.2 (0x00007f8247673000)                                                                                                                              
        libpulse.so.0 => /usr/lib/x86_64-linux-gnu/libpulse.so.0 (0x00007f8247423000)                                                                                                                                
        libsndio.so.6.1 => /usr/lib/x86_64-linux-gnu/libsndio.so.6.1 (0x00007f8247213000)                                                                                                                            
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f8246ffb000)                                                                                                                                  
        libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f8246deb000)                                                                                                                            
        libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f8246be3000)
        libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f82469d3000)
        libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f82467c3000)
        libXss.so.1 => /usr/lib/x86_64-linux-gnu/libXss.so.1 (0x00007f82465bb000)
        libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f82463b3000)
        libwayland-egl.so.1 => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007f82461ab000)
        libwayland-client.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f8245f9b000)
        libwayland-cursor.so.0 => /usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007f8245d93000)
        libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f8245b53000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8245933000)
        libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f824570b000)
        libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f82454ab000)
        libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f8245233000)
        libwebp.so.5 => /usr/lib/x86_64-linux-gnu/libwebp.so.5 (0x00007f8244fd3000)
        libmodplug.so.1 => /usr/lib/x86_64-linux-gnu/libmodplug.so.1 (0x00007f8244c43000)
        libfluidsynth.so.1 => /usr/lib/x86_64-linux-gnu/libfluidsynth.so.1 (0x00007f824497b000)
        libvorbisfile.so.3 => /usr/lib/x86_64-linux-gnu/libvorbisfile.so.3 (0x00007f824476b000)
        libFLAC.so.8 => /usr/lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007f82444f3000)
        libmad.so.0 => /usr/lib/x86_64-linux-gnu/libmad.so.0 (0x00007f82442d3000)
        libGLX.so.0 => /usr/lib/nvidia-378/libGLX.so.0 (0x00007f82440a3000)
        libGLdispatch.so.0 => /usr/lib/nvidia-378/libGLdispatch.so.0 (0x00007f8243db3000)
        /lib64/ld-linux-x86-64.so.2 (0x00005631f111d000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f8243b9b000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f8243993000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f824378b000)
        libjson-c.so.2 => /lib/x86_64-linux-gnu/libjson-c.so.2 (0x00007f824357b000)
        libpulsecommon-8.0.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so (0x00007f82432fb000)
        libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f82430ab000)
        libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f8242e93000)
        libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f8242c83000)
        libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f8242a7b000)
        libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f8242873000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f824264b000)
        libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007f824243b000)
        libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f8242123000)
        libjack.so.0 => /usr/lib/x86_64-linux-gnu/libjack.so.0 (0x00007f8241ed3000)
        libpulse-simple.so.0 => /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0 (0x00007f8241ccb000)
        libsndfile.so.1 => /usr/lib/x86_64-linux-gnu/libsndfile.so.1 (0x00007f8241a5b000)
        libreadline.so.6 => /lib/x86_64-linux-gnu/libreadline.so.6 (0x00007f8241813000)
        libvorbis.so.0 => /usr/lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007f82415e3000)
        libogg.so.0 => /usr/lib/x86_64-linux-gnu/libogg.so.0 (0x00007f82413d3000)
        libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f824134b000)
        libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (0x00007f824113b000)
        libasyncns.so.0 => /usr/lib/x86_64-linux-gnu/libasyncns.so.0 (0x00007f8240f33000)
        libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f8240cc3000)
        libvorbisenc.so.2 => /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007f8240a13000)
        libtinfo.so.5 => /lib/x86_64-linux-gnu/libtinfo.so.5 (0x00007f82407e3000)
        libselinux.so.1 => /lib/x86_64-linux-gnu/libselinux.so.1 (0x00007f82405bb000)
        libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f82402d3000)
        libnsl.so.1 => /lib/x86_64-linux-gnu/libnsl.so.1 (0x00007f82400b3000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f823fe93000)
        libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f823fc7b000)`

## redeclipse_linux binary and core dump
http://acerspyro.ca/fileupload/

**Comment by TheAssassin** [comment]
@acerspyro it'd be way more convenient to debug if you could provide a core dump.

**Comment by shacknetisp** [comment]
Please confirm this issue exists in the new engine. `shaderdetail` isn't even a variable anymore, and I don't know an equivalent variable to test with.

**Comment by qreeves** [comment]
There is no shader detail anymore, everything is done with shaders in Tesseract.
