### ISSUE TITLE
Redo command crashes the game in edit mode

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#738]
On the master branch, pressing 'o' to redo an undo command crashes the game with this error:

`inconsistent msg size for 59 (3 != -1)`

Using commit https://github.com/red-eclipse/base/commit/a4b5cac8f66ecee3b012ff3441cd1ef2743c0cc6 on ArchLinux x64

**Comment by qreeves** [comment]
Fixed in master.
