### ISSUE TITLE
Textures are half the size they should be

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#739]
The textures in every map on master are half the size of what they should be.
Could this be because the Tesseract engine allows for bigger textures?

Using commit https://github.com/red-eclipse/base/commit/a4b5cac8f66ecee3b012ff3441cd1ef2743c0cc6 on ArchLinux x64

**Comment by SniperGoth** [comment]
Yes, that's how tesseract handles texture scale, it doubles them.
I think it's fixable on the code, or by manually changing the values on their .cfg files.

**Comment by acerspyro** [comment]
fixing it in the code and allowing texscale to go down to 0.0625 would be easier than going around changing everything

**Comment by IceflowRE** [comment]
But 0.0625 as minimum is not a nice value to have.

**Comment by acerspyro** [comment]
The current minimum is 0.125, not much better. Ideally, the min tex size would be 1.

**Comment by TheAssassin** [comment]
So, what would you prefer? Fixing the calculation to have a scale like before, or changing the scale to have a minimum of 1?

**Comment by lsalzman** [comment]
Nieb had me change TEX_SCALE from 8 (Sauerbraten) to 16 (Tesseract), with the argument that we are past 1996, and can afford greater texture density. But with so many legacy textures/maps/assets in RE, it makes more sense to return it to 8, so everything is scaled properly again. Newer textures could always resort to using texscale to get the higher density if they really need it.
