### ISSUE TITLE
Cannot change orientation of particle type 8 (fire)

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#771]
In Edit mode, changing the `dir` property of a particle of type 8 (fire) does absolutely nothing.

The particle direction stays at a weird diagonal angle until `dir` is over 270, at which point the `dir` value is useless for the desired effect.

![20171124132637](https://user-images.githubusercontent.com/4400999/33221101-23efde74-d11b-11e7-9987-0ac8016001cc.png)

**Comment by shacknetisp** [comment]
This issue appears to be fixed, please confirm.

**Comment by molexted** [comment]
![20190227114903](https://user-images.githubusercontent.com/23445929/53518317-a54f2680-3a85-11e9-8c2e-59d8c114a675.png)
![20190227114847](https://user-images.githubusercontent.com/23445929/53518318-a54f2680-3a85-11e9-8c2b-9b44159161b1.png)
![20190227114839](https://user-images.githubusercontent.com/23445929/53518319-a54f2680-3a85-11e9-84e9-18067f40dea4.png)
![20190227114831](https://user-images.githubusercontent.com/23445929/53518320-a5e7bd00-3a85-11e9-95fc-9a9a01bd86fc.png)

`dir` appears to work properly (build 2354)
