### ISSUE TITLE
Activating vsync makes the loading screen take at least 2 to 3 times longer to complete. 

### ISSUE THREAD

**Issue by SniperGoth** [red-eclipse/base#777]
For some reason, when playing with vsync turned on, when you change map/load map, the loading takes at least 2 times longer to complete, than with vsync turned off.

This only seems to occur on Master, as on stable, even with playing with vsync on, this doesn't seem to 
happen.

**How to reproduce**:
1.  /vsync 1
2.  load any map.

**Comment by lsalzman** [comment]
Fixed. progressfps was broken. Not anymore.
