### ISSUE TITLE
Windows installer - No header

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#784]
<s>This one is kind of an emergency:
https://github.com/red-eclipse/world/issues/8
The Windows installer is not working for anyone.</s>

The header graphic is blank in the installer and the game doesn't load assets.

This is happening ever since Quin pushed 1.5.9.
I am the last one who touched the installer code, but when built locally, the installer worked perfectly.
Quin published something without checking if it was working first. ᵖᶫᵉᵃˢᵉ ˢᵗᵒᵖ ᵈᵒᶦᶰᵍ ᵗʰᵃᵗ

This has to be addressed ASAP.

**Comment by shacknetisp** [comment]
Side effect of #785.

**Comment by qreeves** [comment]
The asset issue is separate from the NSIS installer issues.

The only real job of the NSIS installer script is when used by the deployment server during `make dist-win`, so *you* need to check that when you make changes to it. It is never built manually.

Also, I can't triple check everything. Not only do I not have the resources to do so (I'd literally need to carry a monitor to each of non-desktop systems), but usually by the time a release is actually pushed out I've pulled a few all-nighter's making that happen.

**Comment by acerspyro** [comment]
NSIS version 2 was *VERY* picky about header images.

When I installed NSIS on both Linux and Windows, I grabbed version 3 (the latest), which is not as picky with the header images.

I'll try to fix the header image for NSIS 2, but the builder script should be using NSIS 3.

**Comment by acerspyro** [comment]
44d6ddd41f73c55959c176eb37517b123b4b4724 fixes this issue. @qreeves will have to re-build the installer.
