### ISSUE TITLE
Unable to load some textures

### ISSUE THREAD

**Issue by AMDmi3** [red-eclipse/base#788]
I'm working on updating FreeBSD port of RE to 1.6.0. The game and data build and install file, however some textures are missing (such as main menu background), with [ texture error ] placeholders and corresponding log errors (after sort -u):

```
could not load texture textures/background
could not load texture textures/cube2badge
could not load texture textures/editing
could not load texture textures/guiexit
could not load texture textures/guihover
could not load texture textures/guioverlay
could not load texture textures/guiskin
could not load texture textures/guiskinborder
could not load texture textures/hud/cursorinput
could not load texture textures/hud/voices
could not load texture textures/menu
could not load texture textures/progress
could not load texture textures/progring
could not load texture textures/textskin
could not load texture textures/textskinborder
```

If you look into the repo, for example textures/background, while present in https://github.com/red-eclipse/textures/tree/v1.5.8 is indeed missing in https://github.com/red-eclipse/textures/tree/v1.6.0, while 1.6.0 sources still reference it:

https://github.com/red-eclipse/base/blob/v1.6.0/src/engine/texture.cpp#L36

Could it be that 1.6.0 tags on the data which were set after the release (#786) are incorrect?

**Comment by qreeves** [comment]
Yeah, looks like the tags were done using the HEAD revision instead of the one stable references.

I really didn't want to continue tagging the submodules as it is unwieldy and floody, and I'd prefer everything use the commit that the base repository references instead.

Is the tag really necessary, or can you get the submodule reference commits instead?

**Comment by AMDmi3** [comment]
I can't. FreeBSD port uses github generated tarballs by tag, not only submodule commit info is not available, but data is also separate port so even if it was it couldn't be used.

**Comment by AMDmi3** [comment]
Could you please fix tags ASAP? I can't update the port without it. Or is there another official way to get data?

**Comment by zaquest** [comment]
Since fetching by tags won't get you any updates after a release you could probably use releases' tarballs directly https://github.com/red-eclipse/base/releases/tag/v1.6.0

**Comment by AMDmi3** [comment]
I pretty much hope that neither tags nor tarballs will get me any "updates" after the release, cause otherwise checksum checks will fail and package builds will break. I'll try the tarballs, but are there souce+data tarball? They all look like binary releases.

**Comment by Hirato** [comment]
They are, but the binary releases still include the full source code.

**Comment by qreeves** [comment]
I've fixed the issue, but you might need to force-refresh the tags to see the updated ones if you've already checked them out. Sorry it took a while, wrong time of year to do a release 😒

**Comment by AMDmi3** [comment]
Thank you!
