### ISSUE TITLE
Minimap is flipped

### ISSUE THREAD

**Issue by molexted** [red-eclipse/base#790]
Shown on build 2019, 1.9.9.
Minimap is flipped, leading to the player being placed on the wrong part of the minimap.

This is true of unported maps from 1.6.0,
![20171231112659](https://user-images.githubusercontent.com/23445929/34463823-b1c1e2c8-ee1d-11e7-9753-d2634f454a7d.png)

maps that have been worked on since at least build 1940,
![20171231112215](https://user-images.githubusercontent.com/23445929/34463826-c8893bbe-ee1d-11e7-9c4f-33940feda366.png)
![20171231112206](https://user-images.githubusercontent.com/23445929/34463839-1921d522-ee1e-11e7-8a97-8974c8e5099c.png)

and maps created in the current build (2019):
![20171231112302](https://user-images.githubusercontent.com/23445929/34463831-e9d96ee2-ee1d-11e7-840c-bdee533a61c4.png)
![20171231112456](https://user-images.githubusercontent.com/23445929/34463833-f18c1298-ee1d-11e7-957d-aca19876f95e.png)

Confirmed on multiple configurations:
Radeon E6760 (Whistler Pro) Ubuntu 16.04; r600 driver
Radeon R3 (Kabini Integrated) Ubuntu 17.10; amdgpu driver 
Haswell Desktop Integrated (Pentium G3220T) GT1 Ubuntu 17.10
Radeon HD 7870 (Pitcairn XT) Arch; amdgpu driver

**Comment by lsalzman** [comment]
Fixed
