### ISSUE TITLE
Picking up flag segfaults.

### ISSUE THREAD

**Issue by shacknetisp** [red-eclipse/base#791]
As a change implemented in b1149681094f3a469fb0529d4881b9cb97d009a3 on line https://github.com/red-eclipse/base/blob/b1149681094f3a469fb0529d4881b9cb97d009a3/src/game/capture.cpp#L227

numflags[0] is not initialized (numflags.add) when `f.owner->clientnum` is 0 and `numflags.length()` is also 0, resulting in a segfault when access is attempted in https://github.com/red-eclipse/base/blob/b1149681094f3a469fb0529d4881b9cb97d009a3/src/game/capture.cpp#L232

I'm unsure why this line was changed, so I did not fix it myself.

**Comment by molexted** [comment]
https://gist.github.com/molexted/6d6e10ce87156229e8ce0befc6b207d1

**Comment by lsalzman** [comment]
Fixed

**Comment by molexted** [comment]
https://gist.github.com/molexted/de415ba3c7ceba88294b68b70b3bd755
