### ISSUE TITLE
Particles unaffected by variant flag

### ISSUE THREAD

**Issue by molexted** [red-eclipse/base#798]
Seen on 1.9.9 build 2032.

Unlike lights, which toggle correctly depending on which variant is selected, particles appear unaffected by setting the variant flag (13) to day or night.

On Polaris:
![20180110202959](https://user-images.githubusercontent.com/23445929/34808643-0c6088fe-f645-11e7-913f-f6e5020aca49.png)
(The particles are the snow at the bottom of the screen)

**Comment by Dziq84** [comment]
I noticed the same with sound entity, day sounds still keep playing if switched to night (until you click on given entity - then sound goes off)

**Comment by molexted** [comment]
Can confirm that selecting the particles entity does **not** fix the issue.
