### ISSUE TITLE
Searchable texture menu

### ISSUE THREAD

**Issue by qreeves** [red-eclipse/base#8]
From: http://redeclipse.net/forum/viewtopic.php?f=9&t=213

Simply enough, often I know exactly what texture i want, or from which textureset, but theres missing some kind of easy way to find the texture you want. I think a simple filter (based on texturepath) such as in the svn vars menu would do the trick. If its easy to implement, me (and probably other regular mappers too :p ) would appreciate it.

**Comment by acerspyro** [comment]
https://github.com/red-eclipse/base/pull/757 fixes this.
