### ISSUE TITLE
decals to review

### ISSUE THREAD

**Issue by Dziq84** [red-eclipse/base#801]
Some decals to check from community/dziq:  https://github.com/red-eclipse/community/tree/master/dziq/decals/dziq

<a href="https://imgur.com/No6kQkO"><img src="https://i.imgur.com/No6kQkOl.jpg" title="source: imgur.com" /></a>

from the left:
- radioactive sign
- blood splatter 2 (blood splatter 1 is already in game)
- blood splatter 3
- impact 1
- meme face
- troll face
- coffee

other decals in that repository are crapy/testing ones
Maybe something is OK to be in use for game, its all up to devs now

Also if someone have a request about given decal(s), let me know

**Comment by IceflowRE** [comment]
Iam not sure about the trolls but the rest is good :)

**Comment by IceflowRE** [comment]
Btw, wouldnt be a PR to the decals repo the better solution?

**Comment by Dziq84** [comment]
not sure, maybe, sometimes it is better to show earlier, for suggestions/criticism(?)

**Comment by IceflowRE** [comment]
You can still edit the PR soo :D

**Comment by shirepirate** [comment]
the radioactivity warning is a little too cutesy for me, would expect it to look more intimidating with perhaps not-so-thick lines. the splatters/debris are good, the faces can be a fun addition for some gimmick maps or easter eggs. the coffee sign seems a little too situational.

**Comment by q009** [comment]
We already had (have?) the baked potatoes thing on Ubik, so why not go ahead with coffee too? :P

**Comment by Dziq84** [comment]
haha true, also many of us like to sip a coffee ;p

@shirepirate, noted, I'll do something about this sign

**Comment by acerspyro** [comment]
Are there any copyright issues associated with the usage of the meme and the troll face?

**Comment by IceflowRE** [comment]
@acerspyro good point
http://cocatalog.loc.gov/cgi-bin/Pwebrecon.cgi?v1=1&ti=1,1&CNT=25&Search%5FArg=trollface&Search%5FCode=TALL&PID=2-vR81CoGMHVCtGrGLuWibR7LNfq&SEQ=20180119152956&SID=1

**Comment by Dziq84** [comment]
Im not sure about copyright issues.. 

Anyway, I'm reworked that radiation sign a little, based on shirepirate suggestion (older <> newer)

<a href="https://imgur.com/O7zMY2L"><img src="https://i.imgur.com/O7zMY2Ll.jpg" title="source: imgur.com" /></a>
<a href="https://imgur.com/dgseZTf"><img src="https://i.imgur.com/dgseZTfl.jpg" title="source: imgur.com" /></a>

**Comment by Dziq84** [comment]
hmm I guess nothing worth... I just updated decals in RE/community/dziq for anyone interested :)

**Comment by qreeves** [comment]
Didn't realise they weren't in with the Kargo files.

**Comment by Dziq84** [comment]
maybe I forgot to put these, but now all ok
