### ISSUE TITLE
Crash upon receiving damage

### ISSUE THREAD

**Issue by shacknetisp** [red-eclipse/base#802]
Backtrace: https://gist.github.com/Dziq84/a38acb119465c5548dac5640fc0eb913

This issue has only been reproduced on Windows.

I added two commits (b93d77457808522c72a27c7d74bda7f8f10bbd48 and a29389a5b48c7bda1eff1310b33be5b009e5be3c) to correct the behaviour of a relevant line of code, but the problem persists so I don't know if the two issues were related.

**Comment by qreeves** [comment]
Probably needs to be wrapped in a `min(x, 1)`, I'll take a better look at it.

**Comment by shacknetisp** [comment]
It seems this was fixed in a0ccb3de78bb417fe5230a200aeccb57273b00ad, probably can be closed now?
