### ISSUE TITLE
Edit close confirmation prevents exiting in all other modes

### ISSUE THREAD

**Issue by molexted** [red-eclipse/base#811]
Most likely, this was introduced in commit e1ea5654d38385f4e580dbe656b91620a3e2eae1.

Tested on 1.9.9 build 2103, but probably has been present since the confirmation dialog was added.

On any mode other than edit, the confirmation dialog flashes quickly onto the screen and then immediately closes, making it impossible to leave a non-edit game without using /quit or /disconnect.

How to reproduce:
1. Play any mode other than edit
2. Try to quit via the GUI

It's pretty surprising nobody's reported this one yet, considering this bug affects any player trying to play any real gamemode, but 1.9.9 must be too edit-heavy at  this point to have seen this issue.

**Comment by shacknetisp** [comment]
This seems to have been fixed: c8d108d29525b5550c0847c4daeddf8805425737

@molexted please confirm.

**Comment by molexted** [comment]
It's fixed in the sense that it no longer prevents exiting, since it was completely removed, but the UI in question needs to be rewritten so that the edit close confirmation appears at all. May be OK to rename issue or start a new one since the two are only somewhat related.

**Comment by shacknetisp** [comment]
Superseded by #871
