### ISSUE TITLE
New server console interface

### ISSUE THREAD

**Issue by Goldenbrain1** [red-eclipse/base#812]
Like I said on the world forum, I wanna try to add a new interface for the server console.
For now the server console just display what is happening on the server, but the owner can't act on the server.
The idea is to add a way to enter command in the server console like in the minecraft server.
I think for now i'll try to make an external program that will echo the server displays and enter commands in it.
The display in the new interface can be done on linux by entering `redeclipse-server > ~/.redeclipse/server_echo.out` for open the server and displaying the content of server_echo.out when the program with the interface is executed.
This way the new program can be opened anytime and display the server output, but i only know how to do it on linux, not with the c++ language.
For the command entering part, I don't know how to do yet, but i think i will have to change a bit the server files to be able to enter commands from another program.
Anyhow, i think i will need a lot of help :)

**Comment by Goldenbrain1** [comment]
I find a bit of time to code the output part, but it bugs.
The program is made of a readfile function that read the 1000 last chars of the output file (in mercy to the memory if the server is running for a very long time), and just for now the display of that function.
After i will try to display the changes of the file if there is an output of the server, but for now when i compiles it works, but when i launch it it says "segmentation fault (core dumped)", can someone tell me why ?

program : 
`
#include <stdlib.h>
#include <stdio.h>


char output[1001]; // this chain will receive  the output

void readfile () { //read the 1000 last chars of the file
FILE *file = fopen("server_echo", "r"); // open file
fseek(file, -1000, SEEK_END); // goto the end of the file

for (int i = 1; i=!1000 && output[i] != EOF ; i++) { // for the 1000 chars
    output[i] = fgetc(file); // get the char
    fseek(file, -1000+i, SEEK_END); // go left
}

};

int main()
{
    readfile(); // read the 1000 last chars of the file
    printf("%s", output); // prints the file
    return 0;
}
`

**Comment by IceflowRE** [comment]
Could you please use a codebox.

**Comment by qreeves** [comment]
This is a support request, not a bug or feature request.

In line with project policy this topic will be moved to the [Discussion Area](https://redeclipse.net/discuss).
