### ISSUE TITLE
AppImage - upon start "RedEclipse is not responding" window pops up prompting to kill the game.

### ISSUE THREAD

**Issue by swooboo** [red-eclipse/base#814]
- Version and build: 1.6.0 stable
- Observation: When starting with AppImage, "is not responding" window pops up
- Expected result: The "not responding" window should not appear. This window doesn't appear when running the non-AppImage binary.
- How to reproduce: I just installed Ubuntu 16.04 LTS and downloaded the AppImage from here - http://www.redeclipse.net/download.

```
$ cat ~/.redeclipse/log.txt 
2018-03-12 01:30.06 loading enet..
2018-03-12 01:30.06 loading game..
2018-03-12 01:30.06 version: 1.6.0-nix64-stable client (Sunset Edition) [0x790814b0]
2018-03-12 01:30.06 loading sdl..
2018-03-12 01:30.06 loading video..
2018-03-12 01:30.06 loading gl..
2018-03-12 01:30.06 renderer: GeForce GTX 1060/PCIe/SSE2 (NVIDIA Corporation)
2018-03-12 01:30.06 driver: 3.3.0 NVIDIA 390.25
2018-03-12 01:30.06 loading sound..
2018-03-12 01:30.06 allocated 32 of 32 sound channels
2018-03-12 01:30.06 loading defaults..
2018-03-12 01:30.06 loading world..
2018-03-12 01:30.06 loading config..
2018-03-12 01:30.06 configuration loaded
2018-03-12 01:30.06 loading required data..
2018-03-12 01:30.06 loading main..
```

Screenshot:

![image](https://user-images.githubusercontent.com/900603/37259963-0bf81fdc-2596-11e8-8e44-b174b5e8978d.png)

**Comment by shacknetisp** [comment]
I tried some different launching methods but cannot reproduce this on a fresh Ubuntu (Unity) 16.04. Please clarify which DE you're using (I guess Unity), and how you download and run the AppImage.

**Comment by swooboo** [comment]
Not Unity, sorry for misinforming. Using Gnome Ubuntu 16.04.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
$ 
$ dpkg --list |grep metapackage |grep Ubuntu
ii  ubuntu-gnome-desktop                        0.58.3                                     amd64        The Ubuntu GNOME metapackage
$ 
```

**Comment by shacknetisp** [comment]
Ok, I can reproduce this on Gnome. The cause appears to be that, during loading, the window does not respond to events (this doesn't seem to be AppImage specific.)

There is already one similar workaround enabled only on macOS:
https://github.com/red-eclipse/base/blob/11ac60e3cab2bfd0f250d0fc775fbc0b7d0a623d/src/engine/main.cpp#L841
Perhaps this could be expanded (@qreeves?)

**Comment by swooboo** [comment]
Interesting. Another question is why don't I experience this with the non-AppImage game? Is it because it was updated automatically upon start and AppImage doesn't do the update?

**Comment by qreeves** [comment]
Not sure of the implications in enabling it on other platforms.

@lsalzman can you weigh in please?

**Comment by lsalzman** [comment]
I guess this should be safe-ish.
