### ISSUE TITLE
Missing UI in game 

### ISSUE THREAD

**Issue by therealTitanium** [red-eclipse/base#815]
> ONLY report a feature request if it was already discussed at: https://redeclipse.net/world/issues
> PLEASE search the issues before submitting your own. Be sure to rename your `config.cfg` and check if the problem still occurs.

- Version and build: 1.6.0 Stable
- Observation: when start the game (online and offline) there's missing almost all the UI (console, crosshair, radar, scoreboard and statiscs, but the "menus" are intact)
- Expected result: tryed to fixed byreinstal redeclipse, and changing options in the game, but without
result
- How to reproduce: i just installed the new redeclipse version (1.6.0)

![2018-03-18 1](https://user-images.githubusercontent.com/37527392/37579439-b4292e5e-2b03-11e8-8f17-e392bfeccea5.png)

**Comment by qreeves** [comment]
You've accidentally disabled the HUD. Try clearing your `config.cfg` or removing the `hidehud` line from it. Where to find your user data [depends on the operating system](http://www.redeclipse.net/docs/FAQ#where-do-i-find-screenshots-logs-and-other-user-data).
