### ISSUE TITLE
Groups of decals pastes incorrectly when all orientation flags are set to 0

### ISSUE THREAD

**Issue by molexted** [red-eclipse/base#816]
Tested on RE 1.9.9 build 2103.

This is quite the specific  bug, only occurring under the following conditions:

- All of the orientation flags (yaw,pitch,roll) are set to 0
- The decal is selected as part of a group by a command such as `/entfindinsel`
- The decal is then copied as a volume selection (does not have to be with other decals) and pasted

The result is that the decal will not be faithfully pasted; instead, due to all the orientation flags being set to 0, the game will automatically rotate the decal to face you, which is not what an editor wants when trying to faithfully reproduce a copied decal set. (This was found when trying to copy/paste sets of letters onto the hangars in ctf13)

"Correct" pasting with `roll` set to 0:
![20180324204030](https://user-images.githubusercontent.com/23445929/37871505-300e2d04-2fa4-11e8-8cda-3eb1ed8909fb.png)

Result of copy/pasting zero'd flags:
![20180324203214](https://user-images.githubusercontent.com/23445929/37871460-253a2a64-2fa3-11e8-9ced-a391486cbbb5.png)

![20180324203220](https://user-images.githubusercontent.com/23445929/37871459-25259428-2fa3-11e8-9c02-f4bd748f250a.png)

**Comment by qreeves** [comment]
Yeah, one of the big differences in RE is that we don't do the automatic rotation stuff Cube 2/Tesseract does. This is obviously a result of the port accidentally including this behaviour.

**Comment by molexted** [comment]
9ad3a69 seems to break things worse:
![20180602223505](https://user-images.githubusercontent.com/23445929/40883568-6c633b08-66b5-11e8-8357-da53aa52cabb.png)
 Passing `/entset decal 35 0 0 0 56 0 0`  , which is 0,0,0 for the three orientation angles, leads to the decal moving to the cursor normal as shown. Attempting to use the number keys + scroll wheel to get to 0,0,0 leads to reseting the decal to the cursor normal upon reaching 0,0,0.
