### ISSUE TITLE
Translucent ammo not rendered behind alpha/glass

### ISSUE THREAD

**Issue by molexted** [red-eclipse/base#820]
Tested in RE 1.9.9 build 2115.
![20180510213659](https://user-images.githubusercontent.com/23445929/39906951-866aa8b0-549a-11e8-8e12-8afc839b26db.png)
![20180510213655](https://user-images.githubusercontent.com/23445929/39906952-867ecaf2-549a-11e8-915a-4affa5ff1684.png)
![20180510214120](https://user-images.githubusercontent.com/23445929/39907005-ec81773c-549a-11e8-9e67-9b57c5fb1f8f.png)

Due to Tesseract's lack of tolerance for multiple alpha layers, the translucent non-pickupable ammo is not rendered behind alpha material nor glass, leaving only the glow surrounding it. 

Assuming that it is not practical to actually implement double alpha (which would be great for much more than this bug), it may be prudent to simply disable ammo models which are non-pickupable (due to loadout not having that weapon). It is also possible to downsize or grayscale useless ammo rather than alpha it. 

It is not reasonable to expect every mapper to never have alpha in such a position that this may occur, as it requires the elimination of all non-outside wall alpha to avoid.

**Comment by Dziq84** [comment]
the same for particles... It is very strange that these are not rendered behind other alpha materials..

**Comment by qreeves** [comment]
Yeah, we need to heavily review the use of alpha blending in general. It's given everything a muted look.

**Comment by qreeves** [comment]
Blending is now turned off by default.
