### ISSUE TITLE
crash when playing Survivor

### ISSUE THREAD

**Issue by Dziq84** [red-eclipse/base#827]
Some players tell me that there is a crash when playing Survivor (mostly around half-time), so I decided to check that and yes, game crashed 3/3 times when playing Survivor

here its full backtrace:
https://gist.github.com/Dziq84/3e14c17ad1d17037f9420e49af168b27

**Comment by qreeves** [comment]
master, stable, or both?

**Comment by Dziq84** [comment]
lol, of course in master :), sorry, my fault
