### ISSUE TITLE
Player blending on race is too low/almost invisible

### ISSUE THREAD

**Issue by SniperGoth** [red-eclipse/base#828]
Playing some race/time-trial(i still preffer to call it TT ) with dziq, i noticed that other players are almost invisible and impossible to follow.
![20180706181257](https://user-images.githubusercontent.com/24359960/42401057-4cb2cdd2-814a-11e8-9a6e-5c541ea1270f.png)
![20180706182144](https://user-images.githubusercontent.com/24359960/42401058-4cd7567a-814a-11e8-87e0-dee1533072f6.png)
![20180706182242](https://user-images.githubusercontent.com/24359960/42401059-4cf51d9a-814a-11e8-8424-ec3c46328ff7.png)

Is there a var to control it, or make the default value way higher?

**Comment by qreeves** [comment]
`playerghostblend` which seems to be set to `0.125` (1/8), probably needs to be more like `0.35`

**Comment by Dziq84** [comment]
while this blending it's possible on races, maybe the same can be enabled for editing too? (its ok, but 'ghosts' are disabled now when someone switch to $editing)

**Comment by molexted** [comment]
Didn't change the default values, but there is now a race opacity slider in settings-gameplay as of e223067b2ecadc5d4a70b3ce5880a6ddfc9badbc, and an edit opacity slider in [e]-[q] (multiplayer) as of f34bc3d323b0b883f4b0c3974d62bb51fd1d9146.
