### ISSUE TITLE
UI does not show on game

### ISSUE THREAD

**Issue by iblowmymind** [red-eclipse/base#836]
- Version and build: 1.6.0-mac64-stable
- Related discussion: ???
- Observation: I entered the game, and... the User Interface doesn't work. It won't show up, also in edit menu, in edit compass, you can't see it, but you can click it. (Update: Without the config it seems to be working.)
- Expected result: I don't know.
- How to reproduce: I don't know.

```
It kinda works. Now we need to understand what setting caused it.
```

**Comment by IceflowRE** [comment]
You could upload your config here, so we can analyze the problem.
**But please remove your auth key**, if you have one and remove other private things.

**Comment by iblowmymind** [comment]
Nope. It worked. Changed the config name and it's good.
