### ISSUE TITLE
guibackground alignment

### ISSUE THREAD

**Issue by bonifarz** [red-eclipse/base#85]
If a _guibackground_ (or _guifill_) command is not the first element of its _guilist_, the result is quite strange. The height and width of the background (and frame) fits perfectly for the entire _guilist_ block, but the positioning is off. The backgrounded is shifted as if it was an element of the list. In most cases, this is no problem. The only exception i can think of: Using the background color for a hover effect, for example to create a pretty button. (In this case, one can just use a negative guistrut, though.)

If this is intended for reasons of efficiency, just close the report as won't fix :wink:

**Comment by coornio** [comment]
I'm pretty sure this is intended behavior. It likely checks whether the first element in a guilist is either a guifill, a guibackground or a similar command and applies its effects before skipping over it and counting the rest of the elements like it normally would.
Not the best of ideas if that is the case if you ask me, considering a condition may wish to call one of these commands later in a guilist..

**Comment by graphitemaster** [comment]
Not applicable anymore since newui
