### ISSUE TITLE
redeclipse.bat does not handle parenthesis

### ISSUE THREAD

**Issue by freezurbern** [red-eclipse/base#86]
## Before 1.5 release this needs to be fixed.

the update.bat file does not work if a path such as `C:\Program Files (x86)`, contains parenthesis.

The default installation directory on 64-bit Windows 7 is `C:\Program Files (x86)`, so this is critical.

**Comment by shirepirate** [comment]
for me the update.bat actually works fine and downloads binaries, but redeclipse.bat won't work unless parenthesis are removed from a parent folder

**Comment by freezurbern** [comment]
I thought it was the update script but redeclipse.bat is actually the problem.

**Comment by ZeroKnight** [comment]
If memory serves, just make sure the path is surrounded in double quotes and it should work fine
