### ISSUE TITLE
Enabling /showloadinglogos causes red fill on title screen

### ISSUE THREAD

**Issue by molexted** [red-eclipse/base#862]
Setting `showloadinglogos` to 1 causes an ugly red box in the top right corner of the title screen. It takes up the same area as the logo does during map loading (which loads properly), and disappears as it should while in game.

`showloadinglogos 0`
![screenshot from 2019-01-30 14-07-08](https://user-images.githubusercontent.com/23445929/52016032-5fa83980-2498-11e9-8f54-84ecd46dbfc4.png)

`showloadinglogos 1`
![screenshot from 2019-01-30 14-06-27](https://user-images.githubusercontent.com/23445929/52016033-6040d000-2498-11e9-9eac-02496384abce.png)

As indicated in the screenshots, this was reproduced on build 2312, but it is probably quite a bit older than that (i'd guess it dates back to when the title screen bg animations happened).

Edit: confirmed on both my Intel HD 5500 laptop and my Radeon R5 340 desktop.

**Comment by TSnake41** [comment]
After few investigations and testing, it seems that in the menu, the "hudbackgroundshader" (the shader used to draw the fancy background) is also used (by accident) to draw the logo which causes issues.

https://github.com/red-eclipse/base/blob/524d6f688c61d2262ed91295523cba9ff45a3661/src/game/hud.cpp#L1779
(we do `hudbackgroundshader->set();` which sets the shader for the background, but also for the code of `showloadinglogos`)

A fix (or workarround) is by using the hud shader to draw the logo (which looks working).
```c
hudshader->set();
```
before this 
```c
if(showloadinglogos)
{
    gle::colorf(1, 1, 1, 1);

    t = textureload(logotex, 3);
    glBindTexture(GL_TEXTURE_2D, t->id);
    drawtexture(w-1024, 0, 1024, 512);
}
```

And then, it works
![image](https://user-images.githubusercontent.com/8642647/53262934-4336a000-36d8-11e9-882b-d2069e49b99a.png)

Or we can disable it in menus by moving the ```if (showloadinglogos)``` block in the loading rendering block like this.

```c
if(!t || t == notexture)
{
    ... // main menu rendering
}
else
{
    glBindTexture(GL_TEXTURE_2D, t->id);
    float offsetx = 0, offsety = 0;
    if(showloadingaspect)
    {
        if(w > h) offsety = ((w-h)/float(w))*0.5f;
        else if(h > w) offsetx = ((h-w)/float(h))*0.5f;
    }
    drawquad(0, 0, w, h, offsetx, offsety, 1-offsetx, 1-offsety);
    
    if(showloadinglogos)
    {
        gle::colorf(1, 1, 1, 1);

        t = textureload(logotex, 3);
        glBindTexture(GL_TEXTURE_2D, t->id);
        drawtexture(w-1024, 0, 1024, 512);
    }
}
```

So the logo will only rendering when loading, in the menu, it does not render.

I am not sure if the logo should render in the main menu, so,
