### ISSUE TITLE
@[weapname]lightpersist only has two apparent modes

### ISSUE THREAD

**Issue by molexted** [red-eclipse/base#872]
@[weapname]lightpersist is defined from 0 to 15 but only appears to have two actual distinct modes, for odd and even arguments. This appears to affect all weapons equally.

Tested in v1.9.9 b2352.

Screenshots (`pistollightradius = 128` for clarity)

`pistollightpersist 0|3|5|7|9|11|13|15`
![lightpersist0](https://user-images.githubusercontent.com/23445929/53428254-4fa04e80-399f-11e9-94dd-acd39afb2e16.png)

`pistollightpersist 0|2|4|8|10|12|14`
![lightpersist1](https://user-images.githubusercontent.com/23445929/53428256-4fa04e80-399f-11e9-8440-2afb079002e8.png)

**Comment by qreeves** [comment]
This is a bitwise flag:
- 1 = Dynamic light emission
- 2 = Material colour on weapon itself
- 4 = Player hint (glow around player)
- 8 = Player hint when powering weapon
