### ISSUE TITLE
discord-rpc.dll and steam_api64.dll missing when REDECLIPSE_BRANCH=devel

### ISSUE THREAD

**Issue by acerspyro** [red-eclipse/base#874]
On Windows 10 64-bit, downloading Red Eclipse from the website and adjusting your `branch.txt` to say `devel` results in a game that cannot start due to `discord-rpc.dll` and `steam_api64.dll` being missing.

![image](https://user-images.githubusercontent.com/4400999/53847524-19eefd00-3f7f-11e9-95e5-82258dd2cf94.png)

![image](https://user-images.githubusercontent.com/4400999/53847527-1d828400-3f7f-11e9-8a7c-100a4009cb3c.png)

This is on a fresh install of Red Eclipse.

**Comment by shacknetisp** [comment]
I think `devel` is for compiling it yourself (whereas `master` is for normal use). So you should compile USE_DISCORD and USE_STEAM set to 0.

**Comment by acerspyro** [comment]
You are correct, `master` should have been used here.
This resolves the issue, but please verify that the documentation is updated correctly.

Closing.

**Comment by shacknetisp** [comment]
Documentation where?

**Comment by acerspyro** [comment]
Should probably be placed in any of these places:

- https://www.redeclipse.net/docs/Information-for-v2
- https://www.redeclipse.net/docs/Install-Guide
- https://www.redeclipse.net/docs/Contributing
- https://www.redeclipse.net/docs/FAQ
