### ISSUE TITLE
cannot open red eclipse

### ISSUE THREAD

**Issue by mrbeeper** [red-eclipse/base#881]
> ONLY report a feature request if it was already discussed at: https://redeclipse.net/world/issues
> PLEASE search the issues before submitting your own. Be sure to rename your `config.cfg` and check if the problem still occurs.

- Version and build: [version] [build]
- Related discussion: red-eclipse/world#ID
- Observation: [what happened?]
- Expected result: [what did you expect to happen?]
- How to reproduce: [what steps can be taken to reliably reproduce the issue?]

```
Insert the contents of your `log.txt` here.
```

**Comment by Calinou** [comment]
We need more information to be able to help. What's your operating system and graphics card?

**Comment by molexted** [comment]
No response in several days, and the issue opener didn't even bother to overwrite the stock text. Closing; can open again if there is a response.
