### ISSUE TITLE
(macOS) deployment not working & dyld: Library not loaded: @rpath/libsteam_api.dylib

### ISSUE THREAD

**Issue by Xx-Henry-xX** [red-eclipse/base#883]
I'm using macOS Mojave 10.14.4.
As the installation guide stated, I unzipped the tarball for the macOS release (1.6.0) to my downloads folder, and opened the app, which was followed by a long download time & one admin password entry possibly because of `touch: test.tmp: Read-only file system`, and then there was `sudo: exec: command not found`. While the game did run, the file deployment didn't work so that I had to go through the same loading process every time I played.

So I moved the app to the Applications folder, opened it, waited for the download to complete, and this happened:
```
dyld: Library not loaded: @rpath/libsteam_api.dylib
  Referenced from: /Applications/Red Eclipse.app/Contents/Resources/bin/redeclipse.app/Contents/MacOS/redeclipse_universal
  Reason: image not found
Abort trap: 6
(The rest is the usual exit command output)
```
The same happened when I moved the app outside of the Applications folder to the desktop except for the directory.
Any help would be appreciated. Thank you.

**Comment by qreeves** [comment]
I'll have to investigate this further with my dust covered old mac mini, but it is likely your issue isn't an isolated incident as there have been a lot of changes recently which haven't been fully tested on macOS.

As this issue could only be from the development branch, can you confirm the stable version runs OK for you?

**Comment by q009** [comment]
I could run some tests as well

**Comment by Xx-Henry-xX** [comment]
I thought the macOS release from https://www.redeclipse.net/download was the stable release?

**Comment by qreeves** [comment]
Sorry, yes you did say that. It shouldn't even be looking for the Steam API library in stable, so there might be some cross contamination between the branches.

**Comment by ToniCHiQuit** [comment]
MacOS Mojave 10.14.5 and have exactly the same problem

**Comment by nesterow** [comment]
Same here. Mojave 10.14.5

**Comment by nesterow** [comment]
[redeclipse.zip](https://github.com/red-eclipse/base/files/3439457/redeclipse.zip)
A build that doesn't require `libsteam_api.dylib`. 
Decompress this archive then do `right click -> show package contents`, then copy directory `Contents` and open `/Applications/redeclipse.app/` and paste the folder. Pick `replace` action for files and `merge` action for directories

**Comment by qreeves** [comment]
Should be fixed now, sorry for the delay. The contamination was on my MacMini.

**Comment by nesterow** [comment]
@qreeves Thanks, everything works on my mac.

**Comment by qreeves** [comment]
Awesome, thanks for confirming. Will close this issue now.
