### ISSUE TITLE
mirrored notexture

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#89]
If theres a non existing skybox choosen the notexture image is mirrored.

To repeat:
load a map with edit mode
go in edit and write (for example) "/skybox nonexisting"
show what happend :D

**Comment by ZeroKnight** [comment]
That's the point?

**Comment by IceflowRE** [comment]
yeah :D looks not really well but is not a bug its maybe a beautification ^^

**Comment by freezurbern** [comment]
I think the skybox should look bad if you're using something nonexistant, so you know something is wrong.

**Comment by bonifarz** [comment]
After all, you're looking at the inner sides of a cube's faces :grinning:
