### ISSUE TITLE
Ammo in classic mode should stack

### ISSUE THREAD

**Issue by lambda-11235** [red-eclipse/base#894]
Currently in classic mode when you pick up a weapon you are holding you discard it, effectively switching ammo capacities. This is kind of annoying with the more limited ammo we have now, as you have to guess if the weapon your picking up has more ammo. Plus, it's counter intuitive to the other modes. I propose that ammo should stack like in other modes.

**Comment by qreeves** [comment]
Seems to have been fixed when I fixed ammo stacking.
