### ISSUE TITLE
Suggested default setting changes

### ISSUE THREAD

**Issue by Calinou** [red-eclipse/base#90]
Feel free to take them or not. You can post additional ones here, too.

```C++
// Game variables:
aniso 16 // [Current: 0] 16× anisotropy by default. If this is too heavy, then go for 4× anisotropy by default, but 0 is really ugly.
animationinterpolationtime 200 // [Current: 150] Smoother animations (this is the value used in Tesseract).
smoothmove 100 // [Current: 90] Slightly higher network smoothing.

// Map variables:
watersubdiv 3 // [Current: 2] Makes waves less detailed, but more realistic overall.
waterlod 3 // [Current: 1] Lets you see water waves from far away.
```

**Comment by qreeves** [comment]
I think I'd like some feedback from the community before pushing a somewhat radical change like this. I'm all for it, if it tests well. We're on the crux of a release so it would be wise to know if it'll be OK.

**Comment by freezurbern** [comment]
I can't find `smoothtime`, only `smoothmove`. How does this variable affect gameplay with higher pings, for example in the range of 250-350?

**Comment by bonifarz** [comment]
I have the impression that default settings are chosen to work with minimum hardware, while the in-game options give some clues how to make things prettier and how demanding those settings are.
