### ISSUE TITLE
mucis off radioboxes broken

### ISSUE THREAD

**Issue by IceflowRE** [red-eclipse/base#97]
When you change the radioboxes in options to off or on nothing happens. And still the music dont player after you make the volume higher 0 again.

**Comment by coornio** [comment]
So i assume that he means the music doesn't play after you set the volume to 0 and then back up. That is normal. The music keeps playing regardless of volume. Whether it continues playing after the song ends depends on whether the volume is > 0. If it's not, it won't play anything. If it is, it will start a new song as soon as something tells it to. It won't pick off from where it left off.

As for the radioboxes, I have no idea what you're talking about.

**Comment by shirepirate** [comment]
is this an actual bug? can you explain further the steps to reproduce it?
