### ISSUE TITLE
Multiplayer map cache

### ISSUE THREAD

**Issue by Calinou** [red-eclipse/base#98]
When you play on a server with a custom map, the map should automatically be saved to a `cache/` directory. This way, you can play it locally later, and you don't need to re-download the map again.

If the map is different (eg. it has been updated), then it should be discarded from cache and a new map should be acquired from the server.

**Comment by Croydon** [comment]
Imo this would require at least a max. cache size and maybe also an expire time of each cached map.

**Comment by Calinou** [comment]
It doesn't, look at Xonotic, it has neither. :P

**Comment by Croydon** [comment]
If not this would just flood your device over the months/years...no?

**Comment by Calinou** [comment]
This is rarely a problem. People can clear it by hand anyway, or there can be a button in-game for this.

**Comment by shirepirate** [comment]
what, like /Redeclipse/temp/maps? every map you ever download is saved there, whether you pressed save or not. in other words there is already a cache folder.

**Comment by Calinou** [comment]
Yeah, but it is not used right now, so there's no caching system. There's also no graphical way of playing on cached maps offline.

**Comment by shirepirate** [comment]
most of the creations in there tend to be a collaboration of multiplayer edit sessions and time trial maps anyway, the general overall quality of these maps is very poor. i'm assuming that's why. if you purposefully save a map however, it is available in-game.

**Comment by Calinou** [comment]
Maps would only be cached outside of editing mode.

**Comment by shirepirate** [comment]
and if a map has the same name as an official map or another cached map? what file will take precedence? once a map has been changed there really aren't any uniquely identifying factors afaik

there won't be different maps because of version gaps in this release, as everyone will always have the same updated maps after every minor stable release.

**Comment by zaquest** [comment]
I also would like to suggest to upload custom models, textures, sounds for map. Now its very limited. Either map is in release with all it's components or parts of map are missing for players who didnt install them manually.

**Comment by shirepirate** [comment]
what the hell are you even talking about? try to post on topic here

**Comment by freezurbern** [comment]
This may be related to #242

**Comment by bonifarz** [comment]
So, is this issue closed with CRC lock, as pointed out by @freezurbern? Or do you want me to add this to the editing menus, @Calinou?
> There's also no graphical way of playing on cached maps offline.
Should be fairly trivial to add a simple menu for editing temp maps, so you can save them properly.

**Comment by bonifarz** [comment]
home/temp/maps can be browsed in the editing menus, mapinfo: e654fff

**Comment by qreeves** [comment]
Nothing in master should be using 'temp' anymore. If it is, it is a bug. Maps now save using their CRC to create a unique name: `mapname_0x12345678`

**Comment by bonifarz** [comment]
Good to know. So downloaded maps will be saved automatically this way in home/maps/?

**Comment by qreeves** [comment]
Yep. Makes things simpler.

**Comment by bonifarz** [comment]
Agreed. I'll keep the functionality in the menu for the backport, but it will be trivial remove later.
So, I guess this ticket and #21 are fixed then.
